### PR TITLE
Fix MSYS2 dll's are not found by modulegraph

### PR DESCRIPTION
**Pull request by danyeaw**
Fixes: #4125

This PR replaces #4240 that was never finished by updating the commit messages to be more descriptive and adding a changelog entry.

1. MINGW Python packages in MSYS2 name Windows dll files with a -cpython-37m.dll extension. Loading a Python module that depends on a dll, for example struct and zlib, results in a ModuleNotFoundError since modulegraph is not looking for files with this naming convention.

2. Fixes double processing of dependencencies when using COLLECT after EXE. When processing of MINGW Python dll files, this results in corrupted file paths, for example when processing the _struct
dll the resulting filepath is dllruct-cpython-37m/_struct-cpython-37m.dll instead of just
_struct-cpython-37m.dll.

### CODE REVIEW

**Comment by danyeaw** [comment]
@htgoebel I really appreciate this awesome library ❤️. If you get a chance, could you please review this PR? I think it is ready 👍

**Comment by danyeaw** [comment]
Any update on whether this can be merged?

**Comment by danyeaw** [comment]
@htgoebel should I patch this downstream in a PyInstaller MINGW package instead? I realize MSYS2 is a niche platform, and I understand if you aren't able to prioritize supporting it for things like packaging GTK apps for Windows. I've been trying to help triage Issues, hopefully that helps some.

**Comment by htgoebel** [comment]
@danyeaw Thanks for this pull-request, which I just merged.

If MSYS2 would be more compatible with standard windows, this would be great and easy developing application using GTK. But this is a different story :-)

**Comment by danyeaw** [comment]
@htgoebel Thanks so much for merging this, I really appreciate it! :gift_heart:

I also wish that MSYS2 was a better supported platform for Python, it is so much work patching issues everywhere :smile:

**Comment by BoboTiG** [comment]
I missed to post here: one of the changes broke AppImage creations (see #4693).
The proposed solution by @Legorooj is to try another version of the patch, but I can't test. Maybe @danyeaw would mind to try out? 🙏

**Pull request merged**
