### PR TITLE
Update waf to version 1.8.20

### PR DESCRIPTION
**Pull request by goodtiding5**
Update waf to version 1.8.20, which added the support for SUNWcc compile V5.0 on Solaris/Sparc 10 systems.

### CODE REVIEW

**Comment by matysek** [comment]
Please fix the wscript that bootloader compiles on Windows. Look at the output on appveyor for more info:
https://ci.appveyor.com/project/matysek/pyinstaller/build/853

**Comment by htgoebel** [comment]
@goodtiding5 There is not need to close this pull-request, you can simply update it. See http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

Splitting the commit is easy using `gitk` (to create a new branch at the place you want) and `git gui` to amend the last commit. In git gui you can include and exclude single lines and file from teh commit easily.

**Comment by htgoebel** [comment]
@goodtiding5 Are you going to update the pull-request?

**Comment by htgoebel** [comment]
@goodtiding5 Pinging. I'd like to have this included soon. Are you going to update the pull-request, or should I take over?

**Comment by htgoebel** [comment]
I'm going to merge this manually.

**Comment by htgoebel** [comment]
Merged via 3027ddc.

**Pull request closed without merging**
