### PR TITLE
fix unable to find "C:\Users\user\nltk_data" #3799

### PR DESCRIPTION
**Pull request by sebastianhohmann**
Had the same issue as here:
https://github.com/pyinstaller/pyinstaller/issues/3799

proposed change is what htgoebel suggested

### CODE REVIEW

**Comment by bjones1** [comment]
Needs correct commit naming and changelog -- @Legorooj, would you guide on this?

On a side note, this is why we want to push hooks to other packages -- too much work to maintain for the core.

**Comment by Legorooj** [comment]
@bjones1 will do

I agree. I also think that sometimes the hook docs are a bit confusing - I might PR with more samples to hooksample.

**Comment by Legorooj** [comment]
@sebastianhohman could you fix the commit message as described [here](https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html), and add a changelog as described [here](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html)

**Comment by bjones1** [comment]
@Legorooj PRs welcome. Also, relaxing these requirements (which many authors stumble on) in a non-PyInstaller repo would be nice.

**Comment by yikir** [comment]
thank you bro!

**Comment by Legorooj** [comment]
If this is not updating in a week, I'm closing it and will open my own fixed copy PR

**Comment by sebastianhohmann** [comment]
Apologies for the delay. I have made an attempt (with some considerable help) to comply with the guidelines. Please feel free to ignore, close and open a fixed PR if anything is off.

**Comment by Legorooj** [comment]
@sebastianhohmann it's all good now. Wait a few days and it'll get merged (Probably by the end of the week).

**Pull request merged**
