### PR TITLE
Misc Django import finder bugs

### PR DESCRIPTION
**Pull request by ciarancourtney**
Will probably fix https://github.com/pyinstaller/pyinstaller/issues/2281 among other issues where Django <1.8 settings were assumed, This PR assumes only Django >=1.8 is supported.

### CODE REVIEW

**Comment by karthikdesai** [comment]
Hi, i pulled in your PR on top of develop branch on pyinstaller to test on my Django but i have some problems
Following is the log if it helps you
`69 INFO: PyInstaller: 3.5.dev0+g567c8560.mod
69 INFO: Python: 2.7.13
69 INFO: Platform: Windows-7-6.1.7601-SP1
75 INFO: UPX is not available.
75 INFO: Extending PYTHONPATH with paths
['D:\\Projekte\\Multicopter\\agrar_groundstation',
 'D:\\Projekte\\Multicopter\\agrar_groundstation\\agrar_server']
75 INFO: checking Analysis
79 INFO: Building Analysis because Analysis-00.toc is non existent
79 INFO: Initializing module dependency graph...
79 INFO: Initializing module graph hooks...
85 INFO: Analyzing hidden import 'krone'
95 INFO: Analyzing hidden import 'smart_farming_server'
109 INFO: Analyzing hidden import 'utils'
125 INFO: Analyzing hidden import 'corsheaders'
2889 INFO: Processing pre-find module path hook   distutils
2889 INFO: distutils: retargeting to non-venv dir 'C:\\Progs\\Python27\\Lib\\distutils'
3139 INFO: Processing pre-safe import module hook   _xmlplus
6095 INFO: running Analysis Analysis-00.toc
6099 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by D:\Projekte\Multicopter\agrar_groundstation\venv\Scripts\python.exe
6194 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
6194 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
6194 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
6194 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
6194 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
6284 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
6284 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57.manifest
6284 INFO: Searching for file msvcr90.dll
6284 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcr90.dll
6284 INFO: Searching for file msvcp90.dll
6284 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcp90.dll
6284 INFO: Searching for file msvcm90.dll
6284 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\msvcm90.dll
6375 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
6375 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
6375 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
6375 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
6375 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
6375 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
6490 INFO: Caching module hooks...
6494 INFO: Analyzing manage.py
6500 INFO: Loading module hooks...
6500 INFO: Loading module hook "hook-distutils.py"...
6500 INFO: Loading module hook "hook-sysconfig.py"...
6500 INFO: Loading module hook "hook-django.core.management.py"...
8004 INFO: Excluding import 'IPython'
8004 INFO:   Removing import of IPython from module django.core.management.commands.shell
8004 INFO: Import to be excluded not found: 'Tkinter'
8004 INFO: Import to be excluded not found: 'matplotlib'
8004 INFO: Loading module hook "hook-xml.py"...
8009 INFO: Loading module hook "hook-django.db.backends.py"...
8529 INFO: Loading module hook "hook-httplib.py"...
8529 INFO: Loading module hook "hook-encodings.py"...
9034 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
9034 INFO: Loading module hook "hook-xml.dom.domreg.py"...
9034 INFO: Loading module hook "hook-pkg_resources.py"...
9325 INFO: Processing pre-safe import module hook   win32com
9644 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
9644 INFO: Loading module hook "hook-django.core.mail.py"...
9704 INFO: Loading module hook "hook-pytz.py"...
9744 INFO: Loading module hook "hook-pywintypes.py"...
9970 INFO: Loading module hook "hook-sqlite3.py"...
10039 INFO: Loading module hook "hook-win32com.py"...
10450 INFO: Loading module hook "hook-django.core.cache.py"...
10544 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "D:\Projekte\Multicopter\agrar_groundstation\venv\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 45, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal201", "gdal20", "gdal111", "gdal110", "gdal19"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
11704 INFO: Determining a mapping of distributions to packages...
24055 INFO: Packages required by django:
['pytz', 'pytz']
24055 INFO: Django root directory D:\Projekte\Multicopter\agrar_groundstation\agrar_server\smart_farming_server
Exception in thread Thread-2 (most likely raised during interpreter shutdown):26215 INFO: Collecting Django migration scripts.
30340 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
30850 INFO: Processing pre-find module path hook   site
30850 INFO: site: retargeting to fake-dir 'd:\\projekte\\multicopter\\agrar_groundstation\\venv\\lib\\site-packages\\pyinstaller-3.5.dev0+g567c8560.mod-py2.7.egg\\PyInstaller\\fake-modules'
34840 WARNING: Hidden import "django.contrib.contenttypes.context_processors" not found!
34845 WARNING: Hidden import "krone.context_processors" not found!
34855 WARNING: Hidden import "django.contrib.auth.templatetags" not found!
34986 WARNING: Hidden import "django.contrib.contenttypes.templatetags" not found!
35016 WARNING: Hidden import "django.contrib.admin.context_processors" not found!
35016 WARNING: Hidden import "django.contrib.sessions.context_processors" not found!
37585 WARNING: Hidden import "django.contrib.staticfiles.context_processors" not found!
37585 WARNING: Hidden import "corsheaders.templatetags" not found!
37585 WARNING: Hidden import "corsheaders.context_processors" not found!
37611 WARNING: Hidden import "django.contrib.messages.templatetags" not found!
37700 WARNING: Hidden import "django.contrib.sessions.templatetags" not found!
37705 WARNING: Hidden import "krone.templatetags" not found!
37766 INFO: Loading module hook "hook-pythoncom.py"...
38026 INFO: Loading module hook "hook-lxml.etree.py"...
38026 INFO: Loading module hook "hook-pydoc.py"...
38026 INFO: Excluding import 'Tkinter'
38030 INFO:   Removing import of Tkinter from module pydoc
38030 INFO: Loading module hook "hook-_tkinter.py"...
38155 INFO: checking Tree
38155 INFO: Building Tree because Tree-00.toc is non existent
38155 INFO: Building Tree Tree-00.toc
38320 INFO: checking Tree
38320 INFO: Building Tree because Tree-01.toc is non existent
38320 INFO: Building Tree Tree-01.toc
38340 INFO: Loading module hook "hook-django.contrib.sessions.py"...
38405 INFO: Loading module hook "hook-cv2.py"...
38405 INFO: Loading module hook "hook-numpy.py"...
38405 INFO: Loading module hook "hook-setuptools.py"...
39000 INFO: Loading module hook "hook-numpy.core.py"...
39075 INFO: Loading module hook "hook-lib2to3.py"...
39171 INFO: checking Tree
39171 INFO: Building Tree because Tree-02.toc is non existent
39171 INFO: Building Tree Tree-02.toc
39200 INFO: Looking for ctypes DLLs
39296 WARNING: Ignoring /usr/lib/libc.dylib imported from d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\monotonic.py - ctypes imports are only supported using bare filenames
39330 INFO: Analyzing run-time hooks ...
39340 INFO: Including run-time hook 'pyi_rth__tkinter.py'
39340 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
39345 INFO: Including run-time hook 'pyi_rth_pkgres.py'
39345 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
39350 INFO: Including run-time hook 'pyi_rth_django.py'
39371 INFO: Looking for dynamic libraries
39536 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
39536 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_7dd1e0ebd6590e0b.manifest
39536 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
39536 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
39631 INFO: Searching for assembly x86_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
39631 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c.manifest
39631 INFO: Searching for file mfc90.dll
39631 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90.dll
39631 INFO: Searching for file mfc90u.dll
39631 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90u.dll
39631 INFO: Searching for file mfcm90.dll
39631 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90.dll
39631 INFO: Searching for file mfcm90u.dll
39631 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90u.dll
39715 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.21022.8_none_5926f98ceadc42c2.manifest
39715 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_7dd1e0ebd6590e0b.manifest
39715 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_ecff360cfb2594f3.manifest
39715 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
39715 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
52796 INFO: Looking for eggs
52796 INFO: Using Python library C:\WINDOWS\system32\python27.dll
52796 INFO: Found binding redirects: 
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
52815 INFO: Warnings written to D:\Projekte\Multicopter\agrar_groundstation\agrar_server\build\manage\warn-manage.txt
53055 INFO: Graph cross-reference written to D:\Projekte\Multicopter\agrar_groundstation\agrar_server\build\manage\xref-manage.html
54885 INFO: checking PYZ
54885 INFO: Building PYZ because PYZ-00.toc is non existent
54885 INFO: Building PYZ (ZlibArchive) D:\Projekte\Multicopter\agrar_groundstation\agrar_server\build\manage\PYZ-00.pyz
57250 INFO: Building PYZ (ZlibArchive) D:\Projekte\Multicopter\agrar_groundstation\agrar_server\build\manage\PYZ-00.pyz completed successfully.
57600 INFO: checking PKG
57600 INFO: Building PKG because PKG-00.toc is non existent
57600 INFO: Building PKG (CArchive) PKG-00.pkg
57631 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
57635 INFO: Bootloader d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\pyinstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\bootloader\Windows-32bit\run.exe
57635 INFO: checking EXE
57635 INFO: Building EXE because EXE-00.toc is non existent
57641 INFO: Building EXE from EXE-00.toc
57641 INFO: Appending archive to EXE D:\Projekte\Multicopter\agrar_groundstation\agrar_server\build\manage\manage.exe
57661 INFO: Building EXE from EXE-00.toc completed successfully.
57680 INFO: checking COLLECT
57680 INFO: Building COLLECT because COLLECT-00.toc is non existent
57680 INFO: Building COLLECT COLLECT-00.toc
57720 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
80437 INFO: Building COLLECT COLLECT-00.toc completed successfully.
`

And the following the error i get when i try to run the `manage.exe runserver`
`[3532] Failed to execute script manage
Traceback (most recent call last):
  File "agrar_server\manage.py", line 22, in <module>
  File "django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "django\core\management\__init__.py", line 331, in execute
    _parser = self.fetch_command('runserver').create_parser('django', 'runserver')
  File "django\core\management\__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "django\core\management\__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "importlib\__init__.py", line 37, in import_module
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\management\commands\runserver.py", line 12, in <module>
    from django.core.servers.basehttp import (
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\servers\basehttp.py", line 18, in <module>
    from django.core.wsgi import get_wsgi_application
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\handlers\wsgi.py", line 11, in <module>
    from django.core.handlers import base
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\handlers\base.py", line 17, in <module>
    from .exception import (
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\core\handlers\exception.py", line 20, in <module>
    from django.views import debug
  File "d:\projekte\multicopter\agrar_groundstation\venv\lib\site-packages\PyInstaller-3.5.dev0+g567c8560.mod-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "django\views\debug.py", line 20, in <module>
    DEBUG_ENGINE = Engine(debug=True)
  File "django\template\engine.py", line 52, in __init__
    self.template_builtins = self.get_template_builtins(self.builtins)
  File "django\template\engine.py", line 96, in get_template_builtins
    return [import_library(x) for x in builtins]
  File "django\template\library.py", line 325, in import_library
    "trying to load '%s': %s" % (name, e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.template.defaulttags': No module named defaulttags
`

**Comment by karthikdesai** [comment]
Hi i pulled in your PR and rebased it on top of pyinstaller/develop. I faced some issues, i have uploaded a couple of gists. 
https://gist.github.com/karthikdesai/5b66480dfb729a05d1f5a98499ddfc80

This log is when i tried to run the manage.exe runserver
https://gist.github.com/karthikdesai/f946ee49c17d42e0209e792dbf8340bf

Did you face this? I am on Django 1.11, Python 2.7

**Comment by karthikdesai** [comment]
@ciarancourtney Sorry was off for a couple of days. Will try it now
But what version of Django are you using? The same 1.11 or 2.1? And if 2.1, is it Python 3.5?

**Comment by ciarancourtney** [comment]
Using Django 1.11 on Python 3.6, don't think it will make much difference

**Comment by karthikdesai** [comment]
Ah okay! I did fix by adding a little more data to my .spec file. 
`'django.template.defaulttags', 'django.template.loader_tags', 'django.middleware.clickjacking', 'django.middleware.security', 'django.template.loaders.filesystem'`
Now i have got `TemplateDoesNotExist at /xxx/` error :( and i see that pyinstaller does not pack my app really well. It is missing all the static and template folders for my app. 
And when i try to load the admin page, i get, 
```
TemplateSyntaxError at /admin/login/
'i18n' is not a registered tag library. Must be one of:
```
After 'Must be one of:' it is blank. I think i am missing more hidden imports here.
The pyinstaller magic for you or did you have to change anything else?

**Comment by ciarancourtney** [comment]
Look at https://github.com/pyinstaller/pyinstaller/issues/1717#issuecomment-165537985 for i18n error

And you need to bundle your templates as data files. See helper function `collect_system_data_files`

**Comment by karthikdesai** [comment]
@ciarancourtney Okay it did start to work on python3.5. I still had the bug in python2.7 weirdly! 
Thank you for your help! :)

**Comment by NissanAloni** [comment]
I also have couple of fixes to django_import_finder.py to support django 2.0+
how can I contribute them?

**Comment by saneletm** [comment]
I am using django 1.11 with Python 2.7.16 and PyInstaller 3.2, getting this error when running my app:
 
[11/Jun/2019 15:50:25] INFO [webservice:188] service is starting from main...
[11/Jun/2019 15:50:25] INFO [webservice:72] Launching apache and solr monitor thread.
[11/Jun/2019 15:51:26] ERROR [webservice:85] Exception in Run: Traceback (most recent call last):
  File "site-packages/django/core/handlers/base.py", line 215, in _get_response
  File "site-packages/django/template/response.py", line 107, in render
  File "site-packages/django/template/response.py", line 82, in rendered_content
  File "site-packages/django/template/response.py", line 64, in resolve_template
  File "site-packages/django/template/loader.py", line 48, in select_template
  File "site-packages/django/template/backends/django.py", line 39, in get_template
  File "site-packages/django/template/engine.py", line 162, in get_template
  File "site-packages/django/template/engine.py", line 132, in find_template
  File "site-packages/django/utils/functional.py", line 35, in __get__
  File "site-packages/django/template/engine.py", line 106, in template_loaders
  File "site-packages/django/template/engine.py", line 111, in get_template_loaders
  File "site-packages/django/template/engine.py", line 124, in find_template_loader
  File "site-packages/django/utils/module_loading.py", line 20, in import_string
  File "importlib/__init__.py", line 37, in import_module
ImportError: No module named loaders.cached

Here are my templates settings: 


# ######## TEMPLATE CONFIGURATION
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [normpath(join(SITE_ROOT, 'templates'))],
        'OPTIONS': {
            "debug": False,
            "context_processors": (
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'options.context_processors.system_notifications_context',
                'versioning.context_processors.versioning',
                'xdv.context_processors.launch_client_url',
            )
        },

    }
]

I have tried to add the import to my PyInstaller hook file for hiddenimports, but doesn't seem to be helpful: 

hiddenimports = []
....
hiddenimports += collect_submodules('django.template.loaders.cached')
....

I think for some reason PyInstaller is having a hardtime locating django/temaplate/loaders/ module.
Any idea how I can fix this? I'll greatly appreciate your help. Thanks!

**Comment by Legorooj** [comment]
Stale

**Pull request closed without merging**
