### PR TITLE
Hook fixes

### PR DESCRIPTION
**Pull request by bjones1**
These commit fix two failing tests (libraries/test_pylint and libraries/test_pygments). Details:

* Add a logilab hook to add the hidden configparser import (dynamically imported by six)
* Add an extra import in test_pygments to make the test pass.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks :-) Is the hidden import for logilab valid for python 3, too?

**Comment by bjones1** [comment]
I've updated the commit message.

The hidden import for logilab in Python 3 is `configparser` (a difference in case). Should I add some sort of conditional for Python 3? What's the preferred way to handle this?

**Comment by bjones1** [comment]
Or, I know there's potential support for the six module in a pull request on the Python 3 branch -- this hook wouldn't be needed in that case. Again, how to handle this?

**Comment by htgoebel** [comment]
> Or, I know there's potential support for the six module in a pull request on the Python 3 branch -- the logilab-hook wouldn't be needed in that case. Again, how to handle this?

We should merge #1231 soon, because this is where the root cause is solved.

**Comment by bjones1** [comment]
I've removed `hook-logilab.py`, since #1231 should auto-detect this.

**Comment by htgoebel** [comment]
Thanks for this update, too. I'll merge it as soon as #1231 is done.

**Comment by bjones1** [comment]
Based on the discussion in #1231, `six` hidden imports are now included only for Python 2, but not for Python 3.

**Comment by htgoebel** [comment]
Merge into python3-branch

**Pull request merged**
