### PR TITLE
Add hook for auxiliary data required by lxml.isoschematron

### PR DESCRIPTION
**Pull request by giumas**
This should solve this issue: https://github.com/pyinstaller/pyinstaller/issues/1613

### CODE REVIEW

**Comment by htgoebel** [comment]
@giumas "should" solve the problem? I assume it does?!

**Comment by giumas** [comment]
@htgoebel : I have tested the hook only on Win7 (64bit) and Mac OS X (10.10.5) with vanilla CPython and under Anaconda distro. Thus, I have used "should" because I am not 100% sure that `lxml` has the Schematron schema files under the same sub-folder in all the possible distribution (e.g., Canopy). But I would assume so..

**Comment by htgoebel** [comment]
Well, CPython is the important one. Thanks!

BTW: Would you mind adding a test-case, too?

**Comment by giumas** [comment]
@htgoebel could you confirm the following steps to add a test?

* add the package (e.g., `lxml`) to https://github.com/pyinstaller/pyinstaller/blob/develop/tests/requirements.txt#L21 (if yes, why `wxPython` is not present in the list?)

then, there are 2 possible approaches:

* using `pyi_builder.test_script`, add a minimal script that uses the package here: https://github.com/pyinstaller/pyinstaller/tree/develop/tests/functional/scripts and the actual test here: https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py

or

* using `pyi_builder.test_source`, directly put the script content in a string

**Comment by htgoebel** [comment]
@giumas This is (almost) correct. Additionally you should add the related apt-package to `.travis.xml`.

I personally prefer using `pyi_builder.test_source` since it keeps the script in the test-code. But if the script is too long, it should be put into a separate file.

**Pull request merged**
