### PR TITLE
Removing non-basename binaries

### LINKED ISSUE #1770: OSX + libsodium : Security-Alert: try to store file outside of dist-directory.
Hello,

We are using pyinstaller 3.1 on travis OSX.
Our travis build using travis + libsodium installed thanks to homebrew is failing.

Here are the logs : 
```
52 INFO: PyInstaller: 3.1
52 INFO: Python: 3.5.0
57 INFO: Platform: Darwin-13.4.0-x86_64-i386-64bit
58 INFO: wrote /Users/travis/build/ucoin-io/sakia/main.spec
61 INFO: UPX is not available.
63 INFO: Extending PYTHONPATH with paths
['/Users/travis/build/ucoin-io/sakia/src', '/Users/travis/build/ucoin-io/sakia']
63 INFO: checking Analysis
64 INFO: Building Analysis because out00-Analysis.toc is non existent
64 INFO: Initializing module dependency graph...
65 INFO: Initializing module graph hooks...
66 INFO: Analyzing base_library.zip ...
3068 INFO: running Analysis out00-Analysis.toc
3083 INFO: Analyzing /Users/travis/build/ucoin-io/sakia/src/sakia/main.py
7199 INFO: Processing pre-find module path hook   distutils
9093 INFO: Looking for import hooks ...
9097 INFO: Processing hook   hook-PyQt5.QtCore.py
9189 INFO: Processing hook   hook-PyQt5.QtWidgets.py
9191 INFO: Processing hook   hook-lib2to3.py
9198 INFO: Processing hook   hook-distutils.py
9200 INFO: Processing hook   hook-requests.py
9204 INFO: Processing hook   hook-pydoc.py
9206 INFO: Processing hook   hook-PyQt5.py
9272 INFO: Processing hook   hook-encodings.py
9287 INFO: Processing hook   hook-PyQt5.Qt.py
9288 WARNING: Hidden import 'PyQt5.QtPrintSupport' not found (probably old hook)
9289 INFO: Processing hook   hook-xml.py
9335 INFO: Processing hook   hook-jsonschema.py
9337 INFO: Processing hook   hook-PyQt5.QtSvg.py
9339 INFO: Processing hook   hook-xml.etree.cElementTree.py
9340 INFO: Processing hook   hook-PyQt5.QtGui.py
9961 INFO: Looking for ctypes DLLs
9969 WARNING: ignoring /usr/local/lib/libsodium.so - ctypes imports only supported using bare filenames
9972 WARNING: library libsodium.so.{0} required via ctypes not found
9975 WARNING: library libsodium-{0} required via ctypes not found
9990 INFO: Analyzing run-time hooks ...
10008 INFO: Including run-time hook 'pyi_rth_qt5.py'
10013 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
10055 INFO: Looking for dynamic libraries
10301 INFO: Looking for eggs
10301 INFO: Using Python library /Users/travis/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/Python
10332 INFO: Warnings written to /Users/travis/build/ucoin-io/sakia/build/main/warnmain.txt
10397 INFO: checking PYZ
10397 INFO: Building PYZ because out00-PYZ.toc is non existent
10397 INFO: Building PYZ (ZlibArchive) /Users/travis/build/ucoin-io/sakia/build/main/out00-PYZ.pyz
11137 INFO: checking PKG
11137 INFO: Building PKG because out00-PKG.toc is non existent
11137 INFO: Building PKG (CArchive) out00-PKG.pkg
11169 INFO: Bootloader /Users/travis/.pyenv/versions/3.5.0/envs/sakia-env/lib/python3.5/site-packages/PyInstaller/bootloader/Darwin-64bit/run
11169 INFO: checking EXE
11172 INFO: Building EXE because out00-EXE.toc is non existent
11172 INFO: Building EXE from out00-EXE.toc
11190 INFO: Appending archive to EXE /Users/travis/build/ucoin-io/sakia/build/main/main
11237 INFO: Fixing EXE for code signing /Users/travis/build/ucoin-io/sakia/build/main/main
11246 INFO: checking COLLECT
11247 INFO: Building COLLECT because out00-COLLECT.toc is non existent
11247 INFO: Building COLLECT out00-COLLECT.toc
Security-Alert: try to store file outside of dist-directory. Aborting. '/usr/local/lib/libsodium.so'
```

Do you have any idea of what is happening ? Is there any workaround possible ?

### PR DESCRIPTION
**Pull request by RantyDave**
scan_code_for_ctypes includes a section for stripping 'None' and any non-basename binaries (i.e. /some/path/binary.so instead of just binary.so) from the list of binaries. While the test and warning are there, the instruction to actually remove it was not.

This fixes #1770

### CODE REVIEW

**Comment by htgoebel** [comment]
> Would it be possible to also print the filename and line where the ctypes import occurs …

@xoviat  Yes, this would be good.
- Printing the file-name should be easy (just pass it from `co.co_filename`).
- But I'd leave away the line-number as getting this is not so easy (dis.Instruction has only "starts_line - line started by this opcode (if any), otherwise None"). To give the usee a hint, we could use `co._co_firstlineno` and a message "in the codeblock starting at line xxx".

WDYT?
Do you want to take care of this on top of PR #2720 ?

**Comment by xoviat** [comment]
> Do you want to take care of this on top of PR #2720 ?

I'm very wary now about making PRs that are too large. I will address this in a separate PR after that one is merged.

**Comment by htgoebel** [comment]
That's absolutely okay for me.

**Comment by htgoebel** [comment]
@xoviat I lost the status for this and related #2768 (which you closed just a few days ago). Tests are passing (I'd say we don't need new ones on to of develop, since nothing in this area changes), so I' propose merging. But what's about your related changes in #2768?

**Comment by xoviat** [comment]
Go ahead and merge this and I'll submit another PR with the additional changes.

**Comment by htgoebel** [comment]
@xoviat I added your changes from #2517 already.

**Pull request closed without merging**
