### PR TITLE
Bugfix: for io error in issue 4024

### PR DESCRIPTION
**Pull request by strangemind**
see also issue #4209.

It appears that namespaces will not parsed correctly for filenames.   fnm in util/misc.py is populated with invalid filename for linux, "-" when NameSpaces are used like "google-cloud-firestore"   The packaging will have unhandled IOError on lines 156

### CODE REVIEW

**Comment by strangemind** [comment]
add hook-firestore.py add hook-grpc.py add hook-firebase_admin.py

The above hooks are need for 'google-cloud-firestore' platform. hook-grpc.py will also retrieve the needed certificate.

**Comment by strangemind** [comment]
The hook files were placed into pull request 4314.

**Comment by htgoebel** [comment]
> The hook files were placed into pull request 4314.

No, they are not! I'm not going to review this pull-request as long as it mixes unrelated stuff. Please clean up this mess!

**Comment by htgoebel** [comment]
@strangemind Please clean it up this pull-request. I'm not spending any time on getting firebase into PyInstaller, as Firebase is a google surveillance tool. If you want it in, clean up, so i just need to click "rebase and merge".

**Comment by Legorooj** [comment]
I'm closing this. It mixes unrelated work, and isn't up to scratch.

**Pull request closed without merging**
