### PR TITLE
Fix recursive import attempts for swig-like modules

### LINKED ISSUE #2911: importing tifffile causes RecursionError
> Pyinstaller 3.3 and 3.4currentdev
> Anaconda 4.3.27
> Python 3.6
> tifffile 0.12.1

**minimalTest.py**
`from tifffile import TiffFile`

**Make exe:**
`pyinstaller minimalTest.py`

**Workaround**
In *tifffile.py*:
Replace 

```
try:
    if __package__:
        from . import _tifffile  # noqa
    else:
        import _tifffile  # noqa
except ImportError:
    warnings.warn(
        "ImportError: No module named '_tifffile'. "
        "Loading of some compressed images will be very slow. "
        "Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/")
```
with
`from . import _tifffile`

**Error message:**
231 INFO: PyInstaller: 3.4.dev0+133d18156
231 INFO: Python: 3.6.1
232 INFO: Platform: Windows-10-10.0.10240-SP0
237 INFO: wrote D:\Programming\eclipse_workspace\scripts\AAA\test.spec
10504 INFO: UPX is not available.
10508 INFO: Extending PYTHONPATH with paths
['D:\\Programming\\eclipse_workspace\\scripts',
 'D:\\Programming\\eclipse_workspace\\scripts\\AAA']
10508 INFO: checking Analysis
10508 INFO: Building Analysis because out00-Analysis.toc is non existent
10508 INFO: Initializing module dependency graph...
10514 INFO: Initializing module graph hooks...
10521 INFO: Analyzing base_library.zip ...
21421 INFO: running Analysis out00-Analysis.toc
21426 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\ProgramData\Anaconda3\python.exe
22475 INFO: Caching module hooks...
22482 INFO: Analyzing D:\Programming\eclipse_workspace\scripts\AAA\test.py
27173 INFO: Processing pre-find module path hook   distutils
33490 INFO: Processing pre-find module path hook   site
33493 INFO: site: retargeting to fake-dir 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4.dev0+133d18156', 'console_scripts', 'pyinstaller')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 415, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1343, in run_script
    self._scan_code(m, co, co_ast)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2528, in _scan_code
    self._process_imports(module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2727, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2202, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1416, in import_hook
    source_package, target_module_partname, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1568, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1985, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2023, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2797, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2528, in _scan_code
    self._process_imports(module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2727, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2202, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1416, in import_hook
    source_package, target_module_partname, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1568, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1985, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _load_module
    self._scan_code(m, co, co_ast)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2528, in _scan_code
    self._process_imports(module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2727, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2312, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  [Previous line repeated 943 more times]
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2202, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1416, in import_hook
    source_package, target_module_partname, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1568, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1979, in _safe_import_module
    module_partname, search_dirs, parent_module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2853, in _find_module
    return self._find_module_path(fullname, name, path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 315, in _find_module_path
    fullname, module_name, search_dirs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2934, in _find_module_path
    module_name)
  File "<frozen importlib._bootstrap_external>", line 1223, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1268, in find_spec
  File "<frozen importlib._bootstrap_external>", line 60, in _path_join
RecursionError: maximum recursion depth exceeded

### LINKED ISSUE #3040: Infinite recursion in "import decimal"
With Ubuntu 14.04 Python 3.4 and latest pyinstaller (3.4.dev0+d258d2882), running pyinstaller on a file containing "import decimal" fails. The reason is that this system distribution of Python doesn't have a "_decimal" module for whatever reason. decimal tries to import _decimal and fails gracefully if it fails. Pyinstaller thinks _decimal is some kind of SWIG candidate, however, and so retries to import it over and over, eventually running off the end of the stack.

### PR DESCRIPTION
**Pull request by davidh-ssec**
Fix #2911
Fix #3040

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for your attempt to fix this. Please understand that I'm not going to add another change to modulegraph **without a proper test suite**. I've been working on the test-suite and a solution most of the day today and discovered some more bugs in the SWIG support. (I would have notified you, but understood your https://github.com/pyinstaller/pyinstaller/pull/2578#issuecomment-347528435 as if you are going to have a look at the *question*.)

Nevertheless your solution looks even simpler than mine and you spotted another case I missed (see your comment https://github.com/pyinstaller/pyinstaller/pull/3043/files#diff-4028735faddaf2453280ad6ffb470bc9R2322) and need to investigate. I'll also review your change.

In the meantime I'd appreciate if you'd answer the question of https://github.com/pyinstaller/pyinstaller/pull/2578#issuecomment-347524702, so I can build a proper test-suite. Thanks!

**Comment by xoviat** [comment]
Test failures due to #3045.

**Comment by htgoebel** [comment]
I merged your change into my patch-series,. replace my change, and it works well. All my new unit-tests test pass. see https://travis-ci.org/htgoebel/pyinstaller/builds/309559015 (ignoring the failures for Python 3.3, which are unrelated). Just now when writing this, it came to my mind that nevertheless I should combine your and my changes: your are faster, mine are stricter. I'm update my change.

**Comment by davidh-ssec** [comment]
Let me know if I can help @htgoebel

**Comment by htgoebel** [comment]
Thanks for this offer, but all should be done now. Just need to wait for the tests to finish (and maybe some polishing.)

**Comment by davidh-ssec** [comment]
Since you are working on testing, how do you feel about my last comment on this issue: https://github.com/pyinstaller/pyinstaller/pull/2838

**Comment by xoviat** [comment]
The Python 2.7 log appears to be very insightful.

**Comment by htgoebel** [comment]
> The Python 2.7 log appears to be very insightful.

@xoviat: I would appreciate if you would not beat around the bush! If you have discovered some issue, say it instead of wasting other peoples time by making them guess what you mean and clicking around. This is bad style, I really hate it.

**Comment by htgoebel** [comment]
Superseeded by #3061 .
@davidh-ssec Thanks for your contributions :-)

**Pull request closed without merging**
