### PR TITLE
Fix hookloader function bug when whitespaces in path

### LINKED ISSUE #6079: Latest pyinstaller (4.5.0) version breaks 3rd party lib hooks running
I am a contributor to pygame, and we maintain our own 3rd party pyinstaller hook in the repo. With the latest 4.5.0 version released a few hours ago, I noticed that pyinstaller generated exes that use pygame crash, complaining about missing DLLs that pygame needs, and with older pyinstaller versions (version 4.0 to 4.4), pyinstaller would load the pygame hook, which in turn, would load all the DLLs and other assets that pygame needs along with the pyinstaller generated exe. With 4.5, it does not run the hook at all, hence, missing data files

### Context information

* Output of `pyinstaller --version`: `4.5`
* Version of Python: `3.9.6`
* Platform: Windows
* How you installed Python: Windows 64-bit installer from python.org
* Did you also try this on another platform? Does it work there? Not tested on other OSes

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Steps to reproduce
- Install pygame with `py -m pip install pygame`
- Put the following minimal reproducer code in a `main.py` file, make an `assets` dir in the same folder, and put a sound file in the assets folder by the name of `blop.ogg` (I cannot attach the sound file because github does not allow me, but any `.ogg` music file can be used to reproduce this issue)
```py
"""
Simple pygame example that loads a sound from ogg file, playes it, and closes.

Demonstates a bug in pyinstaller 4.5
"""

import pygame
import os

pygame.init()

pygame.mixer.music.load(os.path.join("assets", "blop.ogg"))
pygame.mixer.music.play()

pygame.time.delay(500)
pygame.quit()
```
- Verify that simply running this program directly works, and a blop sound is heard
- Install pyinstaller `py -m pip install pyinstaller`
- Make dist with command `pyinstaller --add-data "assets;assets" main.py`
The first few lines of this output is 
```
D:\pyinst>pyinstaller --add-data "assets;assets" main.py
83 INFO: PyInstaller: 4.5
83 INFO: Python: 3.9.6
93 INFO: Platform: Windows-10-10.0.19043-SP0
97 INFO: wrote D:\pyinst\main.spec
101 INFO: UPX is not available.
108 INFO: Extending PYTHONPATH with paths
['D:\\pyinst', 'D:\\pyinst']
373 INFO: checking Analysis
373 INFO: Building Analysis because Analysis-00.toc is non existent
373 INFO: Initializing module dependency graph...
377 INFO: Caching module graph hooks...
382 INFO: Analyzing base_library.zip ...

[Build was successful, extra lines of output skipped]

D:\pyinst>cd dist\\main

D:\pyinst\dist\main>.\\main.exe
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 12, in <module>
pygame.error: Failed loading libvorbisfile-3.dll: The specified module could not be found.

[8060] Failed to execute script 'main' due to unhandled exception!

D:\pyinst\dist\main>
```
- See the crash is due to a missing DLL, which the pygame hook would have otherwise bundled

- In older pyinstaller versions (v4.4), the output is
```
D:\pyinst>pyinstaller --add-data "assets;assets" main.py
82 INFO: PyInstaller: 4.4
83 INFO: Python: 3.9.6
92 INFO: Platform: Windows-10-10.0.19043-SP0
93 INFO: wrote D:\pyinst\main.spec
95 INFO: UPX is not available.
98 INFO: Extending PYTHONPATH with paths
['D:\\pyinst', 'D:\\pyinst']
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
150 INFO: checking Analysis
165 INFO: Building because hookspath changed
165 INFO: Initializing module dependency graph...
169 INFO: Caching module graph hooks...
185 INFO: Analyzing base_library.zip ...

[Build was successful, extra lines of output skipped]

D:\pyinst>cd dist\\main

D:\pyinst\dist\main>.\\main.exe
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html

D:\pyinst\dist\main>
```

Notice how in the buildlog, the pygame welcome message appears, which means that the pygame hook was loaded correctly in this case.

### PR DESCRIPTION
**Pull request by ankith26**
Fixes #6079

### CODE REVIEW

**Comment by ankith26** [comment]
While this PR is a quick fix that works, the overall system of this hook loader thing is a bit hacky, as printing the path along with the other output means that user 3rd party hooks could also print stuff in the same format

**Review by bwoodsend — CHANGES_REQUESTED** [review]
Ughh well spotted. And yes, this will be redundant after #6052 but that probably won't get finished for a while so it's still worth having this.

Stick a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html) in then we're good to go.

**Comment by ankith26** [comment]
Okay I added it, I hope it's in the right format and stuff

**Comment by rokm** [comment]
If we're going to maintain separate 4.x branch, then this will definitely go into that one (while #6052 will go into `develop`/`5.x`)

**Review by rokm — APPROVED** [review]

**Comment by ankith26** [comment]
Hmmm looks like I messed up a bit as well, I rebased my two commits into one, cherry picked it onto v4, and force pushed

**Comment by ankith26** [comment]
Okay, looks like I got it right on `ankith26:v4` branch, do I open a new PR from that branch onto `pyinstaller:v4`?

**Comment by ankith26** [comment]
Oh.. And I guess I would need to open another PR to get this change onto `develop` branch as well, IG

**Comment by rxxg** [comment]
This fix seems to have been inadvertently removed from the v4 branch with the 17 August commit "formatter unleashed [skip ci]"

**Comment by rokm** [comment]
> This fix seems to have been inadvertently removed from the v4 branch with the 17 August commit "formatter unleashed [skip ci]"

Hmm, you're right. Thanks for pointing it out!

**Comment by rxxg** [comment]
Thanks yourself, I see you have pulled in the fix again.  Do you know if there will be a v4.8 (or 4.7.1) soon with this fix in?

**Pull request merged**
