### PR TITLE
Issue #1067 : Django - Override the find_command for commands management

### PR DESCRIPTION
**Pull request by garthylou**
Compatibility : all version of Django (tested with Django 1.7)

### CODE REVIEW

**Comment by htgoebel** [comment]
@garthylou Please add a comment as martin asked for so we can merge this pull-request. Thanks.

**Comment by htgoebel** [comment]
@garthylou pinging. Please help us solving this issue and add a short comment so others can understand your code.

**Comment by garthylou** [comment]
I'm sorry but I don't work on pyInstaller for a long time. I did not succeed to freeze my django app with it.
Therefore, in order to have the "find_command" correctly running on pyinstaller frozen apps, we have to rewrite the command. In the previous writing, all commands are hardly written but it can't work.
"Path" is the path where the command is asked, and all these commands are not working for any path.
I proposed to select the path to "django.core" to solve commands as found there : 
https://github.com/django/django/tree/master/django/core/management/commands

But in a generic way we have to write it differently. I use it as "monkey patch" with cx_freeze and it works with my application.
```python
def _find_commands(management_dir):
"""
Given a path to a management directory, returns a list of all the command
names that are available.
Returns an empty list if no commands are defined.
"""
return [modname for importer, modname, ispkg in pkgutil.iter_modules(
[os.path.join(management_dir, 'commands')]) if not ispkg]
```

**Comment by matysek** [comment]
I recently fixed django hooks in the python3 branch #1067 . Tested with django 1.8.

In the django rthook  pyi_rth_django.py it needs to override function 'get_commands()' and not 'find_commands'.

When we get Python 2 support into python3 branch then it should also work with Python 2.

**Pull request closed without merging**
