### PR TITLE
Fix pyi_locale_char2wchar() for debug Python

### PR DESCRIPTION
**Pull request by vstinner**
Fix pyi_locale_char2wchar(): Py_DecodeLocale() result must be freed
by PyMem_RawFree(), not directly by free().

When Python is built in debug mode, PyMem_RawFree() uses debug hooks
on top of malloc()/free(). Same error occurs when PYTHONMALLOC=debug
environment variable is used on a release build of Python.

Co-Authored-By: Pablo Galindo <Pablogsal@gmail.com>

### CODE REVIEW

**Comment by lkollar** [comment]
Travis failed on one of the builds with `Could not connect to apt.cache.travis-ci.com:80 (34.96.81.152), connection timed out`. @vstinner can you re-trigger the build?

The Windows builds are having issues too, I'm not sure what happened there.

**Comment by vstinner** [comment]
See https://github.com/pyinstaller/pyinstaller/pull/4440#issuecomment-534079744 : I'm not allowed to retrigger a single Travis CI job.

**Comment by vstinner** [comment]
> The Windows builds are having issues too, I'm not sure what happened there.

I picked one Windows job, it says: "FAILED tests/functional/test_basic.py::test_noarchive[onefile] - Failed: Runn..." but I don't see what failed. I don't know how to debug such issue. I'm not a PyInstaller developer :-)

**Comment by lkollar** [comment]
Restarted the Travis build. I'm not sure what to do with the Windows build though as I have no experience with PyInstaller on Windows.

**Comment by bjones1** [comment]
This looks fine. Would you add the fine `news\4441.bugfix.rst` and briefly discuss your changes? Link to `Py_DecodeLocale` and note that its return value must be freed by (another link) `PyMem_RawFree`.

**Comment by vstinner** [comment]
> This looks fine. Would you add the fine news\4441.bugfix.rst and briefly discuss your changes? Link to Py_DecodeLocale and note that its return value must be freed by (another link) PyMem_RawFree.

Done. Would you mind to review it? I'm not sure of the expected format.

**Comment by bjones1** [comment]
This looks great. Thanks! Let me wait for CI to ensure all is well.

**Comment by bjones1** [comment]
Hmm. This seems to break something on Windows, though I can't see why.

**Comment by vstinner** [comment]
> Hmm. This seems to break something on Windows, though I can't see why.

Maybe it's unrelated to my change?

**Comment by bjones1** [comment]
I've rebased your change on my branch and will re-run the tests there -- see https://ci.appveyor.com/project/bjones1/pyinstaller/builds/27886512.

**Comment by bjones1** [comment]
I still get the same failures. I don't know why, but these changes break the bootloader.

**Comment by vstinner** [comment]
I'm not really available to update this PR. So if anyone is interested to update it: please go ahead and reuse my code!

**Comment by htgoebel** [comment]
I have a fix on my private python-3.8 branch. Closing this pull-request.

**Comment by alexchandel** [comment]
@htgoebel Could you publish your fix?

**Pull request closed without merging**
