### PR TITLE
Hook for Cryptodome module

### PR DESCRIPTION
**Pull request by stephenrauch**
Fix for #2125

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request, which I'd like to merge. Can you please change the message of the first commit into "Add Hook for cryptodome" and add "Fixed #2125" in the third line (which will auto-close that issue). Thanks.

**Comment by htgoebel** [comment]
The commit messages adjusted is in #2453

**Comment by ulope** [comment]
This is named a bit misleading. It's a hook for `Cryptodomex` not `Cryptodome` which imports as `Crypto`. Is there any support for `Cryptodome` (without the x)?

**Comment by htgoebel** [comment]
Thansk for pointing this out. It's for the Cryptodomex *package*, but the Cryptodome module. Confusing.

**Pull request closed without merging**
