### PR TITLE
Address compatibility issues with build related to keyring library and Queue import

### PR DESCRIPTION
**Pull request by jstewmon**
Picked from #2069

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request. I'm curious what is the concrete issue this is solving, since PyInstaller is not using 2to3 (AFAIK) and if this would have been an issue, this would have shown up earlier.

Further: Why are you pinning keyring to this very version?

**Comment by jstewmon** [comment]
I have answered that question multiple times already, and I provided a detailed explanation in the commit message.

**Comment by htgoebel** [comment]
Regarding the keyring, I'm sorry. I search for this explanation in the code.

Regarding the Queue: Can I please point me to where you answered this? I can only find my https://github.com/pyinstaller/pyinstaller/pull/2069#pullrequestreview-15086888.

**Comment by jstewmon** [comment]
PyInstaller does not use 2to3 - I only used '2to3' as shorthand for python2 vs python3. Importing from `queue` will work if the `future` package has been installed because `future` will create a `queue` package in the `site-packages` folder.  `test_loader.py` doesn't appear to be intentionally dependent on `tests/requirements-libraries.txt`, so it was coincidental that `import queue` ever worked.

**Comment by htgoebel** [comment]
Thanks you very much for the explanation. This cleared my confusion.

**Pull request closed without merging**
