### PR TITLE
Fix syntax error (re #1148)

### PR DESCRIPTION
**Pull request by jarondl**
The fix for #1148 introduced a syntax error, this solves it

### CODE REVIEW

**Comment by matysek** [comment]
Thanks.

**Comment by htgoebel** [comment]
Really embarrassing for me :-(

**Comment by jarondl** [comment]
@htgoebel it happens to the best of us, don't worry :-)
Is there a specific reason for not having a `.travis.yml` in the python3 branch? If it is a matter of writing one done, I can help

**Comment by matysek** [comment]
@jarondl python3 branch was created before .travis.yml. It would help.

**Pull request merged**
