### PR TITLE
patch to fix bugs on windows platform.

### PR DESCRIPTION
**Pull request by Readon**
when using pygi provided by [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/), it will report gir-1.0 directory could not be found.
This will correct the path on windows and avoid unnecessary check for gir files.

expected to fix the issue [#1966](https://github.com/pyinstaller/pyinstaller/issues/1966)

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this fix.

**Comment by virtuald** [comment]
d9f9ba78094fcbd4489e5edfd2f9c90b5eac2821 breaks packaging Gtk apps on OSX.

**Comment by Readon** [comment]
I do not have a OSX environment.
The patch is only to see if the typelib is exists.
Is that because of the path differences between platform?

**Comment by virtuald** [comment]
Yeah, if you look below the code you patched, you can see that there's an OSX-specific check where it recompiles the typelibs. I think I have a fix, I'll push a PR for you to test on Windows in a few minutes.

**Comment by virtuald** [comment]
@Readon please try #2596 on Windows

**Pull request merged**
