### PR TITLE
hooks: Add soundcard hook.

### PR DESCRIPTION
**Pull request by Bob-Thomas**
Add hook for the soundcard library to also add the .h files required for running the library.

https://github.com/bastibe/SoundCard/issues/77
https://pypi.org/project/SoundCard/

### CODE REVIEW

**Comment by Legorooj** [comment]
@bastibe @Bob-Thomas would you be interested in integrating the hook into soundcard itself? Support for that goes officially live next version - the feature itself is "stable" in the development branch. (See https://pyinstaller-sample-hook.readthedocs.io for details)

Or this will need to be targeted at our new hooks repo; the inbuilt library of hooks is getting too large to manage easily, so we're migrating it to a standalone package that works alongside PyInstaller.

**Comment by Bob-Thomas** [comment]
Oh that sounds pretty cool. It's up for the creator of the library to
decide on integrating it. But I'll be willing to make a pr for either
solutions

**Comment by bastibe** [comment]
In general, I would gladly merge a pull request implementing this hook.

However, I am still a bit confused about how this works: 

If I understand this correctly, the hook is an additional couple of source files we would need to ship with SoundCard, right? The sample project is so littered with makefiles and project files and documentation files that it wasn't quite sure which of these are actually needed for the hook, and which we can leave out. I would want the hook to be clearly visible as such, and small.

Also, do we need to declare pyinstaller as a dependency of SoundCard? I would not like that.

**Comment by Legorooj** [comment]
@bastibe no, pyinstaller wouldn't be a dependency - for users. Maybe for testing though, if you wanted to test the hook. You just ship the hook with the package. 

Someone who has implemented it: https://github.com/almarklein/wgpu-py/issues/25

Yes, I need to update the docs.

If you don't like the solution, we'll put it in the community hooks package.

**Comment by bastibe** [comment]
OK, I'm fine with that. @Bob-Thomas, I'd be grateful for a pull request!

**Comment by Bob-Thomas** [comment]
Ah so you want the hook implemented in soundcard?

**Comment by bastibe** [comment]
I think that's overall the better solution, yes.

**Comment by Legorooj** [comment]
Seeing as you're putting the hook in soundcard, I'll close this. Feel free to tag me on the other PR.

**Pull request closed without merging**
