### PR TITLE
Doc update of two options in makespec.py and doc formatting issue fix

### PR DESCRIPTION
**Pull request by linusg-github**
I improved the descriptions of the --add-data and --add-binary options
and removed the backticks which will hopefully fix
https://github.com/pyinstaller/pyinstaller/issues/2079

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for spotting this. But please reduce the change to the *minimum* and change the quote-characters only where necessary.

**Comment by linusg-github** [comment]
Ok, sorry, I'll remember in future. What is the recommended style for PyInstaller, using single or double quotes? In the file, there's a nice mix of both :P
Is it possible to force sphinx to rebuild the docs? I don't know anything about how and when the docs on readthedocs are build...

**Comment by htgoebel** [comment]
> What is the recommended style for PyInstaller, using single or double quotes? In the file, there's a nice mix of both :P

We do not have a recommendation on this. Your idea of using the same quotes everywhere is okay in principle, but in the long run it's more important to have as few and as small changes as possible.

> Is it possible to force sphinx to rebuild the docs?

This should be as easy as
```
cd doc
make html
xdg-open _build/html/usage.html
```
File `./man/_pyinstaller-options.tmp` may be of interest, too :-)

Please note: these `.tmp` files are regenerated unconditionally *every time* you build docs. This is done ine `conf.py` (Hack!). So you may need to tweak conf.py to be able to play with the `.tmp`-files more easily.

**Comment by linusg-github** [comment]
Thanks for your response. The way you're described it I am able to build the doc files *locally* (thanks for that, it helps me to check, if the issue still exists), but I meant how the online documentation for readthedoc is build an if someone can force a rebuild.
The issue still exists in the local documentation, but I'll search for a way to fix it and do a new commit then.

**Comment by htgoebel** [comment]
The "latest" online documentation for readthedoc is build automatically whenever a commit is pushed.

Rebuild could be initiated manually by the PyInstaller admins at rtfd (currentyl me and matysek).

**Comment by linusg-github** [comment]
I figured it out!
Sphinx was not able to handle the options `metavar` correctly if there were characters like `: ; , #` and some more in in the `metavar` string **except** if the string starts with `<` and ends with `>`. But while `<SRC:DEST>` looks a bit confusing, I decided to use a syntax similar to the `-i` (icon) option metavar: `<SRC;DEST or SRC;DEST>`.
This is maybe also a bit more clear than doing `'SRC{}DEST'.format(os.pathsep)`, which will cause a platform dependent output.

**Comment by htgoebel** [comment]
Thanks for this update.

Please `git rebase -i HEAD^^` and then "fixup" the commits, so there is only one. Otherwise we will still have all these changes of quotes. Useless changes like this make it *really* hard to dig into the 10 years of history if necessary.

And please restore the back-ticks (if possible), since these add semantics :-)

**Comment by linusg-github** [comment]
I'm not sure how to remove the first two commits now... I used `git rebase -i HEAD^^`, and I got this:
```
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```
After doing a commit and retrying it, I edited the file and got this:

```
error: could not apply ed47af1... Cleanup of quotes and backticks

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply ed47af1d85f0c6aa9b1a66ac897733d1e052ec5a... Cleanup of quotes and backticks
```
Maybe I'm commiting changes sometimes too fast :) Can you give me some advice how to do it?

And should I use single or double backtics? It will make the difference that text in single backticks will be formatted italic and text in double ones as code.

**Comment by linusg-github** [comment]
I tried a lot of ``git rebase ...` variations, it always set the state of my local repo back, but not even a forced push will change the online commits, sorry for that :/
If it's ok, the just merge all the commits, otherwise I have to get some help. Would it help to close the pr and open a new one? I am a real newby on git/github, I just started learning it for PyInstaller.

**Comment by linusg-github** [comment]
Huh, I finally figured it out. I removed th ~70 commits and made one new. There is just one typo - ixup instead of fixup - but that should be ok (I hope so).

**Comment by htgoebel** [comment]
@linusg-github Thanks for taking the time learning git :-)

**Comment by linusg-github** [comment]
@htgoebel:
> Thanks for taking the time learning git :-)

No problem! I'm using git for my own projects now myself, and I left this inintuitive GUI program for git I had, the CLI is more transparent for beginners.
I hope I can do some useful contributions to this project in the future, now being familar with all that git stuff.

**Pull request merged**
