### PR TITLE
Enable appveyor "tests" tab.

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by codewarrior0** [comment]
Doesn't work.

Did you check https://ci.appveyor.com/project/xoviat/pyinstaller before sending this PR?

**Comment by xoviat** [comment]
@codewarrior0 The PyInstaller appveyor is currently broken.

**Comment by xoviat** [comment]
@codewarrior0 Look you can see the test results [here][1].

[1]: https://ci.appveyor.com/project/xoviat/pyinstaller/build/1.0.186/job/vaq9yjikm6yxv2k9/tests

**Comment by xoviat** [comment]
@matysek Would you mind fixing the PyInstaller appveyor?

**Comment by htgoebel** [comment]
Thanks, this is a nice add-on :-)

**Comment by htgoebel** [comment]
Can we have this for Travis-CI, too?

**Pull request closed without merging**
