### PR TITLE
Hooks: Add hook-pandas.py to fix issue #2978.

### PR DESCRIPTION
**Pull request by lneuhaus**
pandas>=0.21 has a hidden import of "pandas._libs.tslibs.timedeltas.so".

### CODE REVIEW

**Comment by lneuhaus** [comment]
I do not really understand why tests are failing. Can someone confirm that this is the fault of my fix?

**Comment by htgoebel** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

I restarted the job. We'll see.

**Comment by lneuhaus** [comment]
while it looks here that the test failed, it actually passed:
- it got cancelled in the "Lint" part, I have no idea why?
- the "Python: nightly" build failed, but apparently this is no indication of failure, see for example here: https://travis-ci.org/pyinstaller/pyinstaller/builds/311109538

So: does anything speak against merging this PR?

**Comment by luwii** [comment]
Thanks for posting, I spent ages and it started driving me mad before I stumbled on this. Worked like charm to fix pyinstaller _program.py_  Does not seem to be working with pyinstaller -F _program.py_ but I can live with it. Thanks!

**Comment by maichm** [comment]
when run `pyinstaller -F xxx.py` in windows10 , I get error "AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'", and solve it by degrade pandas version to 0.20.0.

**Comment by jni** [comment]
Has anyone come up with a workaround that works with `-F` *and* a recent pandas?

**Pull request merged**
