### PR TITLE
Backports from v6.x to v5.x

### PR DESCRIPTION
**Pull request by bwoodsend**
- rthooks: win32com: fully isolate the genpy cache
- rthooks: secure temp directories used by matplotlib and win32com rthooks
- archive: splash: normalize path component separator in splash requirements
- bootstrap: add a work-around for sys._stdlib_dir not being set
- hookutils: gi: fix error handling in compile_glib_schema_files
- Fix msys2 dll paths in GdkPixbuf loaders.cache gen (#7842)
- Fix pkgutil.iter_modules for symbolically linked packages
- Fix readthedocs building theme selection. [skip ci]

Running through CI/CD to flush out the Python 3.7 incompatibilities.

### CODE REVIEW

**Review by rokm — APPROVED** [review]

**Comment by rokm** [comment]
Hmm, looks like python changed from 3.11.4 to 3.11.5 in alpine container between yesterday's and today's run... and looks like we have some breakage there (probably in general).

**Comment by bwoodsend** [comment]
Looks like [this change](https://github.com/python/cpython/commit/34ef75d3ef559288900fad008f05b29155eb8b59) added an `is_fork_ctx` attribute but forgot to add handling for it in the pickle methods (`__getstate__()` and `__setstate__()`) so after that class has been pickled and unpickled, the `is_fork_ctx` gets lost?

**Comment by rokm** [comment]
> Looks like [this change](https://github.com/python/cpython/commit/34ef75d3ef559288900fad008f05b29155eb8b59) added an `is_fork_ctx` attribute but forgot to add handling for it in the pickle methods (`__getstate__()` and `__setstate__()`) so after that class has been pickled and unpickled, the `is_fork_ctx` gets lost?

Indeed. Running `pyinstaller/tests/functional/scripts/pyi_multiprocessing_nested_process.py` unfrozen with `spawn` or `forkserver` hits the same error.

I guess there is not much point in us trying to work around it, because python will need to fix this either way. Shall we xfail/skip the nested multiprocessing test for 3.11.5?

**Comment by bwoodsend** [comment]
> I guess there is not much point in us trying to work around it, because python will need to fix this either way. Shall we xfail/skip the nested multiprocessing test for 3.11.5?

I guess we should `xfail` it in `develop`. I'm not sure there's much point in cherry picking it into `v5`. I'm hoping that we'll never need this branch again.

**Comment by rokm** [comment]
> > I guess there is not much point in us trying to work around it, because python will need to fix this either way. Shall we xfail/skip the nested multiprocessing test for 3.11.5?
> 
> I guess we should `xfail` it in `develop`. I'm not sure there's much point in cherry picking it into `v5`. I'm hoping that we'll never need this branch again.

I agree.

**Comment by bwoodsend** [comment]
I've ran the alpine tests locally and there aren't any more surprises hiding behind that *abort after 3 failures* threshold.

**Comment by bwoodsend** [comment]
Are you submitting a fix for CPython/multiprocessing or shall I grab it?

**Comment by rokm** [comment]
> Are you submitting a fix for CPython/multiprocessing or shall I grab it?

Go ahead if you want.

**Pull request merged**
