### PR TITLE
ci: Fix CI with pip>=19 ensuring local PyInstaller package can be imported

### PR DESCRIPTION
**Pull request by jcfr**
Co-authored-by: Francois Budin <francois.budin@kitware.com>

### CODE REVIEW

**Comment by jcfr** [comment]
See #2730 and https://github.com/pypa/pip/issues/6163

**Comment by htgoebel** [comment]
Thanks for this pull-request. I'm curious why this is a fix rather than a work-around. What is the "official" reason for the breakage?

**Comment by jcfr** [comment]
Thanks for reviewing.

Would it help if I change the commit message to

```
ci: Fix CI with pip>=19 ensuring local PyInstaller package can be imported

This workaround addresses issue discussed in pypa/pip#6163 and prevent developer from explicitly
passing the option `--no-use-pep517` to pip.
```

.. and add a comment like this one above the added line:

```
# Explicitly update the python path avoid developer from explicitly passing option --no-use-pep517
# to pip executable. For more, details see https://github.com/pypa/pip/issues/6163
sys.path.insert(0, os.path.dirname(__file__))
```

Let me know what you think,

**Comment by ulope** [comment]
IMO this is a workaround at best. Importing one's own package from `setup.py` is a bit of a code smell in my book.

**Comment by htgoebel** [comment]
After reading the discussion and esp. https://github.com/pypa/pip/issues/6163#issuecomment-457931454 I'm favor or *not* adding this work-around. Many projects are affected by this pip-issue, thus pip (or setuptools) shall be fixed instead of every project implementing a work-around.

**Comment by fbudin69500** [comment]
@jcfr suggested, it would great to at least temporarily integrate a patch in `pyinstaller` to workaround the issue introduced in pip 19. It would allow contributors to this project to verify that their PRs pass the tests on the CI. Updating the CI scripts with `--no-use-pep517` seems like a reasonable approach to me. Just my 2cts.

**Pull request closed without merging**
