### PR TITLE
Add test for lxml.isoschematron hook

### PR DESCRIPTION
**Pull request by giumas**
Test for: https://github.com/pyinstaller/pyinstaller/pull/1614

### CODE REVIEW

**Comment by giumas** [comment]
@htgoebel : on Windows, ``lxml`` has not currently wheels for Python 3.4. And it needs ``libxml-dev`` and ``libxslt-dev`` to be built. What is your suggestion?

**Comment by htgoebel** [comment]
@codewarrior0 Can you please have a look at this,. too. Compiling lxml fails on windows.

**Comment by htgoebel** [comment]
giumas: I do not really understand what the problem is. No need to care about missing wheels if we are able to compile ourself. But maybe this answers your questions:
- Add libxml-dev and libxslt-dev to the `addons: apt: packages:` section like sou did for python-lxml. Mind adding a comment :-)
- For Windows we may be out of luck.

**Comment by htgoebel** [comment]
@giumas: For Windows we my be out of luck compiling it, So test skip. We have to take this.

For Linux building lxml fails, too. Please add libxml-dev and libxslt-dev to the `addons: apt: packages:` section like you did for python-lxml. Mind adding a comment :-)

**Comment by codewarrior0** [comment]
`lxml` fails to build on Windows because it can't find the `libxml` and `libxslt` libraries and headers. [The `lxml` install instructions](http://lxml.de/build.html#static-linking-on-windows) note that you can use this command on an unpacked `lxml` sdist to automatically download these dependencies and link to them:

`python setup.py bdist_wininst --static-deps`

The `--static-deps` option seems to also apply to the `bdist` and `bdist_wheel` setup commands.

When I tried to use this command, I encountered some errors due to the automatically downloaded files being 32-bit builds, while the Python I used was a 64-bit build. I tried again using a 32-bit Python and had complete success with using `bdist_wheel --static-deps` to create an `lxml` wheel.

Downloading the static deps takes several minutes so it would be preferable to have prebuilt wheels ready somewhere for appveyor to use. Sadly, I can't build a wheel for Python 3.3 or 3.4 since I don't have the required version of VS 2010, but I know AppVeyor does have it installed.

**Comment by htgoebel** [comment]
We have `pip-accel` in place to avoid rebuilding - and thus downloading the static deps. Maybe it's enough to add
```
pip-accel install --install-options=--static-deps lxml   # syntax out of my memory
```
in front of the other `pip-accel`-call.

**Comment by giumas** [comment]
> Downloading the static deps takes several minutes so it would be preferable to have prebuilt wheels ready somewhere for appveyor to use. Sadly, I can't build a wheel for Python 3.3 or 3.4 since I don't have the required version of VS 2010, but I know AppVeyor does have it installed.

@codewarrior0 Can we use the [Gohlke's wheels](http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml)? 
There is an option for [storing the binary cache on S3](https://pypi.python.org/pypi/pip-accel#storing-the-binary-cache-on-amazon-s3) that could be worthwhile to explore.. since I believe that the issue is common to other hook tests (e.g., wxPython).

**Comment by htgoebel** [comment]
> There is an option for storing the binary cache on S3 that could

appveyor already support caching. No need to use another feature.

Don't feed the Datenkraken!

**Comment by codewarrior0** [comment]
> @codewarrior0 Can we use the Gohlke's wheels? 

I'm sure the wheels are fine, but Gohlke scrambles his links so we would still need our own mirror of the wheels.

**Comment by giumas** [comment]
@htgoebel For Travis-CI, I have added ``lixml2-dev`` and ``libxslt1-dev`` to ``apt-get``.
@codewarrior0 For AppVeyor, I have put the Gohlke's wheels on Anaconda.org and added a ``pip-accel install -i`` from that repository.

The build was successful on Travis CI, but the building process never started on AppVeyor.

**Comment by giumas** [comment]
It looks like the AppVeyor builbs are failing for other reasons.. but the `xml.isoschematron` test was successful.

**Comment by htgoebel** [comment]
@giumas I just wanted to merge this, but there is something mixed up: This pull-request contains 148 commits changing 123 files. Would you please update the pull-request with clean commits containing only your changes?! Thanks! (`git cherry-pick` and `git push -f` are your friends.)

**Comment by giumas** [comment]
@htgoebel I have not idea of what is going on with this PR.. On my local repository the branch is clean (and I have removed the GitHub fork). I believe that it is quicker if I close it, and create a new PR.

**Pull request closed without merging**
