### PR TITLE
Added a hook for sound_lib.

### PR DESCRIPTION
**Pull request by chrisnorman7**

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this hook which I'd like to accept. Please
- add a copyright header to the file like the other hooks have
- use `collect_dynamic_libs( 'module-name' )`, see https://pyinstaller.readthedocs.io/en/stable/hooks.html#useful-items-in-pyinstaller-utils-hooks

Thanks.

**Comment by htgoebel** [comment]
@chrisnorman7 Are you going to make the requested changes anytime soon?

**Comment by chrisnorman7** [comment]
Actually I thought I'd already done it... Did the changes not go 
through? They're in my personal git repo I'm sure...

**Comment by htgoebel** [comment]
@chrisnorman7 Are you going to update the pull-request anytime soon?

**Comment by htgoebel** [comment]
@chrisnorman7 Pinging. Are you going to update the pull-request anytime soon? Otherwise I will not merge this it but close it - which would be a pity.

**Comment by htgoebel** [comment]
Thanks.

**Pull request merged**
