### PR TITLE
UPX is under active development again (https://github.com/upx/upx)

### PR DESCRIPTION
**Pull request by maphew**

### CODE REVIEW

**Comment by xoviat** [comment]
btw, any time you update the documentation only, prefix the commit message with [skip-ci].

**Comment by maphew** [comment]
ok, thanks for the tip re: skip-ci.

**Comment by htgoebel** [comment]
@maphew Why did you close this pull-request?

BTW: `[skip-ci]` is recognized anywhere in the commit message. Putting it in the first line is not necessary (and IMHO no a good idea since is clutters the message with processing instructions.)

**Comment by maphew** [comment]
I  meant to close the commenting, not the PR. Sorry. I'm not that conversant on the whole Github workflow thing!

**Pull request merged**
