### PR TITLE
Fix typo in manual

### PR DESCRIPTION
**Pull request by rleonid**
s/hooks.utils/utils.hooks/

### CODE REVIEW

**Comment by rleonid** [comment]
I'm not certain what the extra changes that github is making to those files. I just wanted to correct the documentation, so if it is doing something funky with the encoding, please just incorporate the changes and I'll close this PR.

**Comment by htgoebel** [comment]
@rleonid Are you going to update the pull-request?

**Comment by rleonid** [comment]
I did, I push-forced a new commit.

**Comment by htgoebel** [comment]
@rleonid IC. Sorry, I totally missed it.

**Pull request merged**
