### PR TITLE
Drop Python 3.3 support

### PR DESCRIPTION
**Pull request by xoviat**
Python 3.3 has reach EOL.

### CODE REVIEW

**Comment by xoviat** [comment]
@htgoebel Can you go ahead and squash-merge this?

**Comment by xoviat** [comment]
@htgoebel I would recommend merging this ASAP to resolve test failures.

**Comment by htgoebel** [comment]
> Python 3.3 has reach EOL.

What is the urgent need to drop this? (I did not have time yet to check the test failures.)

**Comment by htgoebel** [comment]
Also when dropping *all* code specific to Py 3.3 should be removed.

**Comment by xoviat** [comment]
Dependencies are dropping 3.3. Dropping all code is going to need a longer PR, and it's important to fix the failing tests.

**Comment by htgoebel** [comment]
But why they are now failing? They did not fail yesterday. Why can't they be fixed?

(Yes, I know, 3.3. is EOL. But we need a PyInstaller bug-fix release and can't drop Py3.3. support for this. Thus even removing Py 3.3 from the tests can not be done quickly.)

**Comment by xoviat** [comment]
See https://github.com/pytest-dev/py/issues/175.

**Comment by htgoebel** [comment]
So the simpler solution would be to pin pytest – as long as we no not require a new version.

**Comment by xoviat** [comment]
Yes but that kills #3049. If it was worth killing, then I would say it's fine, but I don't see the point of working on an EOL Python. Even security issues are not fixed.

**Comment by hugovk** [comment]
I'd just drop 3.3, hardly anyone uses it.

Here's the pip installs for pyinstaller from PyPI for the last month (via `pypinfo --percent --pip pyinstaller pyversion`), showing a very small fraction for 3.3:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   48.4% |         26,288 |
| 3.6            |   24.9% |         13,563 |
| 3.5            |   18.1% |          9,857 |
| 3.4            |    7.1% |          3,833 |
| 2.6            |    0.9% |            496 |
| 3.7            |    0.5% |            268 |
| 3.3            |    0.1% |             50 |
| 3.2            |    0.0% |              5 |
| None           |    0.0% |              2 |

**Comment by htgoebel** [comment]
When dropping Py 3.3, this should be done completely, this pull-request did only remove it from the tests.

**Pull request closed without merging**
