### PR TITLE
make PyInstaller under Python 3 work for a normal PyQt5 app

### PR DESCRIPTION
**Pull request by tallforasmurf**
These two changes make PyInstaller under Python 3 work for a normal PyQt5 app. I have used it to build a moderately complex app (github.com/tallforasmurf/PPQT2) on Mac OS X 10.10 ("yosemite"). I built both one-folder and one-file and it ran.

This does not cover PyQt5 apps that use QtWebEngine, I will put up an issue on that shortly.

### CODE REVIEW

**Comment by htgoebel** [comment]
I recommend using `rebase -i  5eede^` (hope this is the correct syntax to get the commit prior to 5eede) and "edit" 5eede – this will of course change the commit-ids, but this does not matter. (You may want to use `gitk --all` for checking.) When you are happy with the results, push your `python3` branch using `--force`. This will update both your branch head and should also update this pull-request.

**Comment by htgoebel** [comment]
@tallforasmurf I tried merging this into the current pthon3-branch (which is now up to date with develop), but I'm getting conflicts I can not resolve due to my lack of QT-knowledge. I'd ask you to do the following:
```
# clone the current repository
cd /tmp
git clone https://github.com/pyinstaller/pyinstaller.git
cd pyinstaller
git checkout python3
# fetch your changes and put them on a new branch
git fetch https://github.com/tallforasmurf/pyinstaller.git python3
git checkout -b tallforasmurf-python3 f3bfaf501a5b
# rebase your changes
git rebase python3
```
You will get conflicts in two of the steps and a quite good explanation on how to process. Which in short says for our case:
* Edit the conflicting file to the expected result
* `git add` the respective file
* `git rebase --continue`.

Thanks.

(An alternative approach would be to use `git rebase -i python3`. Then you could remove the lines containing d101751 and 5eede2e as the former reverts the later and thus they are useless.)

**Comment by htgoebel** [comment]
@tallforasmurf Addendum: Then push this branch to you github repo and update the pull-request. If you do not have further changes on your python3-branch, you could even do:
```
git branch --delete python3
git checkout -b python3 tallforasmurf-python3
```
and then push this python3-branch to you repo using `git push --force`.

**Comment by tallforasmurf** [comment]
It all worked to a point. I had to --skip a couple of the hook changes. When the rebase completed, I recreated them as new commits (b61fc19, b28b2ff). Then performed 

    git branch --delete python3
    git checkout -b python3 tallforasmurf-python3

however the push did not work, presumably because of the --delete?

    git push --force
    fatal: The current branch python3 has no upstream branch.
    To push the current branch and set the remote as upstream, use
    git push --set-upstream origin python3

So I tried that, but it is trying to push to the real master, pyinstaller/pyinstaller for which I don't have privileges:

    git push --set-upstream origin python3
    remote: Permission to pyinstaller/pyinstaller.git denied to tallforasmurf.
    fatal: unable to access 'https://github.com/pyinstaller/pyinstaller.git/': The requested URL returned error: 403

    git remote -v
    origin	https://github.com/pyinstaller/pyinstaller.git (fetch)
    origin	https://github.com/pyinstaller/pyinstaller.git (push)
    upstream	https://github.com/tallforasmurf/pyinstaller.git (fetch)
    upstream	https://github.com/tallforasmurf/pyinstaller.git (push)

Not sure what to do next - probably something simple?

**Comment by htgoebel** [comment]
Huh, I'm curious about the need to `--skip` commits. I did the same when testing my explanation and all worked find - beside the two commits which have conflicts. You can find the console-output of my operations in http://tny.cz/0d56e078.

Regarding the push: You need to push to your repo: `git push --force upstream python3` (I don't know why this is called `upstream` in you case, though.)

**Comment by tallforasmurf** [comment]
My rebase stopped on only two commits, the two where I had deleted several hidden imports from the PyQt5.Qt and PyQt5.QtWebKitWidgets hooks (they were importing a lot of unnecessary modules like QtQml, QtQuick, QtSql). I could not see, comparing the A and B patches, what the problem was. But they were simple and not essential, so I just used --skip, and then re-performed those changes after the rebase completed.

The rebase did not stop for me on the d101751/5eede2e commits you mention.

Anyway, done now and as you said, force upstream to python3 worked. So https://github.com/tallforasmurf/pyinstaller/tree/python3 should be ok now.

**Comment by tallforasmurf** [comment]
Do I need to do anything further? Would it be simpler if I closed this pull request and opened a new one?

**Comment by htgoebel** [comment]
@tallforasmurf Thanks a lot. I merged this manually because I wanted to remove the two commits abolishing each other (I didn't want to ask you doing this, as you seam to struggle with git anyway).

> Would it be simpler if I closed this pull request and opened a new one?

There is no need to close a pull-request in this case. Even more: closing would be counter-productive as it cuts the chain. The "correct" way would have been to update this pull-request within github, see http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Pull request closed without merging**
