### PR TITLE
Analysis: add hook to allow users to filter the assembled dependencies

### PR DESCRIPTION
**Pull request by virtuald**
- This is particularly useful for applications that have dependencies (such as gstreamer)
  that include plugins that their application may or may not need

The problem I'm trying to solve is that the gstreamer hook brings in a lot of plugins that my application doesn't need. I'd like to be able to filter them out. This solution allows me to add a function to the spec file that can take the list of binaries and remove the stuff I don't want to include.

I'm open to other suggestions, but this seemed to be most expedient to get the job done.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request. I like the idea!

The only thing I'm not sure about is: Should this really be a hook, getting the "whole" `Analysis` object as parameter, or should this better "just" be a "dependencies_filter", e.g. like 
```
self.pure, self.binaries = dependencies_filter(self.pure, self.binaries)
```
The later would not require to expose the (still undocumented) attributes of the `Analysis` object and simplify the documentation. What do you think?

BTW: This needs to be documented, too :-)

**Comment by virtuald** [comment]
That would be ok too.

Here's how I currently use it: https://github.com/exaile/exaile/blob/master/tools/installer/exaile.spec#L60

**Comment by htgoebel** [comment]
This brings to my mind whether we want one argument/function which needs to loop over the items itself or if we want two arguments (one for datas, one for binaries) which would be called for each element (like `_exclude` in your example)

**Comment by htgoebel** [comment]
Would be okay, too. I'd use a list of globs instead of regex, though:
```
>>> fnmatch.fnmatch('/usr/lib/foo.so', '*/foo*')
True
```
So match paths is possible, too, without much effort, and one does not need to escape dots which are common in filenames.

**Comment by virtuald** [comment]
I like that, changed.

**Comment by bwoodsend** [comment]
This looks nice. Can we pick this up again? As long as it rebased on top of the develop branch this gets my approval.

**Comment by Legorooj** [comment]
Let's pick this up in a new PR/issue if we're going do look into this again.

**Pull request closed without merging**
