### PR TITLE
Add openpyxl hook

### PR DESCRIPTION
**Pull request by stephenrauch**
Hook to address #1890

### CODE REVIEW

**Comment by beargan** [comment]
@stephenrauch thanks.
your method is feasible.

**Comment by bjones1** [comment]
@stephenrauch, thanks! Would you mind either providing a test case or some code that fails in a comment below?

**Comment by stephenrauch** [comment]
```python
import openpyxl
print openpyxl.__version__
```

**Comment by stephenrauch** [comment]
@bjones1 

OK, if you insist, here is the version with a test case...  :smile:

Sorry it did not occur to me the first time around.  My only excuse is that it was late that night...

**Comment by stephenrauch** [comment]
Lovely,

I add a test case and appveyor blows up before it even gets to the test cases because pip blows a gasket?  Ouch.

**Comment by bjones1** [comment]
Aargh, I have no idea why pip died. Thanks for adding the test case -- I'm busy with other projects and just haven't had the time...

**Comment by htgoebel** [comment]
Thanks for this hook. Please add an URL for `openyxl` since it is not commonly known and which version you tested this hook with. See `hook-distorm3.py` as an example. Thanks.

**Comment by stephenrauch** [comment]
I really have no idea what version I used, I simply did a ```pip install openpyxl``` in response to the bug being filed to see if I could help out.  The problem presented itself in a quick test, and so I coded and submitted the hook.

**Comment by htgoebel** [comment]
`pip list | grep openpyxl` is your friend :-)

This version info showed to up to be useful. This is why I'm insisting on it.

**Comment by stephenrauch** [comment]
Oh, if it were only that easy...

```
C:\>pip list | grep openpyxl
'grep' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by htgoebel** [comment]
@stephenrauch IC, you are using an outdated operating system ;-)

**Comment by bjones1** [comment]
Does `pip show openpyxl` work?

**Comment by stephenrauch** [comment]
@bjones1 

Thanks,

I will be able to get the version with no issues, I was am just super busy lately, and was mostly just teasing @htgoebel.   I think he got it when he threw that dig in at my workstation OS of choice.  It is all good and I should get a chance to make the requested change before too much longer.

That however still doesn't help with the errant appveyor...

**Comment by bjones1** [comment]
@stephenrauch, any help is welcome in Appveyor fixes -- see #2100...

**Comment by htgoebel** [comment]
> I [...] was mostly just teasing @htgoebel. I think he got it when he threw that dig in at my workstation OS of choice.

Yes, I got it ;-)

Thanks for updating the pull-request.

And thanks for competently answering quite some of the issue ticket. It's very helpful for us!

**Pull request merged**
