### PR TITLE
Add the support and the tests of Champlain and Clutter

### PR DESCRIPTION
**Pull request by benoit9126**
Hi,

I used PyInstaller to freeze an application which needed [`Clutter`](https://wiki.gnome.org/Projects/Clutter), `GtkClutter`, [`Champlain`](https://wiki.gnome.org/Projects/libchamplain/) and [`GtkChamplain`](https://developer.gnome.org/libchamplain-gtk/). I have written some basic hooks for that and I propose to add them in PyInstaller.

I also modified the test suite of `gi` hooks to be able to handle the weird version number of `Champlain` and `GtkChamplain` (0.12)

### CODE REVIEW

**Comment by benoit9126** [comment]
A build on travis errored but it is not related to my modifications (https://travis-ci.org/pyinstaller/pyinstaller/jobs/362088314). Could you please restart the job? I can not do it myself...

**Comment by htgoebel** [comment]
Thanks for the pull-request. Can you please split the changes in `tests/functional/test_hooks/test_gi.py` unrelated to the new hook into a commit of it's own. Thanks.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

Please also take the change and rebase your branch on the current `develop` head. Thanks.

**Comment by benoit9126** [comment]
It should do the job.

**Comment by htgoebel** [comment]
Thanks for the update. The second commit does more than the commit message says. It massively reworks the test-case *and* adds test. Thus this should become two commits.

Please follow the [detailed commit guideline](https://pyinstaller.readthedocs.io/en/v3.3.1/development/index.html#guidelines-for-commits) and the [guide for good commit messages](https://pyinstaller.readthedocs.io/en/v3.3.1/development/commit-messages.html). Mind to prefix with the subsystem ("Hooks" resp. "Tests"). Se the later links for why we are so picky about this.

**Comment by benoit9126** [comment]
@htgoebel : You are right. Here is the modification.

PS: Sorry, I was in trouble with Git and some useless continuous integration tests may have been triggered...

**Comment by benoit9126** [comment]
It seems that the `-n` option of `py.test` is not known:
```console
$ py.test -n 3 --maxfail 3 tests/unit tests/functional --ignore=tests/functional/test_libraries.py --ignore=tests/functional/test_hooks
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -n tests/unit tests/functional
  inifile: /home/travis/build/pyinstaller/pyinstaller/setup.cfg
  rootdir: /home/travis/build/pyinstaller/pyinstaller
The command "py.test -n 3 --maxfail 3 tests/unit tests/functional --ignore=tests/functional/test_libraries.py --ignore=tests/functional/test_hooks
" exited with 2.
```

**Comment by htgoebel** [comment]
Thanks you for this pull-request, which is a nice one :-) I'm sorry to not have merged it earlier.

**Pull request merged**
