### PR TITLE
adding hooks for google cloud & google api modules

### PR DESCRIPTION
**Pull request by bayesfactor**
In my build, I found a runtime error unless I included these hook files before build.

### CODE REVIEW

**Comment by htgoebel** [comment]
This hook is for "google.api", but includes meta-data from "google-api-core". Thus should'nt this be a hook for e.g. "google.api.core"?

**Comment by htgoebel** [comment]
@bayesfactor Would you please answer the questions so we can proceed with this pull-request? Thanks.

**Comment by bayesfactor** [comment]
I admit I'm no expert, so I tested both ways.  
with google-api-core, the project builds and runs.
with google.api.core, I get an error on build:
pkg_resources.DistributionNotFound: The 'google.api.core' distribution was not found and is required by the application.

**Comment by htgoebel** [comment]
@bayesfactor Sorry for not commint back on this for so long. I'd like to merge it. For this please
* submit a [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change.

**Comment by bayesfactor** [comment]
I created the entry in the changelog: news/3251.bugfix.rst

I hope this is correct

**Comment by htgoebel** [comment]
@bayesfactor There is still only one file in the pull-request - no changelog entry. Also this needs to go into the "hooks" section, as the manual states.

**Comment by htgoebel** [comment]
@bayesfactor Pinging. The changelog entry is still missing. Please add one, so I can merge. Thanks.

**Pull request merged**
