### PR TITLE
tests: requirements: update execnet

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by htgoebel** [comment]
Please provide some information why thsi restriction is now removed. Esp.: Is this fixed now? Why is /github.com/pytest-dev/execnet used new while the original version is from bitbucket.org/hpk42/execnet?
This will be helpful to understand this change in some years time. Thanks.

**Comment by xoviat** [comment]
> Please provide some information why thsi restriction is now removed. Esp.: Is this fixed now? Why is /github.com/pytest-dev/execnet used new while the original version is from bitbucket.org/hpk42/execnet?
This will be helpful to understand this change in some years time. Thanks.

Execnet development has moved to github. Using the github URL will allow improvements that are not in your personal branch.

**Comment by htgoebel** [comment]
The reason for not using the maim repo or an official release is https://bitbucket.org/hpk42/execnet/pull-requests/21 (see 75bd45ded1856b830e917022425771e0129b53ef), which has been declined. Now you are chageing this to the main repo at github. Thus the commit-message should state why this can now be done savely.

I assume you did recherche this prior to submitting the pull-request. So please but this information into the commit message, so the knowledge will be preserved and can be comprehend when time passes by.

**Comment by xoviat** [comment]
Previously execnet was not under active development. Now it is. pytest-dev/execnet@66a6e22e759500d451ce6aaf156d2bf3a242f903 resolved that issue.

**Comment by xoviat** [comment]
@htgoebel Maybe the commit message clarifies things now?

**Comment by htgoebel** [comment]
@xoviat Yes, thank you very much!

Please apologize for being to picky. But experience shows that it's important to understand the reason for some changes even some years later. Just a few days ago I had some changes in the bootloaders wscript which's root-course and effects are not documented. So it took several hours to find out what are the implications if changing this.

**Pull request merged**
