### PR TITLE
Bootloader: Handle getURL Apple Event (#4397)

### LINKED ISSUE #4397: Custom protocol handler doesn't work on Mac
## Expected behavior: 
I want to be able to launch my PyInstaller application using registered custom protocol handler e.g.: `myapp://id:12345`. 
Opening such link in the browser should trigger system dialog asking to open the application and pass the url (`myapp://id:12345`) as launch argument.

## Actual behavior:

It works properly on Windows by adding registry keys and on Linux with special `myapp.desktop` file, it even works on Mac by adding required attributes to the `info_plist`:

```
app = BUNDLE(exe,
             name='MyApp.app',
             info_plist={
                'CFBundleURLTypes': [{
                    'CFBundleURLName': 'MyApp',
                    'CFBundleTypeRole': 'Viewer',
                    'CFBundleURLSchemes': ['myapp']
                }]
             })
```

and it launches the application properly, but on MacOS it doesn't pass any arguments to the program.

I did some investigation around this problem and I found that PyInstaller bootloader is not handling `kAEGetURL` AppleEvent. It should handle it in the similar way as it does with `kAEOpenDocuments` event.

## Minimal example:

https://gist.github.com/pastDexter/8d2a46d5730e9fde22b207ce6b37f7ff

- Generate `.app` package using provided `.spec` file
- Open `myapp://some-args-123` url in the browser

_(I tested it on all recent releases and `develop` branch on MacOS Mojave)_

### PR DESCRIPTION
**Pull request by pastDexter**
Fixes #4397

Add support for appending URL to program arguments when applications is launched from custom protocol handler on MacOS.

It implements `kAEGetURL` in the same way as the already implemented `kAEOpenDocuments` handler.

## Minimal example:

https://gist.github.com/pastDexter/8d2a46d5730e9fde22b207ce6b37f7ff

- Generate `.app` package using provided `.spec` file
- Open `myapp://some-args-123` url in the browser
- System notification with `["myapp://some-args-123"]` should appear

### CODE REVIEW

**Comment by htgoebel** [comment]
Thank you for this pull-request. For this pull-request to be merged, please 
* submit a [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change.
* Remove the bootloader binaries. We do not accept binaries compiled be others than the core developers.
* Squash the commits into a single one.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

**Comment by htgoebel** [comment]
Is there some way we could tests this in the test-suite?

**Comment by pastDexter** [comment]
I've added the changelog entry, removed compiled binaries and squashed all the commits. 👍 

Now I'll try to find a way to test that functionality in the test-suite

**Comment by pastDexter** [comment]
@htgoebel I managed to add test for this functionality 👍 
I noticed that there is something wrong with TravisCI builds - it fails every time, but the errors are not related to my changes. It looks like it's the same for most of the open PRs. Do you have any idea how to get the fixed?

**Comment by nealdav** [comment]
Very interested in the progress of this PR as I need to pass args to a url handler on mac OS. Were these changes implemented in another branch?

**Comment by pastDexter** [comment]
> Very interested in the progress of this PR as I need to pass args to a url handler on mac OS. Were these changes implemented in another branch?

@nealdav I'd love to merge this. I'll try to find time this week to fight with the failing CI, and finally make it ready to merge :)

**Comment by nealdav** [comment]
@pastDexter thank you for working on this!

**Comment by pastDexter** [comment]
@htgoebel the PR is ready to merge now. Please take a look when you'll have a moment 🙂

**Comment by htgoebel** [comment]
Trigger rerunning the tests (only OSX ones are of interest).

**Comment by htgoebel** [comment]
@pastDexter Thanks for this pull-request I now found time to review and merge it.

**Pull request merged**
