### PR TITLE
PyWin32 Anaconda Support

### PR DESCRIPTION
**Pull request by leycec**
This pull request substantially improves PyInstaller integration with [Anaconda](http://continuum.io/downloads) under Windows, fixing #1247. The solution is fairly simple. We define two new utility functions:

* `import_pywin32_module()`, importing the passed PyWin32 module (e.g, `pywintypes`, `pythoncom`) in an Anaconda-aware manner. Attempting to import this module directly results in an exception resembling `"ImportError: No system module 'pywintypes' (pywintypes34.dll)"`. Why? Because Anaconda installs the referenced DLL into the `site-packages\pywin32_system32\` and `site-packages\win32\` directories, which PyWin32 does *not* search when attempting to find the DLL. (**Insanity.** We know.) This function instructs PyWin32 to search the first directory with a dollop of [vile black magic](b11d2024f).
* `get_pywin32_module_file_attribute()`, getting the `__file__` attribute of the passed PyWin32 module in the same way.

PyInstaller startup now detects PyWin32 in an Anaconda-aware manner by calling `import_pywin32_module()`. Likewise, the `pywintypes` and `pythoncom` hooks now register PyWin32 DLLs as hidden imports in an Anaconda-aware manner by calling `get_pywin32_module_file_attribute()`.

Thus fell another fey dragon.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this patch. I think it is helpful. What about moving `get_pywin32_module_file_attribute` into `PyInstaller/utils/win32/winutils`, though. Its more win32-related than hooks-related and may be useful elsewhere, too.

**Comment by leycec** [comment]
@htgoebel Per your [code review](https://github.com/leycec/pyinstaller/commit/667bd3ccf4f229a368e0d1f18ba977f7d0dd7aa5#commitcomment-11003904), the general-purpose `import_pywin32_module()` function has been extracted out to the `PyInstaller.utils.win32.winutils` module. Thanks for the helpful critique! It hurts, but it's a good hurt. :grimacing:

**Comment by leycec** [comment]
> What about moving get_pywin32_module_file_attribute into PyInstaller/utils/win32/winutils, though. Its more win32-related than hooks-related and may be useful elsewhere, too.

**Woops.** I hit your [other commentary](https://github.com/leycec/pyinstaller/commit/667bd3ccf4f229a368e0d1f18ba977f7d0dd7aa5#commitcomment-11003904) first, and ended up rebasing before reading the above. In short, I've:

* Moved the `import_pywin32_module()` function to the `PyInstaller.utils.win32.winutils` module. As you say, this is a *much* better fit for this general-purpose helper.
* Left the `get_pywin32_module_file_attribute()` function in the `PyInstaller.utils.hooks.hookutils` module. That function should *only* be called by import hooks; likewise, that function internally calls the `hookutils.exec_statement()` function. So, this seems fairly reasonable.

But I'd be happy to move the remaining `get_pywin32_module_file_attribute()` function to the `PyInstaller.utils.win32.winutils` module and rebase again. It *is* a Windows-specific utility function, so it makes equal sense for that function to reside in a Windows-specific module as it does a hook-specific module. Just let me know!

**Comment by htgoebel** [comment]
Thanks for this pull-request.

**Pull request merged**
