### PR TITLE
support for bokeh visualization library

### PR DESCRIPTION
**Pull request by axil**
Hook for packaging bokeh (https://bokeh.pydata.org/en/latest/) applications.

### CODE REVIEW

**Comment by axil** [comment]
Minimal working example: https://github.com/axil/frozen_sliders

**Comment by htgoebel** [comment]
Thanks you very much :-)

**Comment by bryevdv** [comment]
FYI I think this needs to be updated to include `bokeh.themes` since Bokeh currently loads JSON theme files from there on init.  I have very limited experience with pyinstaller but it appears on master that the missing theme files are causing issue:
```
  File "/Users/bryanv/anaconda/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "bokeh/themes/__init__.py", line 19, in <module>
  File "bokeh/themes/theme.py", line 139, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bryanv/work/bokeh/examples/plotting/file/dist/iris/bokeh/themes/light_minimal.json'
[52053] Failed to execute script iris
```

**Comment by bjones1** [comment]
Thanks for the report. Would you provide a short script that reproduces this? Is it as simple as `import bokeh`?

For the hook, what's best -- load the themes for now, then remove this load when you release 1.0?

**Comment by bryevdv** [comment]
Here is a simple example:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/color_scatter.py

I don't have an opinion or recommendation for how pyinstaller should proceed. The next release should be out next week, in case that is useful information.

**Comment by bjones1** [comment]
Choosing the path of laziness, I'll simply wait for your next release instead of updating the hook.

**Pull request merged**
