### PR TITLE
Issue 2701: remove files before write

### LINKED ISSUE #2701: Remove destination for COLLECT and EXE prior to copying it
```
rm -rf build/ dist/
echo "a=1" > test.py
pyinstaller test.py --clean
pyinstaller test.py --clean --onefile
```
crashes:
```
10934 INFO: Building EXE because out00-EXE.toc is non existent
10934 INFO: Building EXE from out00-EXE.toc
Traceback (most recent call last):
…
  File "…/PyInstaller/building/api.py", line 563, in assemble
    self._copyfile(exe, self.name)
  File "…/PyInstaller/building/api.py", line 603, in _copyfile
    with open(outfile, 'wb') as outfh:
IOError: [Errno 21] Is a directory: '/tmp/dist/test'
```

The reason is: In `--ondir` mode, '/tmp/dist/test' was created as a directory, but EXE does not remove the destination prior to writing there.

**Security**: The destination should also be removed prior to writing to avoid sym-link attacks. This might not be a real threat, but let's be on the save side :-)

Todo:
- At the top of [`COLLECT.assemble()`](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/api.py#L663) remove destination if "… exists" (not only if "… is dir").
- Use same code for removing the destination near the top of [`EXE.assemble()`](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/api.py#L486).

### PR DESCRIPTION
**Pull request by xoviat**
Closes #2701.

### CODE REVIEW

**Comment by htgoebel** [comment]
Just to give you a number: This patch has 595 lines. But when stripping down the patch to the relevant parts, its only about 90 lines (given that I kept all relevant changes).

**Comment by xoviat** [comment]
> Just to give you a number: This patch has 595 lines. But when stripping down the patch to the relevant parts, its only about 90 lines (given that I kept all relevant changes).

Can I just submit a PR that reformats the entire project?

**Comment by codewarrior0** [comment]
That seems a bit excessive. Can't you just turn off those autoformatting features in your editor?

**Comment by htgoebel** [comment]
> Can I just submit a PR that reformats the entire project?

Counterquestion: Why should the code be reformatted? I can not see any urgent need for. Also see #2727.

**Comment by xoviat** [comment]
Closing as this does not comply with #2727.

**Comment by htgoebel** [comment]
@xoviat #2727 is not yet accepted and your pull-request could be made to comply by simply leaving off the first commit.

**Comment by htgoebel** [comment]
… as done in 834b274eb980681836a0b7f4b2f2d30d0b893ccb

**Pull request closed without merging**
