### PR TITLE
Fix #3309: Changing from -F to -D on consecutive runs causes crash 

### LINKED ISSUE #3309: Changing from -F to -D on consecutive runs causes crash
MacOS (have not tried Win, Linux; may well fail there too), PyInstaller 3.3.1. Demonstrate as follows.

~~~~
$  pyinstaller --version
3.3.1
$ cat > hello.py
import sys
print( 'hello',sys.argv[1] ) ^D
$ python hello.py world
hello world
$  pyinstaller --clean -y -F hello.py
   ...normal INFO messages...
$ dist/hello world
hello world
$  pyinstaller --clean -y -D hello.py
  ... normal INFO messages down to...
3576 INFO: Building COLLECT because out00-COLLECT.toc is non existent
Traceback (most recent call last):
  File "/Developer/VENV-3.6/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 33, in <module>
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/api.py", line 661, in __init__
    self.__postinit__()
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/api.py", line 674, in assemble
    _make_clean_directory(self.name)
  File "/Developer/VENV-3.6/lib/python3.6/site-packages/PyInstaller/building/utils.py", line 388, in _make_clean_directory
    os.makedirs(path)
  File "/usr/local/Cellar/python3/3.6.2/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Developer/VENV-3.6/dist/hello'
~~~~

### PR DESCRIPTION
**Pull request by melvyn2**
Fix #3309

### CODE REVIEW

**Comment by htgoebel** [comment]
Looks like very simple solution :-) Nevertheless, please update the commit message to comply to https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html#commit-messages.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

**Comment by htgoebel** [comment]
Pinging. You also need to submit a [changelog entry](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change. (This is a new requirement since last Septembe to speed up releasing.)

**Comment by melvyn2** [comment]
@htgoebel I've changed the commit messages and added a newsfragment.

**Comment by htgoebel** [comment]
Thanks for the quick update. 

The changelog-entry has several deficits:
- There is no section "building", it shouf be "bugfix"
- Putting the issue-number here is useless and will lead to duplicating the number.
- Wording does not follow the guideline.

Please go a head an read the instructions about the changelog entry again. If these instructions a to be improved, please let me know. It's still a quite new text.

Also the commit message has room for improvement. Would the current message tell you what this change does?

**Comment by melvyn2** [comment]
Thanks for the feedback @htgoebel , I've tried to fix what you told me. 👍

**Comment by htgoebel** [comment]
Thanks for this pull-request. I just merged it.

**Pull request merged**
