### PR TITLE
Changes to work with python 2.7 built with gcc on AIX platform

### PR DESCRIPTION
**Pull request by goodtiding5**
Added HAVE_MKDTEMP flag for AIX with GCC compiler

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for the updated pull-request.

But I'd ask you to amend the commit-message of the last commit. See https://github.com/pyinstaller/pyinstaller/wiki/Development-Commit-Messages for how we like them commit messages :-) Sory for being a nitpicker her, but we need to spot the content of the commit quickly when looking at it in five years time.

**Comment by goodtiding5** [comment]
Not a problem!  I have amended the commit message.

**Comment by htgoebel** [comment]
Tahnsk. This is a great commit message :-)

**Comment by codewarrior0** [comment]
> Should I close this one and create another pull request?

There's no need. The pull request is linked to the branch, so it is always updated when you push to the same branch. You can even amend commits and force push if you like.

**Pull request merged**
