### PR TITLE
fix GST_PLUGIN_PATH separator being os dependant.

### PR DESCRIPTION
**Pull request by matham**
This fixes the issue mentioned at https://github.com/pyinstaller/pyinstaller/pull/1963#issuecomment-251520593. It also fixes: https://github.com/kivy/kivy/issues/4652.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request, which I'd like to merge. For this can you please prefix the commit message with: "Run-time hooks:". Thanks.

**Comment by MerlijnWajer** [comment]
Shouldn't this be closed at this point?

**Comment by MerlijnWajer** [comment]
Nevermind, this one is not merged yet. The purple 'merged' button confused me.

**Comment by matham** [comment]
Closing for https://github.com/pyinstaller/pyinstaller/pull/2417, which changed the commit message.

**Pull request closed without merging**
