### PR TITLE
Fix for issue #3655

### PR DESCRIPTION
**Pull request by banzr**
qmldir is not properly set. Confirmed to work on Windows after fix.

### CODE REVIEW

**Comment by tpeeters** [comment]
This does not solve problems finding the QML directory for me. I currently work around it by hardcoding it inside the PySide2 hook. When qmake is used, it is using the system qmake, which points to the system Qt, which is not the Qt that is installed with PySide2 (I used pip install PySide2 to install it in a miniconda3 environment).

**Comment by tpeeters** [comment]
Note that exec_command() also is not available on Linux (Ubuntu 16.04 for me, using Python 3.6 in a minconda environment).

  File "/home/tim/miniconda3/envs/app/lib/python3.6/site-packages/PyInstaller/hooks/hook-PySide2.QtQuick.py", line 13, in <module>
    from PyInstaller.utils.hooks import get_qmake_path, exec_command
ImportError: cannot import name 'exec_command'

**Comment by htgoebel** [comment]
The correct fix would be to learn why `get_qmake_path()` returns a qmake which is later not found by windows - and fix that.

**Comment by tpeeters** [comment]
Would that be the correct fix? PySide2 includes the QML dir, but does not come with qmake. So we can find the QML dir inside the sitepackages instead. See for example how I changed it to make it work for me:

https://github.com/pyinstaller/pyinstaller/compare/develop...tpeeters:develop#diff-b541cd0f939e36452212b6cff5ba6606R20

I didn't make a PR yet because maybe it needs some more discussion first, and I also need some other changes before it will actually work with a PySide2 app.

**Comment by bjones1** [comment]
IMHO, the whole PySide2 approach is old and broken. It should instead rely on queries to `QLibraryInfo`. For someone with reasonable Python, PyInstaller, and PySide2 experience, this should be fairly easy. Just add `pyqt5_library_info = Qt5LibraryInfo('PySide2')` after [this line](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/qt.py#L81) and then use that info for the rest of the file and in PySide2 hooks.

**Pull request closed without merging**
