### PR TITLE
Fix: Join pathnames in an OS-independent manner.

### PR DESCRIPTION
**Pull request by bjones1**
This makes more unit tests pass in Windows.

### CODE REVIEW

**Comment by bjones1** [comment]
@htgoebel, I noticed that you added `test_extension` to `tests\unit\test_modulegraph.py` in 56279f3bd63fd5884437f5fe39c22399ff55778e. I'm getting a failure under your favorite OS (Windows) that I'm not sure how to fix. Any ideas? I'm seeing:

```
_______________________________ test_extension ________________________________

tmpdir = local('c:\\users\\bjones\\appdata\\local\\temp\\pytest-of-bjones\\pytest-5\\test_extension0
')

    def test_extension(tmpdir):
        node = _import_and_get_node(tmpdir, 'array', path=sys.path)
>       assert isinstance(node, modulegraph.Extension)
E       assert isinstance(BuiltinModule('array',), <class 'PyInstaller.lib.modulegraph.modulegraph.Extension'>)
E        +  where <class 'PyInstaller.lib.modulegraph.modulegraph.Extension'> = modulegraph.Extension

tests\unit\test_modulegraph.py:66: AssertionError
```

**Comment by htgoebel** [comment]
Maybe `array` is a build-in module in your Python installation?! If so, we should use a different one, e.g. `binascii`, `mmap`, `math`, `time` or `_random`, `_cytpes`. `_csv`, `_json`.

**Comment by htgoebel** [comment]
I'll wait for this pull-request to change until you fixed test_extension. Otherwise this will be closed and we may get it out of sign.

**Comment by bjones1** [comment]
@htgoebel, thanks for the input. Apparently so -- I'm using the PythonXY distribution. Perhaps this is standard for Windows, since Appveyor fails with the same error. There are only a handful of `.pyd` files in `C:\Python27\DLLs` on my PC; there are no in `C:\Python27\Lib`. I picked one (`_ctypes`) to get the test to pass.

```
C:\Python27\DLLs>dir *.pyd
 Volume in drive C is OS
 Volume Serial Number is 6229-AC4F

 Directory of C:\Python27\DLLs

05/15/2013  09:43 PM            68,608 bz2.pyd
05/15/2013  09:43 PM           127,488 pyexpat.pyd
05/15/2013  09:43 PM            10,240 select.pyd
05/15/2013  09:43 PM           686,080 unicodedata.pyd
05/15/2013  09:43 PM             9,216 winsound.pyd
05/15/2013  09:45 PM         1,012,224 _bsddb.pyd
05/15/2013  09:43 PM            87,552 _ctypes.pyd
05/15/2013  09:43 PM            15,872 _ctypes_test.pyd
05/15/2013  09:43 PM           128,512 _elementtree.pyd
05/15/2013  09:44 PM           358,400 _hashlib.pyd
05/15/2013  09:43 PM            48,128 _msi.pyd
05/15/2013  09:43 PM            27,136 _multiprocessing.pyd
05/15/2013  09:43 PM            44,544 _socket.pyd
05/15/2013  09:43 PM            47,616 _sqlite3.pyd
05/15/2013  09:45 PM           899,072 _ssl.pyd
05/15/2013  09:43 PM            32,768 _testcapi.pyd
05/15/2013  09:43 PM            33,792 _tkinter.pyd
              17 File(s)      3,637,248 bytes
               0 Dir(s)  116,288,438,272 bytes free
```

**Comment by bjones1** [comment]
This should now be ready to merge.

**Comment by htgoebel** [comment]
Thanks.

**Pull request merged**
