### PR TITLE
doc: Insert hyperlinks to issues referenced by towncrier.

### PR DESCRIPTION
**Pull request by bjones1**
This produces a more useful `changes.rst` IMHO.

### CODE REVIEW

**Comment by htgoebel** [comment]
I agree, but it renders the text-only version unreadable.

We have a sphinx-role `issue` defined for the manual, which does basically the in the background. Sou your change could be to create
```
:issue:`1234`
```

Please check the result using
```
pip install --user towncrier docutils
towncrier --version=12.3.4.dummy
rst2html doc/CHANGES.rst > /tmp/CHANGES.html
xdg-open /tmp/CHANGES.html  # opens file in your web-browser
```

For now please ignore the warnings not introduced by your change.

**Comment by htgoebel** [comment]
Well, we could use towncriers ``issue_format`` configuration variable by adjusting the filter. 

When working this out, I discovered some issues related to the README and the built documentation. I'll look at this later today or tomorrow and will update your pull-reqeuest (keeping your honors, of course :-)

**Comment by htgoebel** [comment]
Thank you for this suggestion and making me implement it :-)

**Comment by bjones1** [comment]
Thanks for the improvements -- very nice! I really like the towncrier approach.

**Pull request merged**
