### PR TITLE
Fix for Menu not displayed with app bundle on OSX

### PR DESCRIPTION
**Pull request by gholzmann**
As discussed in issue #1078 , this pull requests fixes the problem with the missing menu at startup on OSX. I tested the code OSX Mountain Lion, Maverick and Yosemite.
For discussion please see issue #1078 !

More information about this issue is here:
http://dvitonis.net/blog/2015/01/07/menu-bar-not-visible-when-building-pyqt-app-bundle-pyinstaller-mac-osx-mavericks-yosemite/

### CODE REVIEW

**Comment by tallforasmurf** [comment]
looking forward to this merged to python3?

**Comment by matysek** [comment]
@tallforasmurf Just working on it.

**Comment by tallforasmurf** [comment]
I was just thinking yesterday how grateful I am for your and Hartmut's work the last few months. You've really turned PyInstaller around just at the time I needed it. Thanks very much!

**Comment by htgoebel** [comment]
@tallforasmurf Thanks :-) I can give this back: If you (and some others) would not give *so much* input and puill-requests, I would have a hard time to keep up to date. So thanks again.

**Pull request merged**
