### PR TITLE
building: collect built-in extensions into lib-dynload sub-directory

### LINKED ISSUE #3993: Symbol not found PyCryptoDome Hash
App won't run when packaged from commandline.
I'm stumped by this. Below is the MWE (virtualenv, python script, spec).
This test was ran using the dev version of PyInstaller

```
$ pipenv run python crypto_test.py
9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca72323c3d99ba5c11d7c7acc6e14b8c5da0c4663475c2e5c3adef46f73bcdec043

$ ./dist/crypto_test/crypto_test
Traceback (most recent call last):
  File "crypto_test.py", line 4, in <module>
    c = SHA512.new("hello".encode())
  File "site-packages/Cryptodome/Hash/SHA512.py", line 177, in new
  File "site-packages/Cryptodome/Hash/SHA512.py", line 85, in __init__
  File "ctypes/__init__.py", line 361, in __getattr__
  File "ctypes/__init__.py", line 366, in __getitem__
AttributeError: dlsym(0x7fe0f2e10ee0, SHA512_init): symbol not found
[22551] Failed to execute script crypto_test
```

Python Version: 3.6.6
OS: macOS 10.13.6

virtualenv (output from `pip freeze`):
```
altgraph==0.16.1
future==0.17.1
macholib==1.11
pefile==2018.8.8
pycryptodomex==3.7.3
PyInstaller==3.5.dev0+0d289e49b
```

Script (`crypto_test.py`):
```python3
from Cryptodome.Hash import SHA512

if __name__ == "__main__":
    c = SHA512.new("hello".encode())
    print(c.hexdigest())
```

Spec:
```
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(['crypto_test.py'],
             pathex=['/private/tmp/crypto_test'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='crypto_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='crypto_test')
```

Build Output
```
$ pipenv run pyinstaller crypto_test.spec --onedir --clean -y
82 INFO: PyInstaller: 3.5.dev0+0d289e49b
82 INFO: Python: 3.6.6
89 INFO: Platform: Darwin-17.7.0-x86_64-i386-64bit
96 INFO: UPX is available.
98 INFO: Removing temporary files and cleaning cache in /Users/huw/Library/Application Support/pyinstaller
123 INFO: Extending PYTHONPATH with paths
['/private/tmp/crypto_test', '/private/tmp/crypto_test']
123 INFO: checking Analysis
124 INFO: Building Analysis because Analysis-00.toc is non existent
124 INFO: Initializing module dependency graph...
126 INFO: Initializing module graph hooks...
128 INFO: Analyzing base_library.zip ...
3239 INFO: running Analysis Analysis-00.toc
3248 INFO: Caching module hooks...
3252 INFO: Analyzing crypto_test.py
3346 INFO: Loading module hooks...
3346 INFO: Loading module hook "hook-encodings.py"...
3449 INFO: Loading module hook "hook-xml.py"...
3632 INFO: Loading module hook "hook-pydoc.py"...
3632 INFO: Loading module hook "hook-Cryptodome.py"...
3648 INFO: Looking for ctypes DLLs
3652 INFO: Analyzing run-time hooks ...
3657 INFO: Looking for dynamic libraries
3801 INFO: Looking for eggs
3801 INFO: Using Python library /Users/huw/.pyenv/versions/3.6.6/lib/libpython3.6m.dylib
3805 INFO: Warnings written to /private/tmp/crypto_test/build/crypto_test/warn-crypto_test.txt
3827 INFO: Graph cross-reference written to /private/tmp/crypto_test/build/crypto_test/xref-crypto_test.html
3833 INFO: checking PYZ
3833 INFO: Building PYZ because PYZ-00.toc is non existent
3833 INFO: Building PYZ (ZlibArchive) /private/tmp/crypto_test/build/crypto_test/PYZ-00.pyz
4090 INFO: Building PYZ (ZlibArchive) /private/tmp/crypto_test/build/crypto_test/PYZ-00.pyz completed successfully.
4093 INFO: checking PKG
4093 INFO: Building PKG because PKG-00.toc is non existent
4093 INFO: Building PKG (CArchive) PKG-00.pkg
4097 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
4098 INFO: Bootloader /Users/huw/.local/share/virtualenvs/crypto_test-nR4wJhA5/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run
4098 INFO: checking EXE
4098 INFO: Building EXE because EXE-00.toc is non existent
4098 INFO: Building EXE from EXE-00.toc
4098 INFO: Appending archive to EXE /private/tmp/crypto_test/build/crypto_test/crypto_test
4099 INFO: Fixing EXE for code signing /private/tmp/crypto_test/build/crypto_test/crypto_test
4103 INFO: Building EXE from EXE-00.toc completed successfully.
4103 INFO: checking COLLECT
4103 INFO: Building COLLECT because COLLECT-00.toc is non existent
4104 INFO: Removing dir /private/tmp/crypto_test/dist/crypto_test
4116 INFO: Building COLLECT COLLECT-00.toc
5417 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

### LINKED ISSUE #5583: SHA1_init missing when using PyInstaller on OSX
## Description of the issue
There is no problem running the source code directly with python3 under OSX 11.1
When running the executable generated by PyInstaller, I get the following error message. 

 ```
File "gpsoauth/__init__.py", line 97, in perform_master_login
File "gpsoauth/google.py", line 51, in signature
File "Cryptodome/Cipher/PKCS1_OAEP.py", line 117, in encrypt
lHash = self._hashObj.new(self._label).digest()
 File "Cryptodome/Hash/SHA1.py", line 158, in new
 return SHA1Hash().new(data)
 File "Cryptodome/Hash/SHA1.py", line 74, in __init__
 result = _raw_sha1_lib.SHA1_init(state.address_of())
 File "ctypes/__init__.py", line 369, in __getattr__
File "ctypes/__init__.py", line 374, in __getitem__
AttributeError: dlsym(0x7fc07e7ee6d0, SHA1_init): symbol not found
 ```

After testing, it is found that the `sha1_init` symbol is in the source code `Cryptodome/Hash/_SHA1.abi3.so` library, and the `_sha1.cpython-39m-darwin.so` generated by Pyinstaller does not have the `sha1_init` symbol.

 ## Context information (for bug reports)
* pyinstaller 5.0dev
* python 3.9.1
* OSX 11.1
* There is no problem with the executable file generated by pyinstaller under the win platform

### PR DESCRIPTION
**Pull request by rokm**
On macOS and linux, some of the python's built-ins have extension modules that originally reside in `python3.X/lib-dynload` directory. This directory is in `sys.path`, therefore the collected extensions have no parent directory and end up directly in the `_MEIPASS`.

This commit explicitly diverts such extensions into `lib-dynload` sub-directory in the `_MEIPASS`.

In addition to decluttering the `_MEIPASS` on linux and macOS, this also prevents `ctypes.CDLL()` from picking up the extensions' shared libraries and causing inconsistent behavior between frozen and unfrozen application, which in some corner cases leads to issues with shadowing, such as in #5583.

Fixes #5583. Fixes #3993.

Requires rebuilt bootloader, which will add `_MEIPASS/lib-dynload to initial `sys.path`.

### CODE REVIEW

**Comment by bwoodsend** [comment]
How come this doesn't clash with the macOS/Mach-O library loader path rewriting magic we do on binaries?

**Comment by rokm** [comment]
> How come this doesn't clash with the macOS/Mach-O library loader path rewriting magic we do on binaries?

Actually, it does, hence the macOS CI failures - I'll need to adjust the rewriting procedure as well.

**Comment by rokm** [comment]
Oh well, I guess multipackage needs to be fixed first...

**Comment by rokm** [comment]
This requires multipackage fix from #5606 for the multipackage test to pass (currently rebased on top of it).

The other failures on macOS were indeed due to library path rewriting, but for a different reason than I thought originally. For onedir builds, I had adjusted only the target file path but not the path in bincache, whereas for onefile builds, the change was made on the level that affected both. Therefore, the library paths in lib-dynload extensions were correctly adjusted in onefile, but not in onedir. I've now moved the path/name adjustment up to `Analysis` so that it affects all codepaths in the same way. So no modifications in library-path-rewriting itself is needed after all.

**Comment by rokm** [comment]
I'll squash the building-related commits into a single commit during next rebase; they're left separate for now to better illustrate the original and follow-up changes.

**Comment by rokm** [comment]
This change requires bootloader to be re-build. So in the period between merging this and committing rebuilt bootloaders, installing `develop` branch via github's snapshot archive will result in non-functioning PyInstaller on linux and macOS.

**Comment by bwoodsend** [comment]
There's something broken with Github's CI it seems. Before 3.6 refused to start. Now 3.8 has done the same and 3.6 and 3.9 have been stuck on *Starting workflow run...* for the last 55 minutes.

> This change requires bootloader to be re-build. So in the period between merging this and committing rebuilt bootloaders, installing develop branch via github's snapshot archive will result in non-functioning PyInstaller on linux and macOS.

In that case I think we should just rebuild them now and be done with it. We have several big bug fixes like #5547 which will have people blindly installing from the development branch (me included) so merging this without building the bootloaders will cause a lot of disruption.

**Comment by Legorooj** [comment]
Going to attempt running the CI again.

**Comment by bwoodsend** [comment]
Given that it's just Windows causing the problems and Windows passed on AppVeyor I think it's ok to say CI has passed.

**Comment by Legorooj** [comment]
yeah, I agree. And the tests aren't actually failing, just taking too long. Needs debugging.

**Review by Legorooj — APPROVED** [review]

**Comment by bwoodsend** [comment]
Now for the next wave of antivirus false positives...

**Comment by rokm** [comment]
Ah, right, let's submit current bootloaders to virustotal before we officially make a release.

**Comment by bwoodsend** [comment]
I'm going to see if I can get the virustotal API going...

**Comment by bwoodsend** [comment]
[Looks like someone has beaten us to it](https://www.virustotal.com/gui/file/9cdda0f69b85ead8071c664ba68e58e11470933e72d1883e995ac4abd96c54a1/detection). Also, it now knows that it's a PyInstaller file thanks to [this user-defined yaru rule](https://github.com/bartblaze/Yara-rules/blob/master/rules/generic/PyInstaller.yar). Didn't know that was a thing...

**Comment by rokm** [comment]
> Looks like someone has beaten us to it.

Yeah, I figured manually uploading eight files will be faster than using API :)

Now let's wait and see how long after release they get flagged - i.e., are AV makers following PyInstaller releases, or are malware authors really quick on the uptake..)

But we might want to look into that `invalid-rich-pe-linker-version` tag.

**Comment by bwoodsend** [comment]
According to [this](https://bytepointer.com/articles/the_microsoft_rich_header.htm), the rich header is just a very heavily concealed and undocumented collection of MSVC version numbers. Given MS refuse to publicly admit the thing exists, I think we'll struggle to work out how to fix it. It's also very odd that these files built using an official MSVC aren't automatically correct.

**Comment by rokm** [comment]
I suspect `invalid-rich-pe-linker-version` uses same test as "linker_test" in `spoof_check.py` script from https://github.com/RichHeaderResearch/RichPE.git. The "validity" of the rich PE linker version seems to be based on check between major and minor versions declared in PE header and in Rich header, and depends on the toolchain version:

* current bootloaders (presumably VS2019): PE: 14, 28 vs Rich: 14, 0
* rebuilt with VS2017 toolchain: PE: 14, 16 vs Rich: 14, 0
* rebuild with VS2015 in Vagrant: PE: 14, 0 vs Rich: 14, 0

I've [rebuilt all bootloaders with VS2015 using vagrant VM](https://github.com/rokm/pyinstaller/tree/bootloaders-vs2015), and [the `invalid-rich-pe-linker-version` tag is gone](https://www.virustotal.com/gui/file/756b81ffd3f193049a1c758aa77614dac10032bbae84cdfddad60520288347bf/detection).

I'm not sure how much we should really care about that, though. The reports on bootloader files seem to be more or less the same (32-bit versions get more heat than 64-bit ones), and for all we know, this test/tag might actually be a honeypot to steer malware authors to older versions of VS.

**Comment by bwoodsend** [comment]
Let's just assume it's harmless then. Incidentally, if an AV did infer that our bootloaders were malware because of the rich header then that AV would be so prone to false positives that no-one would use it. `python38.dll` taken from the official python.org installer [also has this tag](https://www.virustotal.com/gui/file/24bfc999a733d4759ca40425610555f597b1d015f87ef5f84e15c665297247a4/detection).

**Pull request merged**
