### PR TITLE
correcting error: UnicodeDecodeError: 'utf-8' codec can't decode 

### PR DESCRIPTION
**Pull request by eduardomotta-emottasistemas**
correcting error: UnicodeDecodeError: 'utf-8' codec can't decode byte

### CODE REVIEW

**Comment by eduardomotta-emottasistemas** [comment]
this problem was reported in

https://stackoverflow.com/questions/75798409/pyinstaller-unicodedecodeerror-utf-8-codec-cant-decode-byte-0x91-in-position

**Comment by bwoodsend** [comment]
What do you have to do to need this change? Presumably this `byteaph.py` is in some non standard encoding? What is this `byteaph.py`? Is it something you wrote or something coming from a dependency?

**Comment by eduardomotta-emottasistemas** [comment]
> What do you have to do to need this change? Presumably this `byteaph.py` is in some non standard encoding? What is this `byteaph.py`? Is it something you wrote or something coming from a dependency?

I wrote the title of the pull request incorrectly.

I already fixed that.

**Comment by rokm** [comment]
This is definitely caused by source file violating PEP3120 - i.e., not being in UTF-8 encoding and failing to specify the actual encoding in the file. 

Unfortunately, python itself doesn't seem to be sufficiently strict about this: if I create a module file in with non-ASCII characters and encode it in non-UTF-8 (e.g., using `č` character and encoding file as ISO-8859-2, but without PEP263 header), I can import the module, but doing `mod.__loader__.get_source('module_name')` raises

```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/tokenize.py", line 334, in find_cookie
    line_string = line.decode('utf-8')
                  ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 18: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 997, in get_source
  File "<frozen importlib._bootstrap_external>", line 768, in decode_source
  File "/usr/lib64/python3.11/tokenize.py", line 375, in detect_encoding
    encoding = find_cookie(first)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/tokenize.py", line 339, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration
```

**Comment by eduardomotta-emottasistemas** [comment]
> This is definitely caused by source file violating PEP3120 - i.e., not being in UTF-8 encoding and failing to specify the actual encoding in the file.

This pull request fixes the bug for those situations.

**Comment by rokm** [comment]
> > This is definitely caused by source file violating PEP3120 - i.e., not being in UTF-8 encoding and failing to specify the actual encoding in the file.
> 
> This pull request fixes the bug for those situations.

My point is, this is not really a bug. You have a file with incorrect encoding, and if you sorted that out, there would be no need to fix (or rather, work around) anything.

But this is not the first time this problem has come up, so I guess I wouldn't mind having a work around for people who don't know or don't care about their files' encodings. 

However, the code should not be blindly catching all exception types, but only the one that is actually raised in the problematic situation (is that `UnicodeDecodeError` or `SyntaxError`, or both?). And there should be a comment as to why we are falling back to reading the source file as data file.

**Comment by eduardomotta-emottasistemas** [comment]
> My point is, this is not really a bug. You have a file with incorrect encoding, and if you sorted that out, there would be no need to fix (or rather, work around) anything.
> 
> But this is not the first time this problem has come up, so I guess I wouldn't mind having a work around for people who don't know or don't care about their files' encodings.
> 
> However, the code should not be blindly catching all exception types, but only the one that is actually raised in the problematic situation (is that `UnicodeDecodeError` or `SyntaxError`, or both?). And there should be a comment as to why we are falling back to reading the source file as data file.

I understand and agree with you.

I have little knowledge in Python, in fact I solved this problem, which also happened to me in a specific situation, using my knowledge in Ruby.

Can you help me make the changes you are suggesting?

**Comment by bwoodsend** [comment]
Most text editors will have a setting for encodings. Or if you know what encoding your code is written in, [declare it](https://peps.python.org/pep-0263/#defining-the-encoding) at the top of the file.

**Comment by eduardomotta-emottasistemas** [comment]
> However, the code should not be blindly catching all exception types, but only the one that is actually raised in the problematic situation (is that `UnicodeDecodeError` or `SyntaxError`, or both?). And there should be a comment as to why we are falling back to reading the source file as data file.

Rok, the modifications were made as per your suggestion. Now the error is caught only for UnicodeDecodeError

**Comment by rokm** [comment]
Ok, thanks. I'll probably push some more commits to this PR in the afternoon. On my test linux system, the error is `SyntaxError` not `UnicodeError`, so we need to account for both. And we need a proper test for this behavior.

**Comment by rokm** [comment]
Looks like the `SyntaxError` is raised as consequence of `UnicodeDecodeError` in cases when the invalid character appears on the first line of the file (because it breaks the scan for PEP263 encoding header). I've added the tests and extended the work-around, so we now handle both cases - with invalid characters appearing in comment on the first line or later on in the code.

**Review by bwoodsend — APPROVED** [review]

**Pull request merged**
