### PR TITLE
depend: Allow pylib detection when not a dependency of python.exe

### LINKED ISSUE #3942: python .dll not found in virtual environment
pyinstaller fails with the following error
```shell
(venv) C:\Users\eth0\Desktop\py>pyinstaller -F dict.py
64 INFO: PyInstaller: 3.5.dev0+5edb4f7de
64 INFO: Python: 3.7.2
64 INFO: Platform: Windows-10-10.0.17763-SP0
64 INFO: wrote C:\Users\eth0\Desktop\py\dict.spec
64 INFO: UPX is not available.
81 INFO: Extending PYTHONPATH with paths
['C:\\Users\\eth0\\Desktop\\py', 'C:\\Users\\eth0\\Desktop\\py']
81 INFO: checking Analysis
82 INFO: Building Analysis because Analysis-00.toc is non existent
84 INFO: Initializing module dependency graph...
87 INFO: Initializing module graph hooks...
90 INFO: Analyzing base_library.zip ...
3887 INFO: running Analysis Analysis-00.toc
3887 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\eth0\desktop\py\venv\scripts\python.exe
3918 INFO: Caching module hooks...
3931 INFO: Analyzing C:\Users\eth0\Desktop\py\dict.py
3936 INFO: Loading module hooks...
3937 INFO: Loading module hook "hook-encodings.py"...
4046 INFO: Loading module hook "hook-pydoc.py"...
4046 INFO: Loading module hook "hook-xml.py"...
4341 INFO: Looking for ctypes DLLs
4341 INFO: Analyzing run-time hooks ...
4357 INFO: Looking for dynamic libraries
4404 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_ssl.pyd
4446 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_ssl.pyd
4489 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4520 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4551 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4582 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4614 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd
4667 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_hashlib.pyd
4714 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_lzma.pyd
4745 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_lzma.pyd
4792 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_socket.pyd
4839 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4875 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4908 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4940 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
4985 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd
5019 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5050 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5095 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd
5126 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\select.pyd
5189 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5232 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5263 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5289 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll
5321 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5352 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5399 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5430 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
5462 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\vcruntime140.dll
6440 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6471 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6502 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6541 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6572 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6603 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6650 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6688 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6720 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6751 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll
6947 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
6976 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7008 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7039 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7077 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7112 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7148 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7165 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7196 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7243 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7270 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 INFO: Looking for eggs
7301 INFO: Using Python library C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\python37.dll
7301 INFO: Found binding redirects:
[]
7317 INFO: Warnings written to C:\Users\eth0\Desktop\py\build\dict\warn-dict.txt
7371 INFO: Graph cross-reference written to C:\Users\eth0\Desktop\py\build\dict\xref-dict.html
7402 INFO: checking PYZ
7402 INFO: Building PYZ because PYZ-00.toc is non existent
7402 INFO: Building PYZ (ZlibArchive) C:\Users\eth0\Desktop\py\build\dict\PYZ-00.pyz
8177 INFO: Building PYZ (ZlibArchive) C:\Users\eth0\Desktop\py\build\dict\PYZ-00.pyz completed successfully.
8208 INFO: checking PKG
8209 INFO: Building PKG because PKG-00.toc is non existent
8210 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "C:\Users\eth0\Desktop\py\venv\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+5edb4f7de', 'console_scripts', 'pyinstaller')()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\eth0\Desktop\py\dict.spec", line 32, in <module>
    console=True )
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 424, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 196, in __init__
    self.__postinit__()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\eth0\desktop\py\venv\lib\site-packages\PyInstaller\building\api.py", line 273, in assemble
    pylib_name = os.path.basename(bindepend.get_python_library_path())
  File "C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Users\eth0\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I have been trying to get this work on windows10 running Python 3.7.2 (x32)

The following are the packages installed
```shell
Package        Version
-------------- ------------------
altgraph       0.16.1
certifi        2018.11.29
chardet        3.0.4
future         0.17.1
idna           2.8
macholib       1.11
pefile         2018.8.8
pip            18.1
PyInstaller    3.5.dev0+5edb4f7de
pypiwin32      223
pywin32        224
pywin32-ctypes 0.2.0
requests       2.21.0
setuptools     40.6.2
urllib3        1.24.1
```

### PR DESCRIPTION
**Pull request by Loran425**
If libpython is not detected uses the dependency checker to look for a
dll matching the pattern pythonXY.dll using the same method as
automated detection.

Checks after automated detection and only on windows systems.

Fixes #3942

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request.

Why did you add the `if pydll in PYDYLIB_NAMES` check? I'd assume this to be always true on windows.

Regarding PYDYLIB_NAMES: I wonder if your change will solve the issue for cygwin or when using msys2. Or is this no issue on these platforms? Would be really great i you could try!

You also need to submit a [changelog entry](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change. Please mind to add *two identical* files: one for this pull-request and one for the related issue. Thanks

**Comment by Loran425** [comment]
Hmm good question on the check, they are both generated from the same data so not a lot of reason for it. 

I'll get that unneeded check stripped out, the changelog entries built, and start digging though the cygwin/msys2 versions to see how they handle python 3.7 venv executables tonight.

**Comment by htgoebel** [comment]
Thanks for the update. Looks like my answer was not recorded a few days ago.
Re. the chagelog entry: This reads like PyInstaller will solve this for all cases where the pylib is not listed in the PE Header - which is not the case.
I suggest rowring into the diretion of "python venv having VERSION.dll rather than pythonXY.dll". What Dou thou think?

**Comment by htgoebel** [comment]
For the records: From https://docs.python.org/3/library/venv.html

>Changed in version 3.7.2: Windows now uses redirector scripts for python[w].exe instead of copying the actual binaries. In 3.7.2 only setup_python() does nothing unless running from a build in the source tree.
>
>Changed in version 3.7.3: Windows copies the redirector scripts as part of setup_python() instead of setup_scripts(). This was not the case in 3.7.2. When using symlinks, the original executables will be linked.

**Comment by htgoebel** [comment]
More background see https://github.com/python/cpython/pull/11029:
There is now a `venvlauncher` which gets copied into the venv as python.exe. This launcher looks up the relevant information in pyvenv.cfg file.

**Comment by Loran425** [comment]
Hmmmm interesting. 
I'll get the change log entry to what you stated. 
as for the actual detection do you think its better to work with the current method of detection or pull from the same `pyvenv.cfg` file that is being written?

**Comment by htgoebel** [comment]
What information does the pyvenv.cfg file provide which can be useful?

If there is nothing useful in: After doing some more recherche, I come to the conclusion we keep the code as you provided it.

BTW: Please take the change to rebase on current develop head as there are conflicts due to recent changes.

**Comment by Loran425** [comment]
Sounds good. I should have some time this weekend/weekend to get the
required steps completed to get this PR.

Thanks for your help in keeping this up to standard and the wonderful info
you tracked down on why it was an issue in the first place.

**Comment by Loran425** [comment]
Yikes, 

Forgot how much of a pain rebase/squash can be for the first time in awhile.

As long as everything passes this should be good.

Let me know if anything else needs works,
Thanks again!

**Comment by altendky** [comment]
Are the force pushes necessary?  I really appreciate that a solution was found, developed, and shared.   But, is rewriting/deleting public history really worthwhile.  I have to update my deps every time to keep unbreaking my builds and I won't be able to rebuild any existing commits.

Certainly this is not a released version so there are no related 'guarantees', but I tend to think of public Git history as something that shouldn't be changed outside of extreme circumstances where secrets were published or the code is dangerous etc.

Thanks for any consideration.  If this is to continue I'll keep a branch in my fork I guess.

Cheers,
-kyle

**Comment by Pluckerpluck** [comment]
@altendky Rebasing pull requests is not uncommon for when they become stale or to fix merge conflicts. I'd go so far to say that it's almost standard practice. Github is designed around it and all CI triggers on a forced-pushed.

---------

Anyway, was just wondering if there's an update on this? I would very much like PyInstaller to work with Python 3.7 without me hosting my own copy of it locally.

**Comment by Loran425** [comment]
@Pluckerpluck Not really any updates as far as requirements that I know of for either functionality or repo PR spec. 
Just trying to debug the `Frozen encoding cp1252 is not the same as unfrozen utf-8.` issue with the appveyor tests when I have time. Thought it might have been a windows line ending issue but i've been unable to lock down the exact cause of the issue.

**Comment by bjones1** [comment]
The encoding CI failure was fixed in https://github.com/pyinstaller/pyinstaller/commit/824559fb0f25c14e599650c1662e882e06aa0efd. Rebase and it should go away.

**Comment by karolyi** [comment]
+1, please get this PR merged.

**Comment by Loran425** [comment]
Well that's been rebased and it looks like another pip update has broken something, if I'm reading the errors correctly. Open to any corrections if that's not the case and I just missed something.
Thanks @bjones1 for pointing out the fix for the previous issue.

**Comment by karolyi** [comment]
@Loran425 you have force pushed again, which broke the CI I guess. I'll come up with a non-force pushed PR with your changes during today.

**Comment by Loran425** [comment]
Yeah looking through https://github.com/pypa/pip/issues/6434 it looks like pip update broke pytest editable installs. 

Just so I'm on the same page on this topic. It is clear no one is happy with Force Pushed content at this level. How would you go about pushing a rebase and  triggering the CI checks if you have no new content to push without force pushing?

**Comment by karolyi** [comment]
@Loran425 you can't do much until that issue is resolved, as the entire dev branch is broken. I'd wait until people get that fixed, and then you can push and empty commit into your branch.

**Comment by altendky** [comment]
My personal choice is merges instead of rebases, at least when it comes to public history.  Builds should commence when you push.  In any case if you need to force a build you can push an empty commit as mentioned or close the PR and reopen it.

But, certainly rebasing PR's to always be a single commit is encouraged by many so I know my opinion isn't universally right.  :]

**Comment by altendky** [comment]
@Loran425 I've also found it easier to work in my forks if I use unique branch names that don't conflict with the upstream repo.  Then it's easy to switch to develop, pull, switch back to my branch, merge.  Just a little less git to remember and no local-branch-name-differs-from-remote-branch-name to keep track of.

**Comment by bjones1** [comment]
@Loran425, would you rebase this again on top of 06f7da789f41a21dd697478ca317c858bc6be9e4, which fixes the pip update failure? We should then see a clean CI.

**Comment by Loran425** [comment]
Alright lets hope for smooth sailing this go round. 
Thanks everyone for the tips on how to keep thing smooth while contributing to public repositories. Made some mistakes along the way but hopefully further contributions here or elsewhere will be smoother.

**Comment by karolyi** [comment]
Unfortunately, the main branch is still breaking the CI, so it makes no difference :(

**Comment by bjones1** [comment]
I wonder if this is just CI confusion; I'd suggest re-running the build. Things suddenly get happy halfway through Appveyor's run for no good reason. Also, My build at https://ci.appveyor.com/project/bjones1/pyinstaller/builds/24193128 completed just fine.

Or, if I'm missing something obvious, please point it out :).

**Comment by altendky** [comment]
https://ci.appveyor.com/project/matysek/pyinstaller/builds/24222256

Sure seems like it could have been a temporary AppVeyor issue.  Cache failure in the beginning of all the failures, not in the successes.  I don't know what gets cached or why the error at the end, but I'd definitely restart the build (unless someone has AppVeyor permissions and can relaunch just the failed jobs).

**Comment by karolyi** [comment]
LGTM !

**Comment by Loran425** [comment]
Huzzah!

**Comment by karolyi** [comment]
guys, what are you waiting for?

**Comment by bjones1** [comment]
Thanks for your contribution! I merged this in 80941bcdbfdb2baabdaafa023f1e2abbc45b0218.

**Pull request closed without merging**
