### PR TITLE
bootloader: search for python malloc labeled shared libraries (AIX)

### LINKED ISSUE #4210: Pyinstaller3.X does not find libpython3.6m.so (AIX)
Hi. New to PyInstaller. Is this a bug?

Pyinstaller3,4 finds libpython3.6m.so but does not recognize it as a valid library.

After I create a symbolic link from /usr/lib/libpython3.6.so to libpython3.6m.so it works fine.

FYI: platform is AIX, Python is Python3-3.6.8 (see [https://github.com/aixtools/cpython/tree/aix-v3.6.8](https://github.com/aixtools/cpython/tree/aix-v3.6.8)) - I have a patch to ctypes (which is in v3.7, but not backported to v3.6) to fix ctype.find_library() and also to allow load of a MEMBER file of an AIX archive.
For this particular issue finding an archive member and/or dlload() of an archive(member) is not relevant as the default shared library packaging creates a .so file, rather than an archive containing a .so file.

```
root@x067:[/home/root/python/hello]ldd /opt/bin/python3
/opt/bin/python3 needs:
         /usr/lib/libc.a(shr.o)
         /usr/lib/libpthreads.a(shr_xpg5.o)
         /usr/lib/libpython3.6m.so
         /unix
         /usr/lib/libcrypt.a(shr.o)
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libdl.a(shr.o)

```

### PR DESCRIPTION
**Pull request by aixtools**
(AIX) add pattern to find libpython3.Xm.so

Closes #4210

### CODE REVIEW

**Comment by Legorooj** [comment]
@aixtools quick Q - are the `.so` files definitely produced? I'll need to change my PR if so - I removed the name.

**Comment by aixtools** [comment]
will try close and open to trigger CI. The failure looks to be an issue with the CI process (could not download zope). If it goes bad again I'll need to figure out what is wrong - as the only change is the commit prefix!

**Comment by Legorooj** [comment]
https://travis-ci.org/pyinstaller/pyinstaller/jobs/660762579#L1031 nope please address the lint errors.

**Comment by aixtools** [comment]
Trying to understand what I, if anything, did to get this result:

Collecting zope.interface==4.7.1

  Downloading zope.interface-4.7.1.tar.gz (151 kB)

    ERROR: Command errored out with exit status 1:

     command: /home/travis/virtualenv/python3.9-dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tq16sdaw/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tq16sdaw/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-tq16sdaw/zope.interface/pip-egg-info

         cwd: /tmp/pip-install-tq16sdaw/zope.interface/

    Complete output (5 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-tq16sdaw/zope.interface/setup.py", line 26, in <module>

        from setuptools import setup, Extension, Feature

    ImportError: cannot import name 'Feature' from 'setuptools' (/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/__init__.py)

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The command "pip install --progress-bar=off -U -r tests/requirements-tools.txt -r tests/requirements-libraries.txt" failed and exited with 1 during .

**Comment by aixtools** [comment]
Again - no idea what the cause is of these CI fails:

Collecting Unidecode==1.1.1

  Downloading Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)

Collecting zeep==3.4.0

  Downloading zeep-3.4.0-py2.py3-none-any.whl (99 kB)

Collecting zope.interface==4.7.1

  Downloading zope.interface-4.7.1.tar.gz (151 kB)

    ERROR: Command errored out with exit status 1:

     command: /home/travis/virtualenv/python3.9-dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f22v9pz6/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f22v9pz6/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-f22v9pz6/zope.interface/pip-egg-info

         cwd: /tmp/pip-install-f22v9pz6/zope.interface/

    Complete output (5 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-f22v9pz6/zope.interface/setup.py", line 26, in <module>

        from setuptools import setup, Extension, Feature

    ImportError: cannot import name 'Feature' from 'setuptools' (/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/__init__.py)

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The command "pip install --progress-bar=off -U -r tests/requirements-tools.txt -r tests/requirements-libraries.txt" failed and exited with 1 during .

Your build has been stopped.

**Comment by Legorooj** [comment]
@aixtools I've restarted the failing builds that need it (ignore the python: nightly one)

**Comment by htgoebel** [comment]
Thanks for this pull-request. I just reworked and merged it.

Re. "change the commit prefix to depend": This was ment to amend the commit message, not the changelog entry.

**Pull request merged**
