### PR TITLE
Hooks: hook-pint should copy metadata.

### PR DESCRIPTION
**Pull request by cowo78**
Accessing pint version at runtime requires setuptools metadata.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thank you for this pull-request. For this pull-request to be merged, please 
* reword the **commit messages** to comply to our [Commit Message Rules](https://pyinstaller.readthedocs.io/en/latest/development/commit-messages.html#commit-messages), and
* submit a [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change.

**Comment by cowo78** [comment]
Well, the commit message didn't seem that bad to me. I've reworded a little and added the news fragment.

**Comment by cowo78** [comment]
Please see updated PR.

**Comment by htgoebel** [comment]
Thanks for updating the pull-request. Although I needed to correct the change log entry (was plain wrong since you did not "Add" the hook).

**Comment by cowo78** [comment]
Ah, absolutely. My bad.

**Pull request merged**
