### PR TITLE
Add bcrypt hook.

### LINKED ISSUE #4735: bcrypt needs _cffi_backend
Please add a hook for bcrypt, identical to nnpy. It needs the hidden import _cffi_backend.

### PR DESCRIPTION
**Pull request by vashek**
Closes #4735

### CODE REVIEW

**Comment by Legorooj** [comment]
Please edit the commit message to add the `hooks: ...msg...` prefix.

**Comment by vashek** [comment]
> Please edit the commit message to add the `hooks: ...msg...` prefix.

Right, sorry. Not sure how to change the commit message of an existing commit without causing what happened here, so I made a new PR #4750.

**Comment by Legorooj** [comment]
@vashek you need to be using the Git CLI.

**Comment by vashek** [comment]
> @vashek you need to be using the Git CLI.

I am -- I did a `git commit --amend` but then I couldn't push without pulling first and that made the extra merge commit.
Feel free to ignore this but just out of curiosity if you happen to know off the top of your head, I wonder what the right way would have been.

**Comment by Legorooj** [comment]
@vashek the right way if there was another commit is `git rebase -i` and just edit the commit message.

**Pull request closed without merging**
