### PR TITLE
Add import of platformthemes on linux

### PR DESCRIPTION
**Pull request by Insoleet**
Tis PR fixes the bug https://github.com/pyinstaller/pyinstaller/issues/1769

### CODE REVIEW

**Comment by bjones1** [comment]
Looks great! Thanks for the help.

**Comment by bjones1** [comment]
What needs to be done here?

**Comment by htgoebel** [comment]
Nothing anymore. I just assigned to you because you took care of it.

**Comment by bjones1** [comment]
I see. Thanks!

**Pull request merged**
