### PR TITLE
fix issue #2826: "datas" is "binaries"?

### PR DESCRIPTION
**Pull request by charlesoblack**
This commit fixes issue #2826, '"datas" is "binaries"?'.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for this pull-request. Can you please provide a more explanatory commit-message. Maybe take some details or wording from the original issue.
Please have a look at [Please Write Good Commit Messages](https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html) to understand what I mean.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

**Comment by rllola** [comment]
I can confirm that there is a mistake here https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/building/build_main.py#L225

Currently the program is appending the `datas` to `binaries`.
I have been spending hours on try to find what I was doing wrong when I finally decided to take a look at the source code.

This PR will fix the problem.

**Comment by htgoebel** [comment]
@charlesnicholson I still need a more meaningful commit-message for this to merge. Please take your time, thanks.

**Comment by htgoebel** [comment]
Thanks again for this pull-request :-)

**Pull request merged**
