### PR TITLE
Hooks: add hook for altair package

### PR DESCRIPTION
**Pull request by quantleap**
Add hook for the Altair project:

https://altair-viz.github.io/index.html

The project contains json schema files which are not copied over by default.

### CODE REVIEW

**Comment by Legorooj** [comment]
Thanks for this PR! Unfortunately, you'll need to move it over to our new hooks package - which will be ready for PRs in a day or two (I just need to finish writing the development guide). I'm leaving this PR open in the meantime, and I'll let you know when you can move it.

**Comment by quantleap** [comment]
No worries, already read about that. Would you also propose getting it mended in the original package ? Then I could look at that in the mean time.

**Comment by Legorooj** [comment]
@quantleap if the developers of altair are happy to have it built in to altair, please go ahead. See https://pyinstaller-sample-hoom.readthedocs.io for details.

**Comment by Legorooj** [comment]
@quantleap please re-target this PR at https://github.com/pyinstaller/pyinstaller-hooks-contrib.

**Pull request closed without merging**
