### PR TITLE
Don't resolve symlinks in modulegraph.py

### PR DESCRIPTION
**Pull request by inglesp**
Resolves https://github.com/pyinstaller/pyinstaller/issues/1750

### CODE REVIEW

**Comment by htgoebel** [comment]
@pyinstaller/contributors I suggest putting this into the bug-fix-release 3.1.1 (if there is one). What do you think?

**Comment by bjones1** [comment]
I agree.

**Comment by htgoebel** [comment]
he first commit was fine. Please remove the other two, so I can merge.

**Comment by inglesp** [comment]
Oof, sorry about that -- I'd been using this branch to build something on Travis which was failing, and so had added some verbose logging to try to work out what the problem was.  Hadn't meant that to end up in this pull request!  Should be fixed now.

**Comment by htgoebel** [comment]
Thanks.

**Pull request merged**
