### PR TITLE
Fix and simplify symlinking in Mac OS X app bundle

### PR DESCRIPTION
**Pull request by springermac**
Fix symlinks so they are relative to the current directory. Also
simplify symlinking code.

### CODE REVIEW

**Comment by matysek** [comment]
Looks fine to me. Thanks.

**Comment by akbhat** [comment]
MT
The  hidden import for ncclient was indeed the issue. I was able to test the executable on Win7 but ran into a totally unrelated issue when generating the executable on a Ubuntu machine. How do I resolve this?

abhat@ubuntu:~/Desktop$ pyinstaller --onefile --hidden-import=ncclient.devices.junos jdatap.py
12 INFO: PyInstaller version 3.0dev
12 INFO: wrote /home/abhat/Desktop/jdatap.spec
15 INFO: UPX is not available.
16 INFO: Extending PYTHONPATH with /home/abhat/Desktop
16 INFO: checking Analysis
17 INFO: Building Analysis because out00-Analysis.toc is non existent
17 INFO: Initializing module dependency graph...
18 INFO: Looking for graph hooks ...
19 INFO: Analyzing hidden import 'ncclient.devices.junos'
2295 INFO: running Analysis out00-Analysis.toc
2313 INFO: Analyzing jdatap.py
3858 INFO: Looking for import hooks ...
3860 INFO: Processing hook   hook-distutils.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:15: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import distutils
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:16: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:17: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sys
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:18: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sysconfig
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:20: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.compat import base_prefix
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:21: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import relpath_to_config_or_make
3862 INFO: Processing hook   hook-sysconfig.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:15: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sysconfig
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:16: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:17: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  import sys
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:19: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller import compat
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:20: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import relpath_to_config_or_make
3863 INFO: Processing hook   hook-xml.py
3930 INFO: Processing hook   hook-jinja2.py
3964 INFO: Processing hook   hook-lxml.etree.py
3978 INFO: Processing hook   hook-httplib.py
3978 INFO: Processing hook   hook-xml.sax.py
3979 INFO: Processing hook   hook-encodings.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-encodings.py:11: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import collect_submodules
4325 INFO: Looking for ctypes DLLs
4367 WARNING: library rpcrt4.dll required via ctypes not found
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0.dev0', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/main.py", line 97, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/main.py", line 50, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 682, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 625, in build
    exec(text, spec_namespace)
  File "<string>", line 12, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 181, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/datastruct.py", line 151, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 420, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/depend/utils.py", line 147, in scan_code_for_ctypes
    instrs = pass1(co.co_code)
AttributeError: 'NoneType' object has no attribute 'co_code'

**Comment by htgoebel** [comment]
> ran into a totally unrelated issue

So please open a new issue. Capturing existing issues with unrelated stuff makes it hard to manage them. Thanks.

**Comment by matysek** [comment]
@akbhat I'm sorry, there is a typo in the issue number. It should be #1433 :-)

**Pull request merged**
