### PR TITLE
Create hook-pytds.py

### PR DESCRIPTION
**Pull request by sam2332**
Please merge new hook for tds.

### CODE REVIEW

**Review by bwoodsend — CHANGES_REQUESTED** [review]
This needs a [news entry](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/news/README.txt).  And we need all Python source files to have the copyright header. Otherwise anyone copying those files (including us) is technically infringing copyright and is liable to be sued.

**Review by bwoodsend — CHANGES_REQUESTED** [review]
And the news entry...

**Comment by rokm** [comment]
Actually, this should go into [contrib hooks](https://github.com/pyinstaller/pyinstaller-hooks-contrib).

**Comment by bwoodsend** [comment]
Oops, I didn't realise that this was the main repo. @sam2332 Can you instead add this file to [the stdhooks dir in the hooks repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib/tree/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks)? Sorry, I should have spotted that...

**Pull request closed without merging**
