### PR TITLE
Hooks: add gooey hook

### PR DESCRIPTION
**Pull request by AndCycle**
just a simple one

gooey carry some language json and images for it's UI to function.

### CODE REVIEW

**Comment by htgoebel** [comment]
I forgot: 
When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual..

**Comment by AndCycle** [comment]
thanks for the remind, 
just add the info to comply the new rule.

**Comment by htgoebel** [comment]
Thanks for the quick update. Unfortunately the [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) is still missing. Please add it so other users can learn about the new hook.

**Comment by htgoebel** [comment]
Thanks for the update and for this hook :-) I just merged it.

**Pull request merged**
