### PR TITLE
building: makespec: add new command-line switches for hookutils functions

### PR DESCRIPTION
**Pull request by rokm**
Add new command-line options that map to the corresponding functions from the hookutils:
* --collect-submodules: collect_submodules()
* --collect-data: collect_data_files()
* --collect-binaries: collect_dynamic_libs()
* --collect-all: collect_all()
* --copy-metadata: copy_metadata()

The hookutils calls are added to the generated .spec files. They may be specified multiple times, and their results supplement
the entries that are manually passed via existing --add-data, --add-binary, and --hidden-import switches.

This allows hookutils calls to be added from command-line, without having to manually edit the .spec file.

### CODE REVIEW

**Comment by bwoodsend** [comment]
Ah, brilliant. I've been meaning to do this for ages.

**Comment by bwoodsend** [comment]
`--collect-submodules=foo` is already implemented as `--hiddenimport=foo.*` but I think `--collect-submodules` is more intuitive.

**Comment by htgoebel** [comment]
I'm not convinced we should add more command-line options. Look at the many options available in the .spec-file. If you try to support all these, this will create a command-line interface with many, many options. And this is terrible UX.

**Comment by bwoodsend** [comment]
> this will create a command-line interface with many, many options. And this is terrible UX.

What makes you say that lot's of options is bad user experience?

Personally, I find:
```shell
$ pyinstaller -h
pages and pages of stuff
half of which I've never ever used
some of which is for a different operating system
```
to be a pain. I almost always need grep to find what I'm looking for (normally something along the lines of *is it `--hiddenimport`, `--hidden` or `--hidden-import`?*) I'd prefer the output of help to be abbreviated by default, with an option to give more details on a specific topic. And maybe group the options like gcc does, use `--help=topic` to get detailed descriptions within a group?

I've had to walk inexperienced users through switching to the spec file in order to use one of these hook utilities far too many times whereas I've never used an option like `--win-no-prefer-redirects` so if it's a matter of limiting the number of CLI options, I'd start jettisoning some of the less useful ones to make space for these new hook utility ones.

**Pull request merged**
