### PR TITLE
issue-4211: fix bootloader: library identifers are case sensitive on AIX

### PR DESCRIPTION
**Pull request by aixtools**
Library identifier needs to be changed from 'Z' to 'z'

See #4211

### CODE REVIEW

**Comment by aixtools** [comment]
Any thoughts?

**Comment by htgoebel** [comment]
Thank you for this pull-request.

Do you think this is important enough to add a [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change?! If so, please submit one.

**Comment by aixtools** [comment]
Asis - this is just a typo, imho.

However, once upon a time there was a choice to call this a "staticlib" linkage - which, I expect it is not.

What I should perhaps try is:
libs.remove('Z')
libs.append('z')

Assuming this works, is this your preference? And then a changelog is perhaps in order - that AIX library arguments are case sensitive.

**Comment by aixtools** [comment]
Rather than a changelog entry - seems overkill - just added a bit of text to the comment that already existed.

**Comment by htgoebel** [comment]
I agree on a change-log entry being to much. I just merged it. Thanks again.

**Pull request merged**
