### PR TITLE
Create hook-argon2.py

### LINKED ISSUE #4625: Import hook for argon2 (password hashing library)
**Is your feature request related to a problem? Please describe.**
I could not use password authentication easily.

**Describe the solution you'd like**
Make it easier to use a good password hashing library.

**Describe alternatives you've considered**
I tried to use `passlib` but the pull-request I found did not work for me and it was easier to fix this library directly.

**Additional context**
This seems to be a good password hashing algorithm, would be great to support it by default.

### PR DESCRIPTION
**Pull request by IlyaOrson**
Password hashing with [argon2](https://pypi.org/project/argon2-cffi/).

Closes #4625

### CODE REVIEW

**Comment by bjones1** [comment]
Thanks. Would you change your news file's name to `4625.hooks.rst`, since that's the issue this PR closes? Also, would you consider writing a short test? For example, from https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py#L78: 

``` Python
@importorskip('gevent')
def test_gevent(pyi_builder):
    pyi_builder.test_source(
        """
        import gevent
        gevent.spawn(lambda: x)
        """)
```

The idea is to import something from argon2 then use it to show that everything is packaged correctly.

**Comment by Legorooj** [comment]
@IlyaOrson pinging

**Comment by IlyaOrson** [comment]
Thanks for the revision, I fixed the names and added a test.

**Comment by Legorooj** [comment]
One last thing: https://travis-ci.org/pyinstaller/pyinstaller/jobs/658382702?utm_medium=notification&utm_source=github_status (at the bottom)

**Comment by htgoebel** [comment]
I forgot: Thanks for this pull-request. I merged it yesterday already.

**Pull request merged**
