### PR TITLE
Appveyor fixes

### PR DESCRIPTION
**Pull request by springermac**
- Implement a better way of cleaning up temp files from a test run that works cross platform.

- Allow a scheduled Appveyor build to only install dependencies and not run tests.
This allows the cache to be kept fresh even when the tests are failing. Requires the "Build schedule" setting to be set on appveyor. See https://ci.appveyor.com/project/springermac/pyinstaller/build/1.0.90 for an example of a scheduled run.

### CODE REVIEW

**Comment by htgoebel** [comment]
Assigning to @bjones1 since you are working on this topic.

**Comment by springermac** [comment]
@matysek This merge would require changing a setting on AppVeyor to run a scheduled build.

**Comment by bjones1** [comment]
This looks good. Let me run tests locally, since Appveyor is of little use at the present.

@matysek. I concur with @springermac: would you update the Appveyor setting?

**Comment by bjones1** [comment]
@springermac, I see the following error:


```
ERROR tests/functional/test_basic.py::test_arbitrary_ext[onefile]

=================================== ERRORS ====================================
______________ ERROR at teardown of test_arbitrary_ext[onefile] _______________
[gw5] win32 -- Python 3.5.1 c:\users\bjones\downloads\anaconda3\python.exe
def del_temp_dirs():
        for dir in passed:
            if os.path.exists(dir):
>               shutil.rmtree(dir)

tests\functional\conftest.py:440:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\users\bjones\downloads\anaconda3\lib\shutil.py:488: in rmtree
    return _rmtree_unsafe(path, onerror)
c:\users\bjones\downloads\anaconda3\lib\shutil.py:378: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
c:\users\bjones\downloads\anaconda3\lib\shutil.py:378: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
c:\users\bjones\downloads\anaconda3\lib\shutil.py:383: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\bjones\\AppData\\Local\\Temp\\pytest-of-bjones\\pytest-0\\popen-gw5\\test_multiprocess_onedir_0\\dist\\pyi_multiprocess'
onerror = <function rmtree.<locals>.onerror at 0x0B6EDE88>

    def _rmtree_unsafe(path, onerror):
        try:
            if os.path.islink(path):
                # symlinks to directories are forbidden, see bug #1669
                raise OSError("Cannot call rmtree on a symbolic link")
        except OSError:
            onerror(os.path.islink, path, sys.exc_info())
            # can't continue even if onerror hook returns
            return
        names = []
        try:
            names = os.listdir(path)
        except OSError:
            onerror(os.listdir, path, sys.exc_info())
        for name in names:
            fullname = os.path.join(path, name)
            try:
                mode = os.lstat(fullname).st_mode
            except OSError:
                mode = 0
            if stat.S_ISDIR(mode):
                _rmtree_unsafe(fullname, onerror)
            else:
                try:
>                   os.unlink(fullname)
E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bjones\\AppData\\Local\\Temp\\pytest-of-bjones\\pytest-0\\popen-gw5\\test_multiprocess_onedir_0\\dist\\pyi_multiprocess\\ucrtbase.dll'

c:\users\bjones\downloads\anaconda3\lib\shutil.py:381: PermissionError
```

Would you wrap the call to rmtree in a try/catch block to ignore this case?

Also, I see a lot of files that don't get cleaned up after your fix -- over 2GB on my system. Would you mind putting the cleanup code in a separate pull request? I'd like to get just your Appveyor fixes merged, then work on cleanup in a separate request.

**Comment by springermac** [comment]
@bjones1 I'll remove the cleanup code.

**Comment by springermac** [comment]
@bjones1 Cleanup code removed.

**Comment by bjones1** [comment]
@springermac, thanks!

@matysek, please update the Appveyor settings when you have a minute.

**Comment by springermac** [comment]
@matysek I would set a scheduled build to run as soon as possible then schedule them for a time when there isn't much activity.

**Comment by matysek** [comment]
@bjones1 @springermac thanks for these fixes. I set periodical building twice per day.

**Comment by bjones1** [comment]
@matysek, thanks! I appreciate your help.

**Comment by bjones1** [comment]
A thought based on some of the odd Appveyor behavior I've seen: per the [docs](https://www.appveyor.com/docs/build-configuration#build-environment), Appveyor sometimes gives us one full core...and sometimes, we share that core with another test. So, build times that were at or above 30 minutes (which is most of the tests) suddenly take an hour, perhaps explaining tests that pass then later time out with no significant changes that would explain this behavior.

**Pull request merged**
