### PR TITLE
Build-essential python-dev required on Ubuntu OS

### PR DESCRIPTION
**Pull request by talhaobject90**

### CODE REVIEW

**Comment by talhaobject90** [comment]
http://stackoverflow.com/questions/33311758/pyinstaller-on-ubuntu-throws-exception-pyinstaller-compat-filenotfounderror

**Comment by htgoebel** [comment]
Todo:
- Only `python-dev` is required.
- Commit-Message should state why: 
- This should be worded more generally, not targeted to ubuntu or debian.
- Do not mention `apt get`. A programmer should know this.

Wany you please update your pull-request?

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept.

**Comment by htgoebel** [comment]
@talhaobject90 Pinging. Are you going to update the pull-request as requested?

**Comment by talhaobject90** [comment]
sorry , i am currently a bit tight, will take a couple of days to relieve

**Comment by htgoebel** [comment]
I'm closing this now since there has been no update for 6 month now. If you are going to update the pull-request, just drop be a note.

**Pull request closed without merging**
