### PR TITLE
Fix comments for TOC class.

### PR DESCRIPTION
**Pull request by k-kapp**
Fix typo "tytecode" and have columns in table follow the same order as in tuple (name, path, typecode).

### CODE REVIEW

**Comment by k-kapp** [comment]
Why is this failing??? I only edited some comments - none of the actual code

**Comment by htgoebel** [comment]
@k-kapp: I assume something else is broken, so the tests fail.

This patch changes *every* line of the file. I assume you mixed up the line-endings. Please FIXUP the commit and push it again for review.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept.

**Comment by htgoebel** [comment]
@k-kapp Are you going to update this pull-request? As it is now, I can not review it. If you are nor going to update, I'll need to close.

**Comment by k-kapp** [comment]
@htgoebel Hi, sorry, I've been buried under work the past few weeks and have not been able to continue with this. You may close. Sorry for my sloppiness :/

**Comment by htgoebel** [comment]
After merging manually I found the difference: The table at the [top of the `TOC` class[(https://github.com/pyinstaller/pyinstaller/pull/2289/files#diff-603b828a9efbed96cb075d021353c58aL48) has been changed to follow the order of fields in the `TOC` list. I prefer to keep the old list with the `typecode` in the first column.

**Pull request closed without merging**
