### PR TITLE
Hooks: Get qmldir from Qml2ImportsPath for PySide2

### LINKED ISSUE #3689: ImportError: cannot import name 'exec_command' from 'PyInstaller.utils.hooks'
Building a PySide2/QtQuick application with the development branch of pyinstaller gives the following error:

 ```
 File "<snip>\PyInstaller\hooks\hook-PySide2.QtQuick.py", line 13, in <module>
    from PyInstaller.utils.hooks import get_qmake_path, exec_command
ImportError: cannot import name 'exec_command' from 'PyInstaller.utils.hooks' (<snip>\PyInstaller\utils\hooks\__init__.py)
```
(note: using Python3.7, Windows 10)

I suspect that `hook-PySide2.QtQuick.py` should instead be importing `exec_command_stdout`. Possibly related to issue #3089

### PR DESCRIPTION
**Pull request by cbenhagen**
Fixes #3689

### CODE REVIEW

**Comment by bjones1** [comment]
Thanks for your contribution. Would you:

1. Add a changelog file named `news/4136.bugfix.rst` with a brief description of your changes (see https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html for more info).
2. Rebase this onto the current develop.

**Comment by sjackso** [comment]
I have a client whose software depends on this fix -- I have them on a custom version right now, but I would like to help get this PR merged.

@bjones1 Is it okay if I open a new PR with @cbenhagen's patch, plus the changes you requested above, so that these changes may be applied?

**Comment by cbenhagen** [comment]
Sorry I must have missed the notification. Yes please go ahead!

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.

**Pull request closed without merging**
