### PR TITLE
Add a hook for PyQt6 QtOpenGLWidgets and add a dynamic dependency

### PR DESCRIPTION
**Pull request by uhwo**

### CODE REVIEW

**Review by rokm — CHANGES_REQUESTED** [review]
The hook looks OK. 

But it applies to `PySide6` as well - can you add a copy for `hook-PySide6.QtOpenGLWidgets.py` as well? 

Also, please add a [news entry for the PR](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/development/changelog-entries.rst).

**Comment by uhwo** [comment]
> 
> 
> The hook looks OK.
> 
> But it applies to `PySide6` as well - can you add a copy for `hook-PySide6.QtOpenGLWidgets.py` as well?
> 
> Also, please add a [news entry for the PR](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/development/changelog-entries.rst).

I added the PySide6 hook together with the news entry

**Review by bwoodsend — APPROVED** [review]
Looks good to me.

**Review by rokm — APPROVED** [review]

**Comment by bwoodsend** [comment]
Thanks @uhwo!

**Pull request merged**
