### PR TITLE
additional argument STRIPFLAGS not passed properly to linker/loader (AIX)

### PR DESCRIPTION
**Pull request by aixtools**
Closes https://github.com/pyinstaller/pyinstaller/issues/4730

The intent is clear - however the value -X32 or -X64 is passed as 3 seperate arguments (-X -3 -2) and these are not recognized by the AIX linker/loader (ld).

The argument -X32 or -X64 is better managed using the environment variable OBJECT_MODE as all AIX utilities recognize this environment variable.

### CODE REVIEW

**Comment by Legorooj** [comment]
https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html

And

https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html

**Comment by Legorooj** [comment]
https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html

Commit prefixes please

**Comment by htgoebel** [comment]
Thanks for this pull-request.

I'm a bit confused: The pull-request title is "neither needed nor working", file in the explanation you write "… is better managed …" - which is quite a difference for me. And in the commit message you write "is not recognized …". And in the 4731.doc.rst you explain how you suggest this o be used.

What about this:
1. Move (and rewrite a little) 4731.doc.rst into an "Building for AIX" section in `docs/bootloader-building.rst` (just above "Vagrantfile Virtual Machines". This s worth not been burried in release notes. -> This shall become a commit of it's own, changelog entry is optional.
  Please mind we are using [semantic line breaks](https://sembr.org/).
2. Change the other commit into "Bootloader build: wscript: Remove not recognized flags for AIX.

**Comment by aixtools** [comment]
Will do. Thx for the getting #4738 past CI!

**Comment by aixtools** [comment]
I changed the title - again - getting a title right is harder than the fix - imho. Also worked on the initial description - hope that is okay. And I'll still open a new PR with the documentation addition.

**Comment by htgoebel** [comment]
Please just put the documentation in here. If this is one pull-request, I can clean it of in case it is necessary.

**Comment by htgoebel** [comment]
@aixtools Thanks again for the pull-request, which I just merged. I also added platfrom-specific usage notes, based on your text.

Thanks for the documentation. I now understand what this is about. But I'm curious, whether we shall make it so complicated for the user. Why not determine Python's size within a) the wscript and b) pyinstalller and set OBJECT_MODE accordingly? If you like this idea, please provide a pull-request (which I promise to merge quicker :-)

**Pull request merged**
