### PR TITLE
Hook keyring

### PR DESCRIPTION
**Pull request by rbranche**

### CODE REVIEW

**Comment by rbranche** [comment]
I'm sorry about this. I'm not sure why I didn't get any notifications for this, but I didn't see any of the change requests. I was reminded earlier today that I created these and came back to check the status.

**Comment by htgoebel** [comment]
@rbranche Are you going to update the pull-request anytime soon?

**Comment by rbranche** [comment]
This one seems to be closed already with the changes that @matysek wanted. Where there any additional changes needed?

**Comment by matysek** [comment]
@rbranche I don't think there are any additional changes needed. It looks like @htgoebel already did them.

**Comment by htgoebel** [comment]
@rbranche Okay, I should have read my own comments :-) Yes, I did the changes. https://github.com/pyinstaller/pyinstaller/pull/150#issuecomment-67254523 was to express that I would have expected you to do this.

**Comment by rbranche** [comment]
@htgoebel Yeah, sorry about that. I have updated #151 per the review comments.

**Pull request merged**
