### PR TITLE
MacOS: Make apps accept both drag/drop & URL events via ARGV EMU before startup. After startup: Apps now accept URL & drag/drop events via Apple Event forwarding

### PR DESCRIPTION
**Pull request by cculianu**
Hi,

Electron Cash developer (and occasional Electrum contributor) here!  We use pyinstaller for our app and love it.

However we noticed that the bootloader parent process wasn't properly picking up the MacOS "URL" events (kAEGetURL as it's called on macOS) and it wasn't forwarding them to the child process.  

It also didn't accept drag/drops of files after the program was started.

There was a patch that someone wrote a couple of years back that supposedly fixed this -- but it didn't actually work at all as intended on modern MacOS. I tried on El Capitan and up. No luck. 

So-- URI/URL handling wasn't working at all.  Not at startup, and not if the app was already running.

Drag/drop only worked previously if the app wasn't running.  After startup -- the events wouldn't make it to the GUI framework.

So I went ahead and fixed it by rewriting some of the bootloader code that was in the aforementioned commit.  Note that this code only gets compiled in if using WINDOWED building mode on macOS.

### To Test ###

Create an app with pyinstaller on Mac that accepts custom URI/URLs for a test scheme, say `myscheme:`, by adding the following XML to your `Info.plist`, using the `plutil` utility from the Terminal:

```plutil -insert 'CFBundleURLTypes' -xml '<array><dict> <key>CFBundleURLName</key> <string>myscheme</string> <key>CFBundleURLSchemes</key> <array><string>myscheme</string></array> </dict></array>' -- /path/to/YOUR.app/Contents/Info.plist```

Once that's done, and the app has the new `myscheme:` URL support (be sure your app was coded up to accept URLs via whatever GUI framework you are using.  On PyQt this would be QFileOpenEvent in your QApplication event() function).

Next, try and open up `myscheme:` style URLs:

1. From Terminal: `open myscheme:this_is_a_test?foo=bar`
2. From a browser: (in the location bar) `myscheme:this_is_a_test?foo=bar`

Your app should receive that URL from macOS (if you are using PyQt it comes in as a QFileOpenEvent). If the app wasn't started, it should be started and receive that URL.

However, that wasn't working previously.

But with this patch, everything works.  If the app wasn't started, the URL is appended to the sys.argv of the python script.  If the app was running, an AppleEvent is forwarded encapsulating the URL request.

Let me know if you have questions or if I can help test!

We would like very much to have this merged into pyinstaller for a future release so that our app can be built by anyone and work correctly! 

Thanks!

### CODE REVIEW

**Comment by cculianu** [comment]
FYI: The PR which attempted to fix this was #2219 but it wasn't working for other people either. (See the thread).

**Comment by cculianu** [comment]
Oh wow thanks so much for trying it out!  I'm glad!! :D  (note: my initial commit had [minor] bugs hopefully you tried the latest, which does indeed work as intended).

Thanks again.

Note to @htgoebel  -- the AppVeyor checks failed but I don't think that's related to my commits -- I suspect the extant dev branch is failing tests anyway regardless of these commits....

**Comment by waiting0729** [comment]
hi, I want use  this patch, but it does not work. I don't know where is a problem.
My steps：
1. git clone https://github.com/cculianu/pyinstaller.git and git checkout 
    fix_apple_open_document_events
2. clone/code/pyinstaller.py  -w --clean test.py
3. plutil -insert 'CFBundleURLTypes' -xml '<array><dict> <key>CFBundleURLName</key> <string>test</string> <key>CFBundleURLSchemes</key> <array><string>test</string></array> </dict></array>' -- /my/code/path/test/dist/test.app/Contents/Info.plist
4. my test.py code:
    print(str(sys.argv))
5. when i From a browser: (in the location bar) test:this_is_a_test?foo=bar, i find 'this_is_a_test?foo=bar' does not pass

**Comment by cculianu** [comment]
Step 3. there doesn't look like valid XML to me.  

> plutil -insert 'CFBundleURLTypes' -xml ' CFBundleURLName test CFBundleURLSchemes test ' -- /my/code/path/test/dist/test.app/Contents/Info.plist

You need to do something like this:

```
plutil -insert 'CFBundleURLTypes' -xml '<array><dict> <key>CFBundleURLName</key> <string>myscheme</string> <key>CFBundleURLSchemes</key> <array><string>myscheme</string></array> </dict></array>' -- /path/to/YOUR.app/Contents/Info.plist
```

**Comment by cculianu** [comment]
Also if it was valid XML but you pasted it wrong (XML tags conflict with github unless you put them in triple quotes) -- know that macOS is weird.  

**You have to run the app at least once for it to "register" its URL type.**  This is because it needs to have scanned the app's Info.plist and it doesn't do this for all .apps on the system as they spontaneously appear.  

So run it once, THEN quit it, then try the URL!

**Comment by MaWe2019** [comment]
Merge for next PyInstaller release!

**Comment by jhtitor** [comment]
This PR is invaluable for our software. Greatly appreciated! 

Merging into develop to get all the latest pyinstaller features seems to be working, e.g.

```
git clone https://github.com/pyinstaller/pyinstaller
cd pyinstaller
git remote add cculianu https://github.com/cculianu/pyinstaller
git checkout develop
git merge cculianu/fix_apple_open_document_events
pip3 install .
```

**Comment by cbenhagen** [comment]
@cculianu do you mind adding forwarding of the reopen (rapp) event to the child process? This would most likely fix https://github.com/pyinstaller/pyinstaller/issues/4234

**Comment by cculianu** [comment]
Ok, I will look at reproducing the issue #4234 and seeing about adding rapp

**Comment by cculianu** [comment]
However I am a bit backed up this week but will try to get to it

**Comment by cbenhagen** [comment]
@bjones1 is there a chance you could review this?

**Comment by cculianu** [comment]
@cbenhagen  I think i may get some time tomorrow or Wednesday to forward the event you requested.. hopefully!  So if he doesn't merge it before tomorrow (unlikely).. then we are good! :D

**Comment by cbenhagen** [comment]
@cculianu any news on this?

@bjones1 / @htgoebel what can I do to help get this merged?

**Comment by cculianu** [comment]
@cbenhagen  As far as news goes: Well it works.  Not much news other than that, really.  I hope some day it gets reviewed and merged since it's a useful addition.

**Comment by cculianu** [comment]
Oh.. yeah that event forwarding.  Yes, I may get time to work on that but motivation is low considering .. well, the chance it will get reviewed in the near future seems low based on the past. :)

**Comment by cculianu** [comment]
I can relate to the need for funding. I support several open source projects for free too.  My work on PyInstaller (I have at least 2 PRs pending) has entirely been in the support and interests of open source projects that I work on for free.. so.. I consider my time donated to those projects (as well as this one should you accept my PRs) as my contribution.

But I totally can relate to the need for funding.  Yours is a very critical piece of python infrastructure used by many projects and which works on different platforms for integration/packaging you do deserve the manpower needed to keep things working well.

Anyway -- I'll try and make time to revise this PR -- it's been a year so I don't quite have my dev env set up to work on PyInstaller.. and I need to make time to work on it.  But I will try and make time this weekend or next week.  Thanks so much for your comments.

**Comment by htgoebel** [comment]
@cculianu Re funding: Thanks for contributing your time :-) I'm looking forward for your updates.

**Comment by cbenhagen** [comment]
@htgoebel why has this been closed?

**Comment by MaWe2019** [comment]
@htgoebel: Same question here. Why did you close this?

**Comment by cculianu** [comment]
I've been using this patch for ~1 year now in my own project so.. I'm happy.  I wish I had time to perhaps pursue @htgoebel in merging this.  I have another PR extant that also I wasn't able to finish.

I consider this PR the "most ready" of the two... so.. I hope it makes it in someday.  On macOS if you want to support drag & drop you really do need this or something like it....

**Comment by jamesbcd** [comment]
Can this please be re-opened? It's really useful

**Comment by SamSchott** [comment]
Considering that using FSRef and `CFURLCreateFromFSRef` to handle file reference has been deprecated and triggers warnings when building or notarising an app, it would be nice to revisit this PR. 

See: https://developer.apple.com/documentation/corefoundation/1584385-cfurlcreatefromfsref?language=objc

**Comment by MaWe2019** [comment]
Another +1 for reopening this issue! It is indeed vital.

**Comment by BoboTiG** [comment]
@cculianu thanks a lot for your time on the subject. I am sorry this didn't make it at the time. But we have now more developers in the team and your patch is quite valuable for several users. Do you mind updating the changes based from the current `develop` branch and remove bootloader binaries?

We hopefully will get that work merged :)

FTR you could also add a NEWs entry:
```shell
echo "OSX: Make apps accept both drag/drop & URL events via ARGV EMU." > news/3822.bootloader.rst
```

**Comment by bwoodsend** [comment]
@htgoebel's requested changes are pretty straight forward so @cculianu (or anyone else who's keen for this feature) could:

- rebase it onto the development branch
- remove the bootloaders (we have to compile these ourselves for security reasons)
- add a changelog entry (and preferably a test or two)

Then we'll be good to go...

We're not quite so understaffed as we were when this was closed and we now have a couple of macOS developers who can review and test this properly (before we didn't have any). So the review process shouldn't be quite such a blocker.

I can't actually re-open this PR because we no longer have a `pyinstaller:bootloader-works` branch. So, unless you're able edit this PR to target our `develop` branch instead (which I'm not sure is even possible), you'll have to create a separate PR.

**Comment by bwoodsend** [comment]
@Legorooj Do you have sufficient repo-permissions to retarget this PR to the `develop` branch?

**Comment by cculianu** [comment]
@BoboTiG @bwoodsend Hi guys!  I will make time today to update this!!  

Just to humble brag (or perhaps brag brag): Note that I am already running my own custom patched PyInstaller that has been using this patch for going on 2 years now.  It's been deployed in over 10,000 different MacOS desktops for our application... it works with no issues.  It's vital for being able to have users click on links in their browser that then get forwarded to an instance of our already-running app.

I see it as a key feature.. so -- I will strike while the iron is hot and rebase this to current dev branch and also address the other recommendations.  I will make some time for it later today or tonight or at the very latest tomorrow (Friday).

**Comment by BoboTiG** [comment]
If you can manage to add a "simple" test, maybe based from https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_apple_events.py, it would be awesome and serve as a non-regression test. Quite important for such a feature IMO.
But do not block on it, I get it that this is not trivial to achieve ;)

**Comment by Legorooj** [comment]
Apologies this didn't get any attention before, please open a new PR with the changes, and it'll get dealt with promptly.

**Comment by cculianu** [comment]
Ok, PR opened here: #5276 . I marked it as WIP.  While the patch works and I was able to build an app that works as expected, I was not able to get the tests working.  I await further instruction from you guys about what my test is doing wrong.  You can see the new test in the PR.

**Comment by BoboTiG** [comment]
Great! It is late here, but promise I will have a look at the new PR tomorrow :)

**Pull request closed without merging**
