### PR TITLE
Hooks/XGBoost: add a hook for resolving XGBoost's binaries and hidden…

### PR DESCRIPTION
**Pull request by kjanko**
… imports

### CODE REVIEW

**Comment by kjanko** [comment]
Solves issue #4076

**Comment by mnboos** [comment]
Any updates?

**Comment by smarkh** [comment]
Has anyone taken a look at this for a while?

**Comment by Legorooj** [comment]
@kjanko please re-target this PR at https://github.com/pyinstaller/pyinstaller-hooks-contrib.

**Comment by wags1999** [comment]
@kjanko, any plans to re-target this to the https://github.com/pyinstaller/pyinstaller-hooks-contrib repo?  Otherwise I might create my own PR with your same content to allow xgboost to work with pyinstaller.

**Pull request closed without merging**
