### PR TITLE
Hook for wgpu

### PR DESCRIPTION
**Pull request by Korijn**
Contributing a new hook for WebGPU python wrapping project `wgpu`: https://github.com/almarklein/wgpu-py/

Resolves https://github.com/almarklein/wgpu-py/issues/25

See the linked thread for verification evidence

### CODE REVIEW

**Comment by Legorooj** [comment]
>; Need to test

You mean you haven't tested this?

**Comment by Korijn** [comment]
That was commit 1. I tested since, see here: https://github.com/almarklein/wgpu-py/issues/25#issuecomment-581890048

**Comment by Legorooj** [comment]
Ok, looks safe to merge @bjones1.

**Comment by bjones1** [comment]
Thanks for your contribution. Would you consider writing a test for this, to ensure that it continues to work as both PyInstaller and WGPU are updated? Here's an example test from https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py#L78:

``` Python
@importorskip('gevent')
def test_gevent(pyi_builder):
    pyi_builder.test_source(
        """
        import gevent
        gevent.spawn(lambda: x)
        """)
```

The heart of a test is to import something from WGPU then use it to show that it works. You mentioned a `triangle.py`, I think?

**Comment by Korijn** [comment]
@almarklein do you think `import wgpu.rs` would be enough to show that the binary was packaged? I don't also want to check that a compatible GPU is available, so we need to get the balance just right here.

**Comment by almarklein** [comment]
Yes, the library is currently loaded when the module is imported. I briefly considered that maybe we should add a tiny bit of public API so 3d party code (like here) can verify that the lib is loaded.

But it makes sense to load the lib on import as we do now. So yeah, let's go ahead an just test that `import wgpu.backend.rs` works. And add a comment in that module that if we ever do things differently, we should update the pyinstaller tests ;)

**Comment by bjones1** [comment]
@almarklein, would you be interested in integrating this hook directly into wgpu? When #4582 is merged, you can include hooks directly in wgpu, which brings a lot of benefits.

**Comment by almarklein** [comment]
Aye, that's interesting! I've always figured that such an approach scales much easier than collecting tons of hooks here :)  But perhaps I am overseeing some disadvantages? @korijn what are your thoughts?

**Comment by Korijn** [comment]
Yes, that's super convenient! We should definitely do that. Great to see this feature landing in PyInstaller!

**Comment by bjones1** [comment]
Great! Would you mind trying this out, then? I'd appreciate feedback in terms of how to docs are, the overall process, etc. Directions are at https://pyinstaller-sample-hook.readthedocs.io/en/latest/; they refer to the code at https://github.com/bjones1/hooksample/. I'll be happy to provide help/pointers.

**Comment by Korijn** [comment]
Alright, here we go:

https://github.com/almarklein/wgpu-py/pull/61

The tests are failing, and I don't totally understand why yet.

**Comment by Korijn** [comment]
Fixed it, CI passed on our end. :)

**Comment by htgoebel** [comment]
@bjones1 @Korijn Since you refered to #4582: Shall this one be merged? Or are you going to use the new hook-hooking ;-)

**Comment by Korijn** [comment]
We would notify you guys when we do a new release, since we are indeed using the new hook hooks :) so i think this can be closed (and not merged)?

**Comment by htgoebel** [comment]
Now the hook hooks are (almost) finished, I'm going to release PyInstaller 4.0 really soon now.

So I'm closing this pull-request - looking forward to have more package providing their own hooks.  Thanks for being to brae using this feature

**Comment by almarklein** [comment]
> We would notify you guys when we do a new release

Here is the notification; we just released a new version of wgpu-py!

**Comment by Legorooj** [comment]
@almarklein thanks for letting us know. This should work as of PyInstaller 4 (next release) because #4582 is on the feature list. (I'll let you know if there are any changes to the integration API)

**Pull request closed without merging**
