### PR TITLE
Detection of python library failing when using python from RedHat Software Collections

### PR DESCRIPTION
**Pull request by matlo607**
Issue with Pyinstaller 3.3.1
Easily reproducible with a docker [centos](https://hub.docker.com/_/centos/)
Python version 3.6, package **rh-python36-2.0-1** available in RHSCL repo.
`pyinstaller --onefile myapp.py`

I was using python 3.6 from RedHat Software Collections and got an issue while trying to generate a bundle for my application with the option `--onefile`
Python is installed in an unusual path and libraries have non-standard names: 
* /opt/rh/rh-python36/root/usr/bin/python
* /opt/rh/rh-python36/root/usr/lib64
* /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so
* /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0
* /opt/rh/rh-python36/root/usr/lib64/libpython3.so.rh-python36

I managed to make the packaging to work with the `--onefile` option. I tried to make the fix as general as possible so that all python versions from RHSCL will now be detected correctly. However I think it needs to be reworked.
What would you advise to fix the detection at [PyInstaller/depend/bindepend.py#L757](https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/PyInstaller/depend/bindepend.py#L757) and  [PyInstaller/building/build_main.py#L606](https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/PyInstaller/building/build_main.py#L606) ?

### CODE REVIEW

**Comment by htgoebel** [comment]
> Issue with Pyinstaller 3.3.1

Please try with current development head, there has bee a minor change in this area lately.

What does
```
$ /opt/rh/rh-python36/root/usr/bin/python
>>> import importlib.machinery
>>> importlib.machinery.EXTENSION_SUFFIXES
```
return on your plattform?

**Comment by matlo607** [comment]
I tried with the branch `develop` and experienced the same issue:
```
175 INFO: PyInstaller: 3.4.dev0+gd4cc9fe
175 INFO: Python: 3.6.3
176 INFO: Platform: Linux-4.13.0-41-generic-x86_64-with-centos-7.4.1708-Core
176 INFO: wrote /project/test.spec
177 INFO: UPX is not available.
179 INFO: Extending PYTHONPATH with paths
['/project', '/project']
179 INFO: checking Analysis
179 INFO: Building Analysis because Analysis-00.toc is non existent
179 INFO: Initializing module dependency graph...
180 INFO: Initializing module graph hooks...
181 INFO: Analyzing base_library.zip ...
3257 INFO: running Analysis Analysis-00.toc
3268 INFO: Caching module hooks...
3273 INFO: Analyzing /project/test.py
3277 INFO: Loading module hooks...
3278 INFO: Loading module hook "hook-encodings.py"...
3346 INFO: Loading module hook "hook-xml.py"...
3592 INFO: Loading module hook "hook-pydoc.py"...
3604 INFO: Looking for ctypes DLLs
3604 INFO: Analyzing run-time hooks ...
3612 INFO: Looking for dynamic libraries
3974 INFO: Looking for eggs
3974 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "./pyinstaller/pyinstaller.py", line 15, in <module>
    run()
  File "/project/pyinstaller/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/project/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/project/pyinstaller/PyInstaller/building/build_main.py", line 814, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/project/pyinstaller/PyInstaller/building/build_main.py", line 760, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/project/pyinstaller/PyInstaller/building/build_main.py", line 237, in __init__
    self.__postinit__()
  File "/project/pyinstaller/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/project/pyinstaller/PyInstaller/building/build_main.py", line 569, in assemble
    self._check_python_library(self.binaries)
  File "/project/pyinstaller/PyInstaller/building/build_main.py", line 652, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.6mu.so.1.0, libpython3.6m.so.1.0, libpython3.6.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

```
>>> import importlib.machinery
>>> importlib.machinery.EXTENSION_SUFFIXES
['.cpython-36m-x86_64-linux-gnu.so', '.abi3.so', '.so']
```

**Comment by matlo607** [comment]
You will be able to reproduce the issue using this Dockerfile:
```bash
FROM centos:latest

RUN yum repolist all \
 && yum install -y "centos-release-scl-rh" "git" \
 && yum install -y "rh-python36-python"

ENV PATH "/opt/rh/rh-python36/root/usr/bin${PATH:+:${PATH}}" \
    LD_LIBRARY_PATH "/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    MANPATH "/opt/rh/rh-python36/root/usr/share/man:$MANPATH" \
    PKG_CONFIG_PATH "/opt/rh/rh-python36/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}" \
    XDG_DATA_DIRS "/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" \

WORKDIR project
RUN echo -e "#!/usr/bin/env python\nprint(\"Hello world!\")" > test.py \
 && chmod +x test.py

#RUN pip install pyinstaller
#CMD ["pyinstaller", "test.py"]

RUN git clone "https://github.com/pyinstaller/pyinstaller.git" \
  && cd pyinstaller && pip install -r requirements.txt && cd -
CMD ["./pyinstaller/pyinstaller.py", "test.py"]
```
```bash
docker build -t pyinstaller:testing .
docker run -it pyinstaller:testing
```

**Comment by matysek** [comment]
@matlo607 python from software collections should be run like this: ```scl enable rh-python36 "python --version"``` and this way you should run pyinstaller to build your app. See this simplified docker file:
```
FROM centos:latest

RUN yum repolist all \
 && yum install -y "centos-release-scl-rh" "git" \
 && yum install -y "rh-python36-python"

WORKDIR project
RUN echo -e "#!/usr/bin/env python\nprint(\"Hello world!\")" > test.py \
 && chmod +x test.py

RUN git clone "https://github.com/pyinstaller/pyinstaller.git" \
  && cd pyinstaller && scl enable rh-python36 "pip install -r requirements.txt" && cd -
CMD ["scl", "enable", "rh-python36", "./pyinstaller/pyinstaller.py test.py"]
```

**Comment by matysek** [comment]
Python from software collection uses this filename for python library: libpython3.6m.so.rh-python36-1.0
```
# ldd /opt/rh/rh-python36/root/bin/python3.6
	linux-vdso.so.1 =>  (0x00007ffd771f1000)
	libpython3.6m.so.rh-python36-1.0 => /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0 (0x00007fcf83196000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcf82f6b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fcf82d67000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fcf82b64000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcf82861000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcf824a0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcf836bd000)
```

**Comment by matysek** [comment]
@matlo607 to finish this, only the PYDYLIB_NAMES should be updated to match the SO name ```libpython3.6m.so.rh-python36-1.0``` and create pyinstaller recipe and describe how to run pyinstaller with software collections (to use command like ```scl enable rh-python36 "python pyinstaller.py myapp.py"```

**Comment by matlo607** [comment]
@matysek, actually it is not mandatory to run softwares from software collections with `scl enable ...`
scl just sources the file `/opt/rh/rh-python36/enable` and if you have a look to it, you can see that is the same variables I set in my environment.
```bash
cat /opt/rh/rh-python36/enable 
export PATH=/opt/rh/rh-python36/root/usr/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/rh/rh-python36/root/usr/share/man:$MANPATH
export PKG_CONFIG_PATH=/opt/rh/rh-python36/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
export XDG_DATA_DIRS="/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
```

**Comment by matlo607** [comment]
Hello @htgoebel , @matysek,
The failures on CIs are not related at all to my change.
Please could you review this PR ?

**Comment by matlo607** [comment]
Hello @htgoebel , @matysek,
Could you please review this PR ?

**Comment by matlo607** [comment]
Hello @htgoebel , @matysek,
Could you please review this PR ?

**Comment by htgoebel** [comment]
Sorry for not coming back in this earlier. I'm quite busy in my day-job.

There is now a similar pull-request #3881 using a different pattern. Can you explain why your pattern is different?

**Comment by htgoebel** [comment]
Beside this question: For me to merge this, please reword the **commit messages** to comply to our [Commit Message Rules](https://pyinstaller.readthedocs.io/en/latest/development/commit-messages.html#commit-messages). 

You also need to submit a [**changelog entry**](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change. (This is a new requirement since last September to speed up releasing.)

**Comment by matlo607** [comment]
> Sorry for not coming back in this earlier. I'm quite busy in my day-job.
> 
> There is now a similar pull-request #3881 using a different pattern. Can you explain why your pattern is different?

Hello @htgoebel,
Here below is the content of `/opt/rh/rh-python36/root/lib64`:
```
# ls -l
total 3092
dr-xr-xr-x  2 conan root       6 May 31  2017 games
lrwxrwxrwx  1 conan root      32 Jan 29  2018 libpython3.6m.so -> libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x  1 conan root 3144624 Oct  6  2017 libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x  1 conan root    6696 Oct  6  2017 libpython3.so.rh-python36
drwxr-xr-x  2 conan root      84 Jan 29  2018 pkgconfig
dr-xr-xr-x  5 conan root      52 Jan 29  2018 pm-utils
drwxr-xr-x 33 conan root    8192 Jan 29  2018 python3.6
dr-xr-xr-x  2 conan root       6 May 31  2017 sse2
dr-xr-xr-x  2 conan root       6 May 31  2017 tls
dr-xr-xr-x  2 conan root       6 May 31  2017 X11
```
The pattern used in #3881 matches the symbolic link `libpython3.6m.so -> libpython3.6m.so.rh-python36-1.0`. If this approach works, it could be better than mine since it seems more generic (without `rh-python36-1.0` suffix).

**Comment by htgoebel** [comment]
Thanks for investigating this. I'm closing this pull-reqeust in favor of #3881 and added a thanks to you to the commit.message.

Duplicate of #3881.

**Pull request closed without merging**
