### PR TITLE
Feature: Add Python 3.9 support.

### PR DESCRIPTION
**Pull request by BoboTiG**
Ready for review :)

### CODE REVIEW

**Comment by BoboTiG** [comment]
The SciPy issue will be fixed in a couple PC days, they are working on Python 3.9 wheels. I will wait for it before continuing.

**Comment by BoboTiG** [comment]
Cool, SciPy wheels for 3.9 are out. I will work on that PR tomorrow :)

**Comment by BoboTiG** [comment]
@Legorooj good for the review (tests are all passing on 3.9 🍾).

**Review by Legorooj — APPROVED** [review]
I can't see anything wrong here, good job! CC @bwoodsend @rokm

**Review by rokm — APPROVED** [review]
Looks good to me.

**Review by bwoodsend — APPROVED** [review]

**Review by Legorooj — APPROVED** [review]

**Pull request merged**
