### PR TITLE
minor changes to codebase to aid operation with Django 4.x

### LINKED ISSUE #7258: Fixes for use of pyinstaller with Django 4.x and custom management commands.
PROBLEM:
This feature aims to solve the problem of the custom app level management commands being missed out from hidden imports alongside issues with imports of apps listed within INSTALLED_APPS failing due to erroneous execution of 'eval_script' function. Specifically when the hidden imports of the INSTALLED_APPS are evaluated the logging outputs generated by 'collect_submodules' when called in django_import_finder.py are captured in the STDOUT regardless of the --log-level. Also any additional management commands provided by one of the INSTALLED_APPS are ignored as the 'get_commands' function has a hardcoded referenced to Django 1.8 command set. Django's currently implementation of command collection will not complain of missing commands at runtime thereby rendering the patch of this function that is currently implemented irrelevant.

SOLUTION:
The solution to this issue is to remove several redundant parts of the code alongside adding additional overrides for decluttering STDOUT. 

The following is a list of measures taken to resolve the problem
-  remove the monkey patching of Django's 'get_commands' method in pyi_rth_django.py
- modify the collect static code to have a boolean input parameter 'log' which when the relevant calls to logging within this function are wrapped in a conditional will serve to prevent logs being inappropriately raised.

### PR DESCRIPTION
**Pull request by Rumbelows**
addition of override parameter to switch off logging in 'collect submodues' aswell as removal of redundant django hooks

Closes #7258.

### CODE REVIEW

**Comment by rokm** [comment]
Preliminary feedback: please avoid stylistic changes, including
- added whitespace in copyright header block (I'd like to keep them the same across the whole codebase)
- replacing single quotes with double quotes for strings
- other stylistic changes that seem to trip up the `yapf` formatter check

This will reduce the amount of unnecessary changes and make it easier to review the actual changes.

**Comment by bwoodsend** [comment]
Like Rok says, please revert the style changes. If every contributor brings their own personal code style then the codebase becomes a free for all. Let yapf deal with whitespace and line wrapping and leave the rest alone.

**Comment by Rumbelows** [comment]
All style changes introduced from my local interpreter have now been reverted

**Comment by rokm** [comment]
The first part, i.e., removal of `django.core.management.get_commands`  override looks reasonable to me. In the past, the dynamically-built list of commands was probably not built correctly in the frozen application, and therefore a static override was provided. This override does not seem necessary anymore; we get the command list even without it (and it is up-to date, i.e., matches the list from the unfrozen version).

---

The second part, addition of `log` argument to `collect_submodules` looks problematic to me. The messages put under this parameter are already all `logger.debug() `, so they should not be displayed unless PyInstaller is ran with `--log-level DEBUG` is used. 

In #7258 you wrote that 
> Specifically when the hidden imports of the INSTALLED_APPS are evaluated the logging outputs generated by 'collect_submodules' when called in django_import_finder.py are captured in the STDOUT regardless of the --log-level

Can you show us an example log with such messages, so we can see what you are trying to address with this change? 

We did have an issue with `--log-level` setting not being properly propagated into subprocesses (#7231) that was fixed by #7235. Can you check if this makes any difference (it has not been released yet, so you need to install PyInstaller from `develop`). But even if the setting was not propagated, the default is INFO, so debug messages should not be displayed.

On the other hand, there are some `logger.info()` calls in `PyInstaller/hooks/hook-django.py` that probably do not honor the `--log-level WARN` setting due to using separate logger instance (which I suspect does not connect to PyInstaller's logger hierarchy, due to run-time name not fitting under PyInstaller.* hierarchy).

So all in all, if the debug messages from `collect_submodules` are really a problem, I think this change is just masking an issue that should otherwise be investigated and resolved.

**Comment by Rumbelows** [comment]
Having run my code (an attempt to compile a simple django project) with the latest develop branch code I still see this output:  2022-11-21 20:19:50,381::DEBUG::PyInstaller.utils.hooks::collect_submodules::650::Collecting submodules for django.contrib.contenttypes.templatetags suggesting that the subprocess is still not respecting the --log-level

**Comment by rokm** [comment]
> Having run my code (an attempt to compile a simple django project) with the latest develop branch code I still see this output: 2022-11-21 20:19:50,381::DEBUG::PyInstaller.utils.hooks::collect_submodules::650::Collecting submodules for django.contrib.contenttypes.templatetags suggesting that the subprocess is still not respecting the --log-level

That looks like a custom log format. Are you running PyInstaller from command-line or some IDE that overrides the log format (and possibly also log level)?

**Comment by Rumbelows** [comment]
> > Having run my code (an attempt to compile a simple django project) with the latest develop branch code I still see this output: 2022-11-21 20:19:50,381::DEBUG::PyInstaller.utils.hooks::collect_submodules::650::Collecting submodules for django.contrib.contenttypes.templatetags suggesting that the subprocess is still not respecting the --log-level
> 
> That looks like a custom log format. Are you running PyInstaller from command-line or some IDE that overrides the log format (and possibly also log level)?
I am running from a command line in vscode. I am not too familiar with the logging module. where would this override likely originate?

**Comment by rokm** [comment]
Are you seeing DEBUG messages only from `collect_submodules`, or also from other parts of PyInstaller?

**Comment by Rumbelows** [comment]
> Are you seeing DEBUG messages only from `collect_submodules`, or also from other parts of PyInstaller?

I am also seeing INFO messages from hook-django with --log-level set to CRITICAL

**Comment by Rumbelows** [comment]
The issue with the logging in hook-django has been resolved by switching 'from PyInstaller import log as logging' to 'from PyInstaller.utils.hooks import logger' to access the log the same way as other hooks appear to do so. perhaps this is a separate more robust instance

**Comment by rokm** [comment]
> The issue with the logging in hook-django has been resolved by switching 'from PyInstaller import log as logging' to 'from PyInstaller.utils.hooks import logger' to access the log the same way as other hooks appear to do so. perhaps this is a separate more robust instance

Yes, switching to `PyInstaller.utils.hooks.logger` in hook-django should fix the problems with messages from there.

**Comment by Rumbelows** [comment]
> > The issue with the logging in hook-django has been resolved by switching 'from PyInstaller import log as logging' to 'from PyInstaller.utils.hooks import logger' to access the log the same way as other hooks appear to do so. perhaps this is a separate more robust instance
> 
> Yes, switching to `PyInstaller.utils.hooks.logger` in hook-django should fix the problems with messages from there.

The issue however still persists when the logger is referenced in the subprocess (django_import_finder.py)

**Comment by rokm** [comment]
Can you try outside of the vscode, just to make sure?

**Comment by rokm** [comment]
Because with default log-level, I get log like this on Windows (and similar on linux as well):

<details><summary>build log</summary><p>

``` 
(venv) C:\Users\Rok\Development\pyi-django\mysite>pyinstaller --clean --noconfirm manage.py
675 INFO: PyInstaller: 5.6.2
675 INFO: Python: 3.10.8
695 INFO: Platform: Windows-10-10.0.19045-SP0
695 INFO: wrote C:\Users\Rok\Development\pyi-django\mysite\manage.spec
695 INFO: UPX is not available.
714 INFO: Removing temporary files and cleaning cache in C:\Users\Rok\AppData\Local\pyinstaller
714 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Rok\\Development\\pyi-django\\mysite']
1391 INFO: checking Analysis
1391 INFO: Building Analysis because Analysis-00.toc is non existent
1391 INFO: Initializing module dependency graph...
1391 INFO: Caching module graph hooks...
1450 INFO: Analyzing base_library.zip ...
4897 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
5055 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
8206 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
11444 INFO: Caching module dependency graph...
11605 INFO: running Analysis Analysis-00.toc
11623 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\Users\Rok\AppData\Local\Programs\Python\Python310\python.exe
11713 INFO: Analyzing C:\Users\Rok\Development\pyi-django\mysite\manage.py
11732 INFO: Loading module hook 'hook-django.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
804 WARNING: Failed to collect submodules for 'django.contrib.postgres.forms' because importing 'django.contrib.postgres.forms' raised: ModuleNotFoundError: No module named 'psycopg2'
19626 INFO: Determining a mapping of distributions to packages...
21385 INFO: Packages required by django:
['asgiref', 'sqlparse', 'tzdata']
21385 INFO: Django root directory C:\Users\Rok\Development\pyi-django\mysite\mysite
42698 INFO: Collecting Django migration scripts.
43341 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
43458 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
44567 INFO: Loading module hook 'hook-zoneinfo.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
44593 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
45154 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
45636 INFO: Loading module hook 'hook-django.core.cache.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
46459 INFO: Loading module hook 'hook-django.core.mail.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
46529 INFO: Loading module hook 'hook-django.core.management.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
47330 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
47577 INFO: Loading module hook 'hook-django.db.backends.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
48797 INFO: Processing module hooks...
49958 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
50737 INFO: Loading module hook 'hook-django.db.backends.mysql.base.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
50878 INFO: Loading module hook 'hook-django.db.backends.oracle.base.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
51042 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
51570 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
54552 INFO: Loading module hook 'hook-django.contrib.sessions.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
55852 INFO: Loading module hook 'hook-django.template.loaders.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
56931 WARNING: Hidden import "django.contrib.messages.templatetags" not found!
56931 WARNING: Hidden import "django.contrib.contenttypes.templatetags" not found!
56946 WARNING: Hidden import "django.contrib.sessions.templatetags" not found!
56946 WARNING: Hidden import "django.contrib.contenttypes.context_processors" not found!
56946 WARNING: Hidden import "django.contrib.staticfiles.templatetags" not found!
56946 WARNING: Hidden import "django.contrib.sessions.context_processors" not found!
56962 WARNING: Hidden import "django.contrib.auth.templatetags" not found!
56962 WARNING: Hidden import "django.contrib.staticfiles.context_processors" not found!
56962 WARNING: Hidden import "django.contrib.admin.context_processors" not found!
56993 INFO: Loading module hook 'hook-tzdata.py' from 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
58118 WARNING: Hidden import "django.db.backends.oracle.compiler" not found!
58196 INFO: Looking for ctypes DLLs
58227 INFO: Analyzing run-time hooks ...
58242 INFO: Including run-time hook 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
58243 INFO: Including run-time hook 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
58258 INFO: Including run-time hook 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
58258 INFO: Including run-time hook 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_django.py'
58274 INFO: Including run-time hook 'C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
58305 INFO: Looking for dynamic libraries
905 INFO: Extra DLL search directories (AddDllDirectory): []
906 INFO: Extra DLL search directories (PATH): ['C:\\Users\\Rok\\Development\\pyi-django\\venv\\Scripts', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\dotnet\\', 'C:\\Users\\Rok\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Rok\\.dotnet\\tools']
59838 INFO: Looking for eggs
59838 INFO: Using Python library c:\Users\Rok\AppData\Local\Programs\Python\Python310\python310.dll
59838 INFO: Found binding redirects:
[]
59853 INFO: Warnings written to C:\Users\Rok\Development\pyi-django\mysite\build\manage\warn-manage.txt
60010 INFO: Graph cross-reference written to C:\Users\Rok\Development\pyi-django\mysite\build\manage\xref-manage.html
60228 INFO: checking PYZ
60228 INFO: Building PYZ because PYZ-00.toc is non existent
60228 INFO: Building PYZ (ZlibArchive) C:\Users\Rok\Development\pyi-django\mysite\build\manage\PYZ-00.pyz
61198 INFO: Building PYZ (ZlibArchive) C:\Users\Rok\Development\pyi-django\mysite\build\manage\PYZ-00.pyz completed successfully.
61244 INFO: checking PKG
61244 INFO: Building PKG because PKG-00.toc is non existent
61244 INFO: Building PKG (CArchive) manage.pkg
61276 INFO: Building PKG (CArchive) manage.pkg completed successfully.
61276 INFO: Bootloader C:\Users\Rok\Development\pyi-django\venv\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
61276 INFO: checking EXE
61276 INFO: Building EXE because EXE-00.toc is non existent
61290 INFO: Building EXE from EXE-00.toc
61291 INFO: Copying bootloader EXE to C:\Users\Rok\Development\pyi-django\mysite\build\manage\manage.exe.notanexecutable
61432 INFO: Copying icon to EXE
61445 INFO: Copying icons from ['C:\\Users\\Rok\\Development\\pyi-django\\venv\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
61510 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
61510 INFO: Writing RT_ICON 1 resource with 3752 bytes
61510 INFO: Writing RT_ICON 2 resource with 2216 bytes
61510 INFO: Writing RT_ICON 3 resource with 1384 bytes
61510 INFO: Writing RT_ICON 4 resource with 37019 bytes
61510 INFO: Writing RT_ICON 5 resource with 9640 bytes
61510 INFO: Writing RT_ICON 6 resource with 4264 bytes
61510 INFO: Writing RT_ICON 7 resource with 1128 bytes
61525 INFO: Copying 0 resources to EXE
61525 INFO: Embedding manifest in EXE
61525 INFO: Updating manifest in C:\Users\Rok\Development\pyi-django\mysite\build\manage\manage.exe.notanexecutable
61603 INFO: Updating resource type 24 name 1 language 0
61603 INFO: Appending PKG archive to EXE
61616 INFO: Fixing EXE headers
62057 INFO: Building EXE from EXE-00.toc completed successfully.
62072 INFO: checking COLLECT
62072 INFO: Building COLLECT because COLLECT-00.toc is non existent
62072 INFO: Building COLLECT COLLECT-00.toc
89004 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

</p></details>

So only INFO and WARNING, as expected.

**Comment by Rumbelows** [comment]
I have now run the build in the command line outside of vscode and im still getting this error:

> (venv) D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE>pyinstaller .\manage.spec --log-level CRITICAL
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File ".\manage.spec", line 7, in <module>
    a = Analysis(
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\building\build_main.py", line 410, in __init__
    self.__postinit__()
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\building\build_main.py", line 579, in assemble
    self.graph.process_post_graph_hooks(self)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 329, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 447, in post_graph
    self._load_hook_module(keep_module_ref=True)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 387, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\compat.py", line 609, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\hooks\hook-django.py", line 31, in <module>
    settings_py_imports = django.django_dottedstring_imports(root_dir)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\utils\hooks\django.py", line 35, in django_dottedstring_imports
    ret = eval_script('django_import_finder.py', env=env)
  File "D:\Pycharm projects\MY-PACKAGE-DEV\MY-PACKAGE\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 181, in eval_script
    return eval(txt)
  File "<string>", line 1
    2022-11-21 20:34:54,478::DEBUG::PyInstaller.utils.hooks::collect_submodules::650::Collecting submodules for django.contrib.contenttypes.templatetags
               ^
SyntaxError: invalid syntax

**Comment by rokm** [comment]
Hmm... this means that whatever is overriding your logger configuration (the format), it is also causing log messages to be written to stdout instead of default stderr, polluting the expected stdout.

**Comment by Rumbelows** [comment]
> Hmm... this means that whatever is overriding your logger configuration (the format), it is also causing log messages to be written to stdout instead of default stderr, polluting the expected stdout.

Thanks, i will look into this.

**Comment by rokm** [comment]
One more thing to check - if you set up just the basic django project with `django-admin startproject mysite `and freeze its manage.py script, do you observe the same behavior?

**Comment by rokm** [comment]
I suppose it could be that your project is using some logging framework or something that overrides the logger configuration... and since that helper script probably ends up loading the project's configuration, it might end up with altered logger state.

**Comment by rokm** [comment]
Either way, I suspect this is a good opportunity to port `eval_script('django_import_finder.py', env=env)`to the new `isolated` framework and limit the effect of stdout-related problems like this one.

**Comment by Rumbelows** [comment]
Yes i think we've gotten to the root cause of the issue. part of my dependecy structure was overwriting the log module output stream. I have since pointed it back to stderr. I will modify this pr to just include the removal of the get_commands patch.

**Review by rokm — APPROVED** [review]

**Review by bwoodsend — CHANGES_REQUESTED** [review]
I you run:
```
pip install yapf
yapf -rip .
```
then that will appease the linter.

**Review by bwoodsend — APPROVED** [review]

**Pull request merged**
