### PR TITLE
Add assertion message to imphook.py assert statement

### LINKED ISSUE #4626: PyInstaller 3.6 AssertionError
Hi, since the latest 3.6 release all my Linux builds are failing with a new `AssertionError`.
This is the log:
```
23 INFO: PyInstaller: 3.6
24 INFO: Python: 2.7.16
25 INFO: Platform: Linux-4.9.184-linuxkit-x86_64-with-debian-squeeze-sid
26 INFO: wrote /simulator.spec
35 INFO: UPX is not available.
36 INFO: Removing temporary files and cleaning cache in /.cache/pyinstaller
37 INFO: Extending PYTHONPATH with paths
['/agent/project/src/bin', '/']
37 INFO: checking Analysis
37 INFO: Building Analysis because Analysis-00.toc is non existent
38 INFO: Initializing module dependency graph...
49 INFO: Caching module graph hooks...
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "/simulator.spec", line 17, in <module>
    noarchive=False)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/building/build_main.py", line 343, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 734, in initialize_modgraph
    user_hook_dirs=user_hook_dirs,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 116, in __init__
    self._reset(user_hook_dirs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 134, in _reset
    self._hooks = self._cache_hooks("")
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/analysis.py", line 215, in _cache_hooks
    return ModuleHookCache(self, hook_dirs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/imphook.py", line 100, in __init__
    self._cache_hook_dirs(hook_dirs)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/imphook.py", line 133, in _cache_hook_dirs
    hook_module_name_prefix=self._hook_module_name_prefix,
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/imphook.py", line 289, in __init__
    assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError
```

PyInstaller: 3.6
OS: Linux & macOS
Python: 2.7

After reverting to version 3.5 it seems to work fine, what can I do to try to find the source of this issue?

### PR DESCRIPTION
**Pull request by Legorooj**
Added an assertion message to allow users to remove custom hooks that conflict with pyinstaller ones.

Closes #4626

### CODE REVIEW

**Comment by Legorooj** [comment]
Added changelog entry, and fixed line length. Also fixed the commit message (its added the commit twice?), but I'm quite new to Git CLI - I used to use github desktop, but I've recently decided that the CLI is better.

**Comment by Legorooj** [comment]
@bjones1 This should be complete;

- [x] Commit messages
- [x] Lint line length - Also fixed the first failure, linked in last commit
- [x] Changelog entry

**Comment by Legorooj** [comment]
K the last commit broke something. Let me see...

**Comment by bjones1** [comment]
Would you:

- Squash these commits, then use the appropriate https://pyinstaller.readthedocs.io/en/stable/development/commit-messages.html#standard-prefixes?
- Remove the changes to `.gitgnore`
- Changes the news file to reference issue 4626, which this closes?

**Comment by Legorooj** [comment]
@bjones1 I can't remove the gitignore or it adds my virtual environment. The rest I'll do today.

**Comment by Legorooj** [comment]
This is superceded by #4698 with the changes you requested @bjones1

**Pull request closed without merging**
