### PR TITLE
Write additional bitfield for Python 3.7 and later.

### PR DESCRIPTION
**Pull request by TobiasRzepka**
Current implementation of PEP552 was only valid for Python 3.7.
By the way I've replaced the helper function _write_long with standard Python lib calls.

### CODE REVIEW

**Comment by htgoebel** [comment]
Thanks for the pull-request, but I'm afraid it does not change anything, see [the definition of is_py37](https://github.com/pyinstaller/pyinstaller/blob/9a74f7d5522c6d4678b9/PyInstaller/compat.py#L34).

If you want to provide this as as cleanup, please keep the old `if not is_py37`-structure as I consider it easier to understand. And of course the commit-message need to be changed.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

**Comment by htgoebel** [comment]
@TobiasRzepka Are you going to revise your pul-request? Othersie I'll close it

**Comment by TobiasRzepka** [comment]
Please leave it open. I'll make a rebase shortly.

**Comment by htgoebel** [comment]
Pinging

**Pull request merged**
