### PR TITLE
Tests: add verbose output.

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by htgoebel** [comment]
"Add" to what? IMO this should read like "Run created executables with --verbose option." But why would you want to to this? I'm not aware of any test-case evaluation such an option.

**Comment by xoviat** [comment]
The reason for this is that the trace messages are not output during the test suite. If we're going to have a trace function, then we should be able to use it.

**Comment by codewarrior0** [comment]
Have you even tested this change? Because AFAIK it does nothing. The exes built by the test suite do not respond to the `-v` argument.

**Comment by xoviat** [comment]
Sorry but I couldn't make this work.

**Pull request closed without merging**
