### PR TITLE
Update Qt hooks

### LINKED ISSUE #6483: PyQt5 produces binaries without Wayland support [Has Workaround]
## Description of the issue

When you create a PyQt5 application, the Wayland Qt plugins are not included, so only Xorg is supported. If you do not force wayland to be ignored (unset `WAYLAND_DISPLAY` or set `QT_QPA_PLATFORM=xcb`), you get:

```
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: ()
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
```

These are the missing binaries, if you install PyQt5 in a venv in `$(VENVDIR)`, include:

```
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-shell-integration/*:PyQt5/Qt/plugins/wayland-shell-integration
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-graphics-integration-client/*:PyQt5/Qt/plugins/wayland-graphics-integration-client
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-decoration-client/*:PyQt5/Qt/plugins/wayland-decoration-client 
```

This adds about 1MB of shared objects, it's worth to include.

I guess this can be fixed by changing the hook code, to include these new plugins. Maybe here:

https://github.com/pyinstaller/pyinstaller/blob/9cca9cb613f3824ac3035ed99a366a66e1dfb633/PyInstaller/utils/hooks/qt.py#L379

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: `3.8.12`
* Platform: Arch Linux
* How you installed Python: Arch Linux repositories

### LINKED ISSUE #6489: Qt6 missing Multimedia hooks
## Description of the issue
Qt reintroduced the Multimedia module in Qt 6.2, pyinstaller is currently missing a hook to support this.
At least for PySide6, including `QtMultimedia` and `QtMultimediaWidgets` as qt6 dependencies in the hook works

### PR DESCRIPTION
**Pull request by rokm**
Add hooks for `PySide6.QtMultimedia` and `PyQt6.QtMultimedia`. Fixes #6489.

Collect `QtWayland` plugins to enable Wayland support. Fixes #6483.

Relatively minor clean-up of the Qt5 dynamic dependencies dictionary (removed and fixed couple of items and comments, and alphabetically sorted the items).

### CODE REVIEW

**Comment by Numerlor** [comment]
Building a PySide6 QtMultimedia app with the true_property PySide6 feature causes the following error:
```
Fatal Python error: failed to create a new feature set!
Python runtime state: initialized
Traceback (most recent call last):
  File "shibokensupport/signature/loader.py", line 70, in pyside_type_init
  File "shibokensupport/signature/parser.py", line 491, in pyside_type_init
  File "shibokensupport/signature/mapping.py", line 208, in update
  File "shibokensupport/signature/mapping.py", line 617, in init_PySide6_QtMultimedia
ModuleNotFoundError: No module named 'PySide6.QtMultimediaWidgets'

The above exception was the direct cause of the following exception:

SystemError: <class 'PySide6.QtCore.PyClassProperty'> returned a result with an error set

Current thread 0x00004300 (most recent call first):
  File "file.py", line 5 in <module>
```
where file.py is
```py
from PySide6 import QtCore, QtMultimedia

from __feature__ import true_property

QtCore.QCoreApplication()
  ```
The QtMultiMedia widgets should be included as mentioned in #6489.  I'm not exactly sure how and when pyside tries to import the module, as the error does not show itself without the feature import, even though it looks like the same loader should be executed

**Comment by rokm** [comment]
@Numerlor Thanks for the feedback! I see the same problem occurs also occurs with `PySide2` when `true_property` is imported.

**Comment by rokm** [comment]
So the error happens [here (PySide2)](https://github.com/qtproject/pyside-pyside-setup/blob/9282e03de471bb3772c8d3997159e49c113d7678/sources/shiboken2/shibokenmodule/files.dir/shibokensupport/signature/mapping.py#L577-L586) or [here (PySide6)](https://github.com/qtproject/pyside-pyside-setup/blob/bd0e0bdec184ae9f8e82a2c5e5101faf9be1db83/sources/shiboken6/shibokenmodule/files.dir/shibokensupport/signature/mapping.py#L616-L629). 

The initialization of type mappings for `QtMultimedia` seems to trigger `QtMultimediaWidgets` import in both `PySide2` and `PySide6`, which is rather unfortunate, because there's probably no real reason for `QtMultimedia` depending on `QtMultimediaWidgets`. The PySide6 code seems to try handling the exception, but it should probably be catching `Exception` instead of `SystemError` in order to handle `ModuleNotFoundError`...

Questionable design choices on part of Qt/PySide aside, we'll have to handle this by adding a hiddenimport to PySide{2,6}.QtMultimedia hook, and also adding PySide{2,6}.QtMultimediaWidgets hooks due to emulated top-down dependency (e.g., to properly pick up QtWidgets & other dependencies)...

**Review by bwoodsend — APPROVED** [review]

**Review by Numerlor — APPROVED** [review]

**Comment by rokm** [comment]
Backport to `v4` pending the test results in my fork (merge conflicts...).

**Pull request merged**
