### PR TITLE
tests/ci: rerun failures

### PR DESCRIPTION
**Pull request by xoviat**
This may cut down on the flakiness.

### CODE REVIEW

**Comment by xoviat** [comment]
@bwoodsend this appears to work: https://github.com/pyinstaller/pyinstaller/runs/2309524543?check_suite_focus=true#step:10:1045

**Comment by xoviat** [comment]
Hopefully, no more CI issues after this.

**Comment by bwoodsend** [comment]
@xoviat Turn this back into a non-draft once CI is happy... Just so that we know not to review yet.

**Comment by xoviat** [comment]
This should work. It involves patches to xdist and rerunfailures to rerun even tests that crash the node (which happens with timeouts on windows). However, the patch is currently less-than-ideal because it uses a log-file in the current directory to record test failures; an ugly solution. I'll be able to upstream these patches provided I get assistance from pytest-dev, but they seem to be busy.

**Comment by bwoodsend** [comment]
Ooh wow. It worked out in the end. I'm rerunning CI again just to be sure. If it passes then it definitely gets my approval.

**Pull request merged**
