### PR TITLE
add badges to README

### PR DESCRIPTION
**Pull request by Legorooj**

### CODE REVIEW

**Comment by rokm** [comment]
Sure, why not. As long as there's no badge that shows our CI failing :) (I assume docs|passing is referring to docs build passing?)

**Review by rokm — APPROVED** [review]

**Comment by Legorooj** [comment]
@rokm :P and yes, docs|passing refers to `stable` docs being currently built correctly.

**Review by bwoodsend — COMMENTED** [review]
Putting test coverage is also a trendy one. There's an extra special one specifically for PyInstaller :vomiting_face:.

```restructuredtext
.. image:: https://img.shields.io/badge/coverage-something%20pathetically%20low-%23FF0000
```

The badges are all on their own lines rather than in a neat little row (see [the preview](https://github.com/Legorooj/pyinstaller/tree/readme-badges)). I vaguely remember seeing this before and the fix was something really stupid. I'm fairly certain you have to supply a `:target:` for each one too...

**Comment by Legorooj** [comment]
Fixed the formatting. I personally however don't see the need to point out how inadequate our test suite is.

**Review by bwoodsend — APPROVED** [review]
Ahh, I was just joking.

**Comment by Legorooj** [comment]
I know :P

**Pull request merged**
