### PR TITLE
hooks: Add hook for cherrypy

### PR DESCRIPTION
**Pull request by juharris**

### CODE REVIEW

**Comment by htgoebel** [comment]
Hmm, I wonder which version of cherrypy you are using. I can't find a module `cherrypy.wsgiserver.wsgiserver3` in the current (11.0) cherrypy sources. But the `CHANGES.rst` say:

> v6.1.0
>------
>
>* Combined wsgiserver2 and wsgiserver3 modules into a
>  single module, ``cherrypy.wsgiserver``.

and

> v9.0.0
>------
>
>* #1481: Move functionality from cherrypy.wsgiserver to
>  the `cheroot 5.0 <https://pypi.org/project/Cheroot/5.0.1/>`_
>  project.

Beside of this: Please add the standard copy right header (see the other hook files, mind to set the year to `2017` only).

**Comment by juharris** [comment]
Thanks for the heads up! Somehow I was on 3.8.0, I just did an upgrade and got 11.0.0, I'll test it out tomorrow.

**Comment by htgoebel** [comment]
I assume this to be solved. If not please reopen.

**Comment by juharris** [comment]
Yep confirmed that it's fine with 11.0.0.  Thanks again!

**Pull request closed without merging**
