### PR TITLE
Make test_option_w_ignore verify 'warnings' get imported

### PR DESCRIPTION
**Pull request by mnencia**
Closes: #3402

### CODE REVIEW

**Comment by mnencia** [comment]
On py 3.6 it fails with

~~~
'import warnings' failed; traceback:
E           Traceback (most recent call last):
E             File "/home/travis/virtualenv/python3.6.3/lib/python3.6/warnings.py", line 505, in <module>
E               _processoptions(sys.warnoptions)
E             File "/home/travis/virtualenv/python3.6.3/lib/python3.6/warnings.py", line 186, in _processoptions
E               _setoption(arg)
E             File "/home/travis/virtualenv/python3.6.3/lib/python3.6/warnings.py", line 192, in _setoption
E               import re
E             File "/home/travis/virtualenv/python3.6.3/lib/python3.6/re.py", line 122, in <module>
E               import enum
E           ModuleNotFoundError: No module named 'enum'
~~~

**Comment by mnencia** [comment]
The test highlighted that also 'enum' module must be part of
base_library.zip to support Python 3.6

**Comment by htgoebel** [comment]
Thanks for this quick fix :-)

Please put the change regarding "enum" into a commit of it's own, like you did in f101f6f3b93d5b633fa894612. Thanks.

When updating a pull-request, you can simply (force) push the updated branch to github again. This will automatically update the pull-request (which follows the branch, not the commit). So you do not need to close the pull-request and open a new one. This also has the benefit that the discussion history is kept. For detailed instructions please read [Updating a Pull-Request](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html#updating-a-pull-request) in the manual.

Please also take the change and rebase your branch on the current `develop` head. Thanks.

**Comment by mnencia** [comment]
Commit splitted, branch rebased :-)

**Comment by htgoebel** [comment]
Merged. Thank you!

**Pull request merged**
