### PR TITLE
Fix symlinking of data files from Resources to MacOS

### PR DESCRIPTION
**Pull request by lordwelch**

### CODE REVIEW

**Review by bwoodsend — APPROVED** [review]

**Comment by bwoodsend** [comment]
I'll release this tonight when I get home.

**Comment by bwoodsend** [comment]
Although, @rokm feel free to do it now if you're up for it.

**Comment by rokm** [comment]
> Although, @rokm feel free to do it now if you're up for it.

I'll need access to PyInstaller's PyPI.

**Comment by bwoodsend** [comment]
Hmm, I thought you were already added...

**Comment by bwoodsend** [comment]
Normality should be restored...

**Comment by Safihre** [comment]
Thanks for the quick fix @lordwelch @rokm and @bwoodsend  ❤️

**Pull request merged**
