### PR TITLE
Fixed install on cygwin (KeyError: 'cygwin' in bootloader/wscript).

### PR DESCRIPTION
**Pull request by ssouffri**

### CODE REVIEW

**Comment by htgoebel** [comment]
I have heavy stomachache with this, since cygwin *is not* Linux, so this may have unexpected side-effects. Please provide more information, esp, your use-case and the concrete error.

**Comment by ssouffri** [comment]
You are indeed right. There are many more issues I am running into despite all the is_cygwin checks in the code. I don't think i will ever have time to debug them all. Please disregard this pull request.

**Comment by htgoebel** [comment]
Never the less I would like to learn what is you use-case :-)

**Comment by ssouffri** [comment]
The issue is this:

stso@ANRSSOUFFRIAU-L ~
$ uname --all
CYGWIN_NT-6.1 ANRSSOUFFRIAU-L 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64
Cygwin

stso@ANRSSOUFFRIAU-L ~/dev/github/pyinstaller
$ python setup.py build
running build
running build_bootloader
No precompiled bootloader found. Trying to compile it for you ...
Setting top to                           :
/home/stso/dev/github/pyinstaller/bootloader
Setting out to                           :
/home/stso/dev/github/pyinstaller/bootloader/build
Checking for 'gcc' (C compiler)          : /usr/bin/gcc
Traceback (most recent call last):
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py",
line 122, in waf_entry_point
    run_commands()
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py",
line 183, in run_commands
    ctx=run_command(cmd_name)
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Scripting.py",
line 174, in run_command
    ctx.execute()
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Configure.py",
line 85, in execute
    super(ConfigurationContext,self).execute()
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py",
line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File
"/home/stso/dev/github/pyinstaller/bootloader/.waf-1.9.13-c4df071cf489d17f72b886deab7c5999/waflib/Context.py",
line 129, in recurse
    user_function(self)
  File "/home/stso/dev/github/pyinstaller/bootloader/wscript", line 423, in
configure
    DESTOS_TO_SYSTEM[ctx.env.DEST_OS])
KeyError: 'cygwin'
ERROR: Failed compiling the bootloader. Please compile manually and rerun
setup.py


The patch I made fixes the build but running pyinstaller then returns other
errors. I get the exact same issue when installing "PyInstaller-3.3.tar.gz"
with "pip2".

$ python ./pyinstaller.py
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
1398 INFO: PyInstaller: 3.4.dev0+g133d1815
1398 INFO: Python: 2.7.13
1445 INFO: Platform: CYGWIN_NT-6.1-2.9.0-0.318-5-3-x86_64-64bit
1453 INFO: wrote
/home/stso/dev/github/pyinstaller/lnpProxyApp/lnpProxyApp.spec
1507 INFO: UPX is not available.
1509 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer',
 '/home/stso/dev/github/pyinstaller/lnpProxyApp']
1509 INFO: checking Analysis
1522 INFO: Building because
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
changed
1522 INFO: Initializing module dependency graph...
1532 INFO: Initializing module graph hooks...
1657 INFO: running Analysis out00-Analysis.toc
1657 WARNING: Can not get binary dependencies for file:
/usr/bin/python2.7.exe
Traceback (most recent call last):
  File "/home/stso/dev/github/pyinstaller/PyInstaller/depend/bindepend.py",
line 721, in getImports
    return _getImports_pe(pth)
  File "/home/stso/dev/github/pyinstaller/PyInstaller/depend/bindepend.py",
line 103, in _getImports_pe
    pe = pefile.PE(pth, fast_load=True)


This I could also work around with this:

stso@ANRSSOUFFRIAU-L ~/dev/github/pyinstaller
$ git diff
diff --git a/PyInstaller/compat.py b/PyInstaller/compat.py
index 53d876b9..85dc6d71 100644
--- a/PyInstaller/compat.py
+++ b/PyInstaller/compat.py
@@ -35,6 +35,7 @@ is_py35 = sys.version_info >= (3, 5)
 is_py36 = sys.version_info >= (3, 6)
 is_py37 = sys.version_info >= (3, 7)

+print "platform:", sys.platform
 is_win = sys.platform.startswith('win')
 is_cygwin = sys.platform == 'cygwin'
 is_darwin = sys.platform == 'darwin'  # Mac OS X
diff --git a/PyInstaller/depend/bindepend.py
b/PyInstaller/depend/bindepend.py
index 89b86a28..a8c714f2 100644
--- a/PyInstaller/depend/bindepend.py
+++ b/PyInstaller/depend/bindepend.py
@@ -32,13 +32,13 @@ logger = logging.getLogger(__name__)

 seen = set()

+#import pefile
 # Import windows specific stuff.
 if is_win:
     from ..utils.win32.winmanifest import RT_MANIFEST
     from ..utils.win32.winmanifest import GetManifestResources
     from ..utils.win32.winmanifest import Manifest
     from ..utils.win32 import winresource
-    import pefile
     # Do not load all the directories information from the PE file
     pefile.fast_load = True

@@ -498,7 +498,7 @@ def selectImports(pth, xtrapath=None):
     for lib in dlls:
         if lib.upper() in seen:
             continue
-        if not is_win and not is_cygwin:
+        if not is_win:# and not is_cygwin:
             # all other platforms
             npth = lib
             lib = os.path.basename(lib)
@@ -714,7 +714,7 @@ def getImports(pth):
     """
     Forwards to the correct getImports implementation for the platform.
     """
-    if is_win or is_cygwin:
+    if is_win:# or is_cygwin:
         if pth.lower().endswith(".manifest"):
             return []
         try:

However then I ran into this problem and I gave up:

stso@ANRSSOUFFRIAU-L ~/dev/github/pyinstaller
$ python ./pyinstaller.py
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
platform: cygwin
750 INFO: PyInstaller: 3.4.dev0+gdd92c94b.mod
750 INFO: Python: 2.7.13
793 INFO: Platform: CYGWIN_NT-6.1-2.9.0-0.318-5-3-x86_64-64bit
795 INFO: wrote
/home/stso/dev/github/pyinstaller/lnpProxyApp/lnpProxyApp.spec
836 INFO: UPX is not available.
838 INFO: Extending PYTHONPATH with paths
['/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer',
 '/home/stso/dev/github/pyinstaller/lnpProxyApp']
838 INFO: checking Analysis
840 INFO: Building because
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
changed
840 INFO: Initializing module dependency graph...
849 INFO: Initializing module graph hooks...
970 INFO: running Analysis out00-Analysis.toc
1240 INFO: Caching module hooks...
1246 INFO: Analyzing
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
3305 INFO: Loading module hooks...
3306 INFO: Loading module hook "hook-encodings.py"...
4251 INFO: Looking for ctypes DLLs
4253 INFO: Analyzing run-time hooks ...
4256 INFO: Looking for dynamic libraries
6434 INFO: Looking for eggs
6434 INFO: Using Python library /usr/bin/libpython2.7.dll
6441 INFO: Warnings written to
/home/stso/dev/github/pyinstaller/lnpProxyApp/build/lnpProxyApp/warnlnpProxyApp.txt
6454 INFO: Graph cross-reference written to
/home/stso/dev/github/pyinstaller/lnpProxyApp/build/lnpProxyApp/xref-lnpProxyApp.html
6532 INFO: checking PYZ
6546 INFO: checking PKG
6555 INFO: Building because
/cygdrive/c/Projects/Applications/TOOL_LnpProxy/vlatest/apps/lnpProxyServer/lnpProxyApp.py
changed
6555 INFO: Building PKG (CArchive) out00-PKG.pkg
6626 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
6631 INFO: Bootloader
/home/stso/dev/github/pyinstaller/PyInstaller/bootloader/CYGWIN_NT-6.1-64bit/run.exe
6631 INFO: checking EXE
6631 INFO: Building EXE because out00-EXE.toc is non existent
6631 INFO: Building EXE from out00-EXE.toc

Kind Regards,

Stijn

**Pull request closed without merging**
