### PR TITLE
tests: requirements: remove wheel restriction for osx

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by htgoebel** [comment]
Please provide some information why thsi restriction is now removed. They will be helpful to understand this change in some years time.

**Comment by xoviat** [comment]
> Please provide some information why thsi restriction is now removed. They will be helpful to understand this change in some years time.

I have no idea but it doesn't cause any test failures. Perhaps it has something to do with pyinstaller-osx-tests.

**Comment by htgoebel** [comment]
Sorry for asking unprecicly. I meant why *you* removed this restriction. You just removed it since it now work without the restriction? This is okay, but should be mentioned in the commit message.

**Comment by xoviat** [comment]
@htgoebel Done.

**Comment by springermac** [comment]
I added the restriction because at the time the binary version of gevent caused a crash with xdist. This is no longer that case and using the binary of gevent speeds up the tests by about 2-3 minutes.

**Comment by htgoebel** [comment]
@springermac Thanks for the explanation. I squashed the commit message accordingly.
@xoviat Thanks for the updated commit-massage anyway :-)

**Pull request merged**
