### PR TITLE
Monthly dependency update

### PR DESCRIPTION
**Pull request by Legorooj**
Supercedes #4777

### CODE REVIEW

**Comment by bjones1** [comment]
Before you're done, squash this mess down to a single commit. Look at what I've done last month.

**Comment by Legorooj** [comment]
@bjones1 it's quicker to squash merge.

**Comment by bjones1** [comment]
Sounds good.

**Comment by bjones1** [comment]
I'm removing the ready to merge label until CI passes.

**Comment by bjones1** [comment]
Thanks for working on this!

**Pull request merged**
