### PR TITLE
SciPy >= 0.15.0 Hidden Import: `scipy.integrate`

### LINKED ISSUE #1908: SciPy >= 0.15.0 Hidden Import: `scipy.integrate`
In SciPy >= 0.15.0:

1. The `scipy.special.__init__` module imports...
1. The `scipy.special._ellip_harm` module imports...
1. The `scipy.special._ellip_harm_2` C extension imports...
1. The `scipy.integrate` package.

The third import is undetectable by PyInstaller. Attempting to import `scipy.special` within frozen applications raises runtime exceptions resembling:

```
Traceback (most recent call last):
  File "site-packages/scipy/interpolate/__init__.py", line 145, in <module>
  File "/home/leycec/py/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/interpolate/interpolate.py", line 16, in <module>
  File "/home/leycec/py/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/special/__init__.py", line 608, in <module>
  File "/home/leycec/py/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
  File "/home/leycec/py/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
  File "scipy/special/_ellip_harm_2.pyx", line 6, in init scipy.special._ellip_harm_2 (scipy/special/_ellip_harm_2.c:7441)
ImportError: No module named 'scipy.integrate'
```

Existing issues #1679, #1680, and #1742 all show users passing `--hidden-import=scipy.integrate` to `pyinstaller`, implying this to be a fairly widespread (albeit trivial) issue. I'll submit a pull request putting this problem to the sword... _any femtosecond now._

**Merry Easter Bunny Day.**

### PR DESCRIPTION
**Pull request by leycec**
This pull request fixes #1908 in the trivial way.

A new `hook-scipy.special._ellip_harm_2` hook imports the undetectable import of the `scipy.integrate` package by the `scipy.special._ellip_harm_2` Cython module. To exercise this fix, a new `test_scipy_special()` test has been added. For maintainability, this and the existing `test_scipy()` test have been moved from `test_libraries.py` into a new `test_hooks/test_scipy.py` script.

_Suuuuuper boring._ :cat:

### CODE REVIEW

**Comment by leycec** [comment]
_Hmmmm._ Travis skips SciPy tests, but `.travis.yml` lists `python-scipy` under `addons:`. I am Mr. confused. Anyone have any idea what that's about?

**Comment by codewarrior0** [comment]
Does anyone remember why any packages were added under `addons:`? On Travis, the tests are run in a virtualenv, which will ignore any system-installed packages and only use the ones installed into the virtualenv.

It looks like `scipy` isn't getting installed into the virtualenv. It should be listed in `tests/requirements.txt` to install it.

**Comment by leycec** [comment]
**palmhitsforehead**

Sweet! That's it. I'll update this pull request by adding `scipy >= 0.15.0` to `tests/requirements.txt` and `tests/requirements-mac.txt`. Would it be safe to add that dependency to ``tests/requirements-win.txt` as well?

**Comment by codewarrior0** [comment]
It only needs to be added to `tests/requirements.txt`. The `-mac` and `-win` files are added on to the base requirements when running on that platform, and are for platform-specific packages and such.

**Comment by leycec** [comment]
**palmhitsforehead** x 2

Perfect sense is made. Cheers!

**Comment by leycec** [comment]
_[wat](https://travis-ci.org/pyinstaller/pyinstaller/jobs/119191121)_

I'm not up on my Travis foo, sadly. Should I have done something here? I'm not quite sure how I could have interactively intervened in a non-interactive process, but... **there it is.**

**Comment by leycec** [comment]
_Ah-ha!_ `.travis.yml` contains the suspicious block:

```
install:
  # Install PyInstaller.
  - pip install -e .

  # Install dependencies for tests. Use pip-accel to cache compiled
  # packages and safe recompiling each time.
  # Download-progress bars break Travis's log view. Disable them by
  # piping output through another program (if output is not a tty, no
  # progress bars)
  - pip install pip-accel | cat
  - pip-accel install -r tests/requirements.txt | cat
```

Presumably, we need to pass an additional option to `pip-accel` to disable interactive prompts. And... that's a wrap for me. Tune in tomorrow as I tediously contemplate how to fix this. :tv:

**Comment by codewarrior0** [comment]
That's just the symptom. Fixing that would be nice, just to make the build fail faster.

The real problem is here:

```pip_accel.bdist    WARNING Build of scipy (0.17.0) failed, checking for missing dependencies ..
pip_accel.deps     INFO Checking for known dependencies of scipy ..
pip_accel.deps     INFO Found 2 known dependencies: gfortran and libatlas-base-dev
pip_accel.deps     INFO You seem to be missing 2 dependencies: gfortran and libatlas-base-dev
pip_accel.deps     INFO You can install them with this command: sudo apt-get install --yes gfortran libatlas-base-dev
```

Those two C-level deps need to be added to the `addons:` section of `.travis.yml`

Also, all of those Python packages ought to be removed from that section, because they are doing [exactly zero good](https://docs.travis-ci.com/user/languages/python#Travis-CI-Uses-Isolated-virtualenvs).

**Comment by leycec** [comment]
Thanks for the heap o' help! I've appended two new commits:

* **Adding SciPy dependencies** (`gfortran`, `libatlas-base-dev`) to the Linux-specific `.travis.yml`. I've left the [OS X-specific `.travis.yml`](https://github.com/pyinstaller/pyinstaller-osx-tests/blob/master/.travis.yml) alone, as that repository baffles and frightens me.
* **Removing all Python 2.7 packages** (i.e., prefixed by `python-`) from the Linux-specific `.travis.yml`. Let's see if the world collapses.
* **Documenting our continuous integration methodology.** I tried to adopt a high-level perspective, with particular attention to installing both Python and non-Python test dependencies. I found the process to be a bit _Jabberwocky_-ing. Hopefully, this documentation will assist other sacrificial lambs navigate the deadly maze of CI. <sup>← Including me in the future, when I inevitably forget... _again._</sup>

**Comment by leycec** [comment]
SciPy appears to install properly under both Appveyor and Linux Travis now. Tangerine dreams for all! :tangerine:

**Comment by matysek** [comment]
Thanks, I especially like the updated readme.

Binary wheels are not provided for windows. Could you please skip the scipy test on windows and as reason give this link? https://github.com/scipy/scipy/issues/5461

**Comment by leycec** [comment]
> Could you please skip the `scipy` test on windows and as reason give this link? scipy/scipy#5461

Thanks for the heads up! Absolutely. I'll do that.

Relatedly, have we considered installing [Miniconda](http://conda.pydata.org/miniconda.html) into our Appveyor environment? Doing so would give us access to the `conda` package manager, providing a variety of otherwise impossible-to-install dependencies. Like, SciPy.

Configuring Miniconda for Appveyor  doesn't _appear_ [that hard](https://github.com/sunpy/sunpy/blob/master/appveyor.yml), though I do wonder how well `conda` and `pip-accel` play together. (_Probably not well._)

Food for future thought, anyway.

**Comment by leycec** [comment]
**Done.** Let's see what the dread CI thinks.

**Comment by leycec** [comment]
**Done** <sup>x 2</sup>.

SciPy is now required _only_ for non-Windows platforms: namely, Linux and OS X. To do so, a new Linux-specific `requirements-linux.txt` has been added and Travis reconfigured to install from this file. This obsoletes the existing `requirements.txt`, which can (..._probably_) be safely removed now.

**Comment by leycec** [comment]
@matysek Three onefile tests appear to be failing under Windows with timeouts: `test_sphinx[onefile]`, `test_pylint[onefile]`, and `test_pygments[onefile]`. I have no idea why these tests in particular are failing to halt, but suspect this nothing to do with this pull request. <sup>Of course, I _would_ say that.</sup>

Actually, I _do_ have an idea. _Only_ onefile tests are failing. _No_ onedir tests are failing. This suggests that the frozen executables for these tests are too large under Windows, probably due to too many dependencies being discovered and frozen. If this is the case, decompressing these executables into temporary test directories could be... exhausting the test timeout? <sup>_Yup._ It's a bit far-fetched, but I've got nothin' better.</sup>

Ignoring these three unrelated tests, this pull request should be good to go. _Facepunch!_ :facepunch:

**Comment by htgoebel** [comment]
@leycec Thanks for the work on this. If there is still something todo for the tests, feel free to fix it ;-)

**Comment by leycec** [comment]
**_Sweet_-ness!** Thanks for the prompt merge. You are the constant rockstar. :guitar: 

I'm currently churning on #1919 (`scipy.linalg`), a hard prerequisite of #1901 (`excludedimports`). I hope to have something ready for public scrutiny in a few days. <sup>_Oh, the wishful thinking. Will it never end?_</sup>

**Pull request merged**
