### PR TITLE
Added donation link to Bountysource

### PR DESCRIPTION
**Pull request by ErikBjare**
As discussed in https://github.com/pyinstaller/pyinstaller/issues/2755

### CODE REVIEW

**Comment by htgoebel** [comment]
This should go into 3.3 so users can start donating :-)

**Comment by htgoebel** [comment]
But I want to add the other things mentioned in #2755, t00.

**Comment by ErikBjare** [comment]
I just responded to your email

**Comment by htgoebel** [comment]
I merged this manually to my WIP release branch. Thanks for pushing this topic!

**Pull request closed without merging**
