### PR TITLE
Fix: add qt5 styles plugin

### PR DESCRIPTION
**Pull request by glennra**

### CODE REVIEW

**Comment by bjones1** [comment]
I don't think this will work. First, this commit refers to an outdated version of PyInstaller; you need to pull/update from `develop`, not `master`. Second, the `styles` plugin is already included in the current develop - see https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/qt.py#L365.

**Comment by glennra** [comment]
This pull request is supposed to be against `master`. It is a one line change to fix the styles issue on that branch.

**Comment by bjones1** [comment]
OK, I see. I don't think @htgoebel usually accepts PRs to `master`, but I'll let him decide.

**Comment by htgoebel** [comment]
We are not accepting pull-request to `master`, as these are the stable releases, see https://pyinstaller.readthedocs.io/en/latest/development/branch-model.html?highlight=master. I changed the branch base to develop.

It's up to @bjones1 to decide whether this change is still useful/needed.

**Comment by bjones1** [comment]
Since this is already fixed in develop, I'm closing.

**Pull request closed without merging**
