### PR TITLE
util: print basename binaries

### PR DESCRIPTION
**Pull request by xoviat**
The commits will need to be cleaned up because I currently don't have access to a terminal.

### CODE REVIEW

**Comment by xoviat** [comment]
Actually I am giving up on this

**Comment by htgoebel** [comment]
What is the problem? If it's jsut the clean-up, I can do it.

**Comment by xoviat** [comment]
Okay then.

**Comment by htgoebel** [comment]
So this is working as expected and it's just the commits need to be squashed, right?

**Comment by xoviat** [comment]
That's correct.

2017-08-31 15:29 GMT-05:00 Hartmut Goebel <notifications@github.com>:

**Pull request closed without merging**
