### PR TITLE
loader: remove deprecated PEP-302 functionality from FrozenImporter

### PR DESCRIPTION
**Pull request by rokm**
Remove `find_module()` and `load_module()` from `FrozenImporter`. As per comments in these two methods, they are deprecated since python 3.4 in favor of PEP-451 loader.

Also remove the `FrozenPackageImporter` class which was used only from `FrozenImporter.load_module()`.

### CODE REVIEW

**Comment by BoboTiG** [comment]
May be related to #1455? In any cases, a NEWs entry would be great :)

**Review by BoboTiG — APPROVED** [review]
Great clean-up, LGTM 👍

**Comment by rokm** [comment]
> May be related to #1455?

I don't think so. There's no references to `BuiltinImporter` in there - it seems that was removed some time between 3.6 and 4.0 release...

**Review by Legorooj — APPROVED** [review]

**Comment by htgoebel** [comment]
I'm not sure removing this is a good idea: While these are deprecated, there might still be code out there using it - as they are only deprecated, not removed.

So I'm in favour of keeping them (which means reverting this commit) and remove them only after the our support has been removed in/by the oldest Python version we support.

WDYT?

**Comment by htgoebel** [comment]
Anyway, if keeping, this would need a news-fragment in the "breaking" section, too.

**Comment by rokm** [comment]
> I'm not sure removing this is a good idea: While these are deprecated, there might still be code out there using it - as they are only deprecated, not removed.
>
>So I'm in favour of keeping them (which means reverting this commit) and remove them only after the our support has been removed in/by the oldest Python version we support.
>
>WDYT?

PEP-451 was implemented in Python 3.4, so its module loading mechanism should be used in all Python versions that we still support. So as per PEP-451, the removed `find_module()` would be used only if `find_spec()` was not provided, and `load_module()` would be used only if `exec_module()` was not provided. And I think the test suite sufficiently confirms that the removal of those functions does not affect (standard) module loading.

I am, however, not familiar with PEP-302 enough to be 100% sure that some 3rd party package will not try using the removed functions directly - if that is even possible? So from that perspective, keeping those functions around "just in case" makes for a good argument.

On the other hand, I would prefer not having unused code around, because that complicates maintenance of the active part of the codebase. I.e., when changes are made there (e.g., #5354), one needs to come back and wonder if and how they apply to the other part. And if that other part is unused, it will also be untested, anyway...

So FWIW, reverting this commit shouldn't be a problem. But the behavior of the removed code and the behavior of the active code path w.r.t. to (namespace) package attributes will be different (and I have no idea if they were fully synchronized before, anyway).

**Comment by htgoebel** [comment]
I'm going to revert this for 4.2, since this is a breaking change.

My point is not about *our* code, but about "*customer*"'s code. The PEP-303 api is deprecated only, not removed even from the standard lib (for Python 3.7 AFAIK). I some "customer"'s code still relies on PEP-302 api their program will crash when frozen - which is not a good service of us. (Even if the reason for this crash is easy to spot, you can expect "customers"  not getting it and opening tickets.)

Please provide a new pull-request to be discussed and applied for 5.0 then.

For this pull-request please
- add a news-fragment in the "breaking" section
- remove renaming references to PEP-302 from the code `git grep -iE PEP.?302`
- what about tests/functional/test_import_pep302.py? I suggest to rename this file and the tests to no longer refer to PEP-302.

> But the behavior of the removed code and the behavior of the active code path w.r.t. to (namespace) package attributes will be different

This has always been the case, didn't it? IOr did I miss something?

**Comment by rokm** [comment]
OK, that sounds reasonable. I'll look into this again for 5.0.

**Pull request merged**
