### PR TITLE
modulegraph: fix AliasNode handling

### PR DESCRIPTION
**Pull request by toxeus**
Before, submodules that were imported from a package with an
aliased name would not be found but registered as `MissingModule`
and consequently not be packaged into the EXE.

### CODE REVIEW

**Comment by toxeus** [comment]
A single test failed for a particular configuration on AppVeyor. But this PR is not the reason for the failure. The current tip of the `develop` branch is [failing there too](https://ci.appveyor.com/project/matysek/pyinstaller/build/3239).

**Comment by toxeus** [comment]
@htgoebel how can I help to make sure this gets incorporated into the next release?

**Comment by lclc** [comment]
utACK.

This PR would help making our code nicer.

**Comment by htgoebel** [comment]
Thanks for this pull-request. Sorry for not merging it earlier, but now I did. Will go into the next release which is due the next days.

**Pull request merged**
