### PR TITLE
Add default hook implementation 

### PR DESCRIPTION
**Pull request by lkollar**
For any package which does not have a hook, copy the entire package (including binaries and data files) into the bundle. This makes it much simpler to package applications which use native extensions as no hook files need to be provided. The feature is behind the --use-default-hook flag.

This is a follow up to #3577. The change fixes a few bugs in the original implementation and adapts it for the current develop branch.

See previous conversation on this feature: #4145

Something happened with https://github.com/pyinstaller/pyinstaller/pull/4415 and now I can't get Travis to pick up the correct changes. I'm opening a new PR to see if I can get the CI to pass.

### CODE REVIEW

**Comment by lkollar** [comment]
This is now ready for review. @bjones1 this is a follow up to your original PR in #4145. This should make it much easier to package applications.

**Comment by Legorooj** [comment]
@lkollar pinging

**Comment by lkollar** [comment]
Sorry, but I won't be able to work in this PR. There is still quite a bit of work left and I don't need the feature anymore. Unless somebody else wants to pick it up, I'm happy to close it.

**Comment by Legorooj** [comment]
Don't close it yet. Thanks for letting us know though.

**Comment by Legorooj** [comment]
@lkollar I'm going to close this. Please don't delete the branch - I'll get to this at some point. I've got a PR I need to finish first. I'll use the idea behind this PR to create a new one.

**Pull request closed without merging**
