### PR TITLE
Modify numpy.core hook for supporting numpy MKL builds (fix #1881)

### LINKED ISSUE #1881: New numpy hook for intel mkl libraries
Hello - anaconda and winpython build numpy against Intel's mkl libraries. Building someone that uses numpy will need to have those libraries.

Here is a winpython hook:
http://stackoverflow.com/a/35853001

and I adapted that for anaconda & python3:
https://github.com/maqifrnswa/scimpy/blob/master/pyinstaller-hooks/hook-numpy.py

### PR DESCRIPTION
**Pull request by pwuertz**
If numpy is built with MKL support it depends on a set of libraries loaded at runtime. Since PyInstaller's static analysis can't find them they must be included manually (fix #1881).

The current `hook-numpy.core.py` only searches for libraries in the numpy package folder. The anaconda distribution for example places them in Python/Libraries/bin, so both folders must be searched for support and in particular the MKL libraries.

This PR should also enable numpy+MKL support on Linux and OSX systems.

### CODE REVIEW

**Comment by htgoebel** [comment]
@pwuertz Thanks for this patch. Do we have a test-case for this?

**Comment by pwuertz** [comment]
@htgoebel By test-case you meant use cases like those in #1881, or automated test for CI? Automated tests could be a bit difficult / resource hungry since Anaconda is the only distribution I know of that builds numpy with MKL support.

**Comment by dickreuter** [comment]
The error still persists:
Pyinstaller on mac compiles correctly but when running the file an error is produced:
Intel MKL FATAL ERROR: Error on loading function mkl_blas_avx_xdcopy

**Comment by pwuertz** [comment]
Unfortunately I can't debug this on OSX, but from the error message you posted the problem you are experiencing doesn't seem to be related to the bug we fixed in this PR. The problem here was a missing shared object / dll (Cannot load libmkl_avx2.so), while your MKL complains about a missing function (Error on loading function).

**Comment by dhyams** [comment]
I have not had a chance to test, but I would guess that the problem on a mac would be that the mkl files have a .dylib extension; not .dll or .so.  The PR here only looks for .so and .dll files.  For example, they are called

libmkl_avx2.dylib
libmkl_core.dylib 

and so forth.

**Pull request merged**
