### PR TITLE
Hooks: Fix the nltk hook

### PR DESCRIPTION
**Pull request by funtion**
Only add path to datas when it exists. Otherwise, it may have path not found error.

### CODE REVIEW

**Comment by funtion** [comment]
How do I get a pull request merged?

**Comment by funtion** [comment]
@htgoebel Could you please kindly help review at this PR?

**Comment by cur33** [comment]
I ran into this problem as well; it would be great if this could be merged.

**Comment by cwenner** [comment]
Common issue and the fix works. Would be great to merge. @bjones1

**Comment by cwenner** [comment]
On Linux and Windows, this error can also be worked around by creating the searched directories. Notably on Windows, one may want to run `subst d: c:\` and/or `subst e: c:\`.

On macOS, System Integrity Protection prevents the workaround and the only known approach is to edit the pyinstaller source.

**Comment by qiray** [comment]
Are there any problems with this request? It seems correct and fixes problems for many people.

**Comment by lemoncalamitous** [comment]
I think this needs to be merged, as I have problems when making Windows executable of my NLP application that utilizes `nltk` when using `PyInstaller==3.6`.

**Comment by cwenner** [comment]
@bjones1 @Legorooj @htgoebel - Can you please merge this? It is a critical blocker for several users, the solution is straightforward and verified. I don't see how this could be held up for a year.

**Comment by Legorooj** [comment]
Sorry that this has been buried.

A quick checklist to merge it:

* Add a changelog entry. - open the `news` directory and add a new file `3964.hooks.rst`:
```
Update hook-nltk to only add existing datas to data's
```

* Squash/amend: we want the changelog entry and the hook edit in the same commit

* Change the commit message to `Hooks: update nltk to only add existing directories`

**Comment by cur33** [comment]
Since @funtion hasn't responded, I was going to go make this change myself and make another PR, but it looks like it was already fixed back on April 1 thanks to @bjones1 and @sebastianhohmann .

**Comment by Legorooj** [comment]
@cur33 good point.

**Pull request closed without merging**
