### PR TITLE
fix bootloader onefile related operation to be unicode aware for win32

### PR DESCRIPTION
**Pull request by AndCycle**
this is a fix for #1866 

as I am not a experience programmer for C and win32 platform,
it would be nice if someone can review this before pull in

### CODE REVIEW

**Comment by matysek** [comment]
@codewarrior0 could you please find some time to review this since you did a lot of unicode :)

**Comment by codewarrior0** [comment]
Good catch. I think I noted this earlier: the `_tempnam` function ignores the base path you pass to it and uses the path from the environ `%TMP%` instead, which apparently is either stored as ANSI or converted to ANSI during the function call. So `pyi_get_temp_path` returns ANSI when it should return UTF-8. Changing to `_wtempnam` is the right fix.

The changes to `pyi_remove_temp_path` will not compile. This is because the SHFileOperation function is defined in shell32.lib which we do not link to. SHFileOperation is not a true system-level API or a C runtime API, but is a Shell API, which is a call to ask Windows Explorer to delete the file for you. I'd rather not link to shell32 or delegate anything to Windows Explorer because the behavior of Explorer can be customized in various ways using things like COM servers or copy hooks. In particular, I don't want it to possibly show a "Deleting files" dialog on app shutdown because of those customizations.

`pyi_remove_temp_path` still needs to be changed, though. The `_findfirst` and `_findnext` functions expect ANSI paths, but are receiving UTF-8 paths... this only worked because `pyi_get_temp_path` was similarly broken and returned ANSI paths. It might be sufficient to call `_wfindfirst` etc - I'll give that a try shortly.

**Comment by AndCycle** [comment]
@codewarrior0
maybe just exclude last two patch? 
b9730c3 is the unicode version of pyi_remove_temp_path.

**Comment by codewarrior0** [comment]
Very nice. That will save me some time. Let me just chop those last two off and run it through testing.

**Comment by codewarrior0** [comment]
Looks good to me. I rewrote your commit messages a bit and merged them manually. Thanks again!

**Pull request closed without merging**
