### PR TITLE
Fix django imports

### PR DESCRIPTION
**Pull request by zuck**
In Django-based projects all relevant modules of installed apps should now be collected by PyInstaller.

### CODE REVIEW

**Comment by htgoebel** [comment]
We may need to rebase this on current `develop` head since ther are overlapping changes in.

**Comment by zuck** [comment]
Maybe I'm wrong, but it seems the rebase isn't necessary (the commits are the same of #1548).

**Comment by htgoebel** [comment]
Hmm, it worked. I wonder why github shows these common commits here again, though.

**Comment by zuck** [comment]
I think because they come from a branch derived from the one used for #1548. BTW, glad to see it merged, thank you!

**Pull request merged**
