### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by tallforasmurf**
This brings the manual current except for the topic "Understanding PyInstaller Hooks" which is incomplete. Remaining open manual-related issues are:

#1513 not sure if I have dealt with this sufficiently, see new text

#1511 is to be held to 3.1 at least

#1463 (and #1335) awaiting more input re: Hooks

#1372 not clear if this should go in the manual as such, or if there should be a separate howto or wiki page

#896 query on mailing list re one-file merges

#895 to be held for 3.1

### CODE REVIEW

**Comment by matysek** [comment]
* I like the contents on the left side.
* We support Python 3.3+, not only 3.4+.
* For development branch the version is not `3.ndev-xxxxxx` but `3.n.dev0-xxxxxx'. See this wiki page for details: https://github.com/pyinstaller/pyinstaller/wiki/Development-Release
* in section `Verifying the installation fix path at 'Apple-supplied Python' to `/usr/bin/` add line about homebrew:
```
OS X (using Python installed by homebrew) /usr/local/bin
```
* section `Getting the Opened Document Names` is broken - issue #1309
* in compiling bootloader replace `python ./waf configure build install` by `python ./waf distclean all`
* remove the line `MinGW - stable and mature, uses gcc 3.4 as its base` - mingw-w64 is required
* remove the note about `inprocsrvr`:  `, and inprocsrvr*.dll (bootloader for in-process COM servers)`

I'm going to merge it and you can fix it directly. I especially like the clarity of the manual. Thanks for your work!

**Comment by htgoebel** [comment]
@tallforasmurf Thanks a lot :-)

**Comment by tallforasmurf** [comment]
> section Getting the Opened Document Names is broken - issue #1309

Does it still work if I build a 32-bit app following the directions that are displayed every time I run pyinstaller? So only broken for default 64-bit? Or broken for all versions?

> in compiling bootloader replace python ./waf configure build install by python ./waf distclean all

This appears twice -- change it also under "Building for Windows"?

**Comment by tallforasmurf** [comment]
Also, the bootloader sections says "use any Visual Studio" -- is this in conflict with the need for MnGW-64? Or are they alternate choices?

**Comment by codewarrior0** [comment]
They are alternate choices. You can use any version of Visual Studio to build the bootloader, or if you want to use MinGW, you must use MinGW-x64. MinGW-x64 supports the unicode entry points `wmain`/`wWinMain` but the regular MinGW does not.

**Comment by matysek** [comment]
> is this in conflict with the need for MnGW-64? Or are they alternate choices?

Yes they are alternative choices. We use Mingw-w64 to build the precompiled bootloader that is distributed with pyinstaller.

**Comment by matysek** [comment]
> in compiling bootloader replace python ./waf configure build install by python ./waf distclean all
> This appears twice -- change it also under "Building for Windows"?

Yes, this command also works when recompiling bootloader (the `distclean` step)

**Comment by matysek** [comment]
> section Getting the Opened Document Names is broken - issue #1309
> Does it still work if I build a 32-bit app following the directions that are displayed every time I run pyinstaller? So only broken for default 64-bit? Or broken for all versions?

No, it is broken for both - 32 and 64 bit:
* I tried to work on it for two weeks without success.
* I kept it in broken state for both.
* I kept it broken for both in the hope that someone will jump in and continue with that :-)

**Comment by tallforasmurf** [comment]
#375205c, to be pushed shortly. I left the description of the feature in place, but added a NOTE that it is broken, don't use it, and a link to this issue.

**Pull request merged**
