### PR TITLE
tests: enable flake8

### PR DESCRIPTION
**Pull request by xoviat**
This enables automatic checking of the diffs to ensure PEP8 compliance. Existing code is not affected.

### CODE REVIEW

**Comment by xoviat** [comment]
Evidence that this works:

https://travis-ci.org/xoviat/pyinstaller/jobs/268816597

**Comment by xoviat** [comment]
Reason for the changes: flake8 is automatically run only for pull requests and automatically against the correct pull request branch.

**Comment by htgoebel** [comment]
I now found time to look at this – I thought, it would be much more complicate, otherwise I would have reviewed it earlier.

Is there a special reason why the "lint" step is run on all oses and with all versions? I'd thought it would be okay to run it once.

**Comment by htgoebel** [comment]
[Needs to be run on all versions](http://flake8.pycqa.org/en/latest/):
> It is very important to install Flake8 on the correct version of Python for your needs. If you want Flake8 to properly parse new language features in Python 3.5 (for example), you need it to be installed on 3.5 for Flake8 to understand those features. In many ways, Flake8 is tied to the version of Python on which it runs.

But I assume we can save OS X (we do not test on Windows, either)

**Comment by htgoebel** [comment]
Superseded by #2864

**Pull request closed without merging**
